#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").  
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2009-03-27 13:28+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../client.py:118
msgid ""
"Usage:\n"
"        pkg [options] command [cmd_options] [operands]\n"
"\n"
"Basic subcommands:\n"
"        pkg install [-nvq] [--no-refresh] [--no-index] package...\n"
"        pkg uninstall [-nrvq] [--no-index] package...\n"
"        pkg list [-aHsuvf] [package...]\n"
"        pkg image-update [-fnvq] [--be-name name] [--no-refresh] [--no-"
"index]\n"
"        pkg refresh [--full] [publisher ...]\n"
"        pkg version\n"
"\n"
"Advanced subcommands:\n"
"        pkg info [-lr] [--license] [pkg_fmri_pattern ...]\n"
"        pkg search [-lrI] [-s server] query\n"
"        pkg verify [-Hqv] [pkg_fmri_pattern ...]\n"
"        pkg fix [pkg_fmri_pattern ...]\n"
"        pkg contents [-Hmr] [-o attribute ...] [-s sort_key]\n"
"            [-t action_type ... ] [pkg_fmri_pattern ...]\n"
"        pkg image-create [-fFPUz] [--force] [--full|--partial|--user] [--"
"zone]\n"
"            [-k ssl_key] [-c ssl_cert] [--no-refresh] \n"
"            [--variant <variant_spec>=<instance>]\n"
"            (-p|--publisher) name=uri dir\n"
"\n"
"        pkg set-property propname propvalue\n"
"        pkg unset-property propname ...\n"
"        pkg property [-H] [propname ...]\n"
"\n"
"        pkg set-publisher [-Ped] [-k ssl_key] [-c ssl_cert]\n"
"            [-O origin_uri] [-m mirror_to_add | --add-mirror=mirror_to_add]\n"
"            [-M mirror_to_remove | --remove-mirror=mirror_to_remove]\n"
"            [--enable] [--disable] [--no-refresh] [--reset-uuid] publisher\n"
"        pkg unset-publisher publisher ...\n"
"        pkg publisher [-HPa] [publisher ...]\n"
"        pkg history [-Hl]\n"
"        pkg purge-history\n"
"        pkg rebuild-index\n"
"\n"
"Options:\n"
"        -R dir\n"
"        --help or -?\n"
"\n"
"Environment:\n"
"        PKG_IMAGE"
msgstr ""
"使用方法:\n"
"        pkg [options] command [cmd_options] [operands]\n"
"\n"
"基本的なサブコマンド:\n"
"        pkg install [-nvq] [--no-refresh] [--no-index] package...\n"
"        pkg uninstall [-nrvq] [--no-index] package...\n"
"        pkg list [-aHsuvf] [package...]\n"
"        pkg image-update [-fnvq] [--be-name name] [--no-refresh] [--no-"
"index]\n"
"        pkg refresh [--full] [publisher ...]\n"
"        pkg version\n"
"\n"
"高度なサブコマンド:\n"
"        pkg info [-lr] [--license] [pkg_fmri_pattern ...]\n"
"        pkg search [-lrI] [-s server] query\n"
"        pkg verify [-Hqv] [pkg_fmri_pattern ...]\n"
"        pkg fix [pkg_fmri_pattern ...]\n"
"        pkg contents [-Hmr] [-o attribute ...] [-s sort_key]\n"
"            [-t action_type ... ] [pkg_fmri_pattern ...]\n"
"        pkg image-create [-fFPUz] [--force] [--full|--partial|--user] [--"
"zone]\n"
"            [-k ssl_key] [-c ssl_cert] [--no-refresh] \n"
"            [--variant <variant_spec>=<instance>]\n"
"            (-p|--publisher) name=uri dir\n"
"\n"
"        pkg set-property propname propvalue\n"
"        pkg unset-property propname ...\n"
"        pkg property [-H] [propname ...]\n"
"\n"
"        pkg set-publisher [-Ped] [-k ssl_key] [-c ssl_cert]\n"
"            [-O origin_uri] [-m mirror_to_add | --add-mirror=mirror_to_add]\n"
"            [-M mirror_to_remove | --remove-mirror=mirror_to_remove]\n"
"            [--enable] [--disable] [--no-refresh] [--reset-uuid] publisher\n"
"        pkg unset-publisher publisher ...\n"
"        pkg publisher [-HPa] [publisher ...]\n"
"        pkg history [-Hl]\n"
"        pkg purge-history\n"
"        pkg rebuild-index\n"
"\n"
"オプション:\n"
"        -R dir\n"
"        --help or -?\n"
"\n"
"環境:\n"
"        PKG_IMAGE"

#: ../client.py:216
msgid "-s and -v may not be combined"
msgstr "-s と -v を組み合わせることはできません"

#: ../client.py:292 ../client.py:1089 ../client.py:1366
msgid "no packages installed"
msgstr "インストール済みのパッケージが存在しません"

#: ../client.py:299
msgid "No specified packages have available updates"
msgstr "指定されたパッケージの中で、使用可能な更新を持つものは存在しません"

#: ../client.py:302
msgid "No installed packages have available updates"
msgstr "インストール済みパッケージの中で、使用可能な更新を持つものは存在しません"

#: ../client.py:328
#, python-format
msgid "no packages matching '%s' %s"
msgstr "'%s' に一致するパッケージが存在しません %s"

#: ../client.py:371
#, python-format
msgid "Created ZFS snapshot: %s"
msgstr "作成された ZFS スナップショット: %s"

#: ../client.py:401
msgid "verify: -v and -q may not be combined"
msgstr "verify: -v と -q を組み合わせることはできません"

#: ../client.py:456
msgid ""
"pkg: no packages matching the following patterns you specified are\n"
"installed on the system.\n"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージの中で、\n"
"システムにインストール済みのものは存在しません。\n"

#: ../client.py:466
#, python-format
msgid ""
"\n"
"All other patterns matched installed packages.  %s"
msgstr ""
"\n"
"ほかのパターンは、すべてインストール済みパッケージに一致しました。  %s"

#: ../client.py:507
msgid "image-update: -v and -q may not be combined"
msgstr "image-update: -v と -q を組み合わせることはできません"

#: ../client.py:510
#, python-format
msgid "image-update: command does not take operands ('%s')"
msgstr "image-update: コマンドはオペランドを取りません ('%s')"

#: ../client.py:520 ../client.py:563
#, python-format
msgid "No image rooted at '%s'"
msgstr "'%s' をルートに持つイメージは存在しません"

#: ../client.py:534 ../client.py:703
msgid "No updates available for this image."
msgstr "このイメージで使用可能な更新は存在しません。"

#: ../client.py:537
#, python-format
msgid ""
"image-update failed (inventory exception):\n"
"%s"
msgstr ""
"image-update が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:557
msgid ""
"WARNING: pkg(5) appears to be out of date, and should be updated before\n"
"running image-update.\n"
msgstr ""
"警告: pkg(5) が古いようなので、image-update を実行する前に\n"
"これを更新すべきです。\n"

#: ../client.py:559
msgid ""
"Please update pkg(5) using 'pfexec pkg install SUNWipkg' and then retry\n"
"the image-update."
msgstr ""
"「pfexec pkg install SUNWipkg」を使って pkg(5) を更新したあとで、\n"
"image-update を再試行してください。"

#: ../client.py:587
msgid ""
"\n"
"An unexpected error happened while preparing for image-update:"
msgstr ""
"\n"
"image-update の準備中に予期しないエラーが発生しました:"

#: ../client.py:594
#, python-format
msgid "image-update failed: %s"
msgstr "image-update が失敗しました: %s"

#: ../client.py:597
msgid "image-update cannot be done on live image"
msgstr "ライブイメージに image-update を実行することはできません"

#: ../client.py:619
#, python-format
msgid ""
"\n"
"An unexpected error happened during image-update: %s"
msgstr ""
"\n"
"image-update の実行中に予期しないエラーが発生しました: %s"

#: ../client.py:625
msgid ""
"NOTE: Please review release notes posted at:\n"
"   http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"注: 次の場所で公開されているリリースノートを確認してください:\n"
"   http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../client.py:672
msgid "install: at least one package name required"
msgstr "install: パッケージ名を少なくとも 1 つ指定する必要があります"

#: ../client.py:675
msgid "install: -v and -q may not be combined"
msgstr "install: -v と -q を組み合わせることはできません"

#: ../client.py:690 ../client.py:824 ../client.py:987 ../client.py:1547
#: ../client.py:1629 ../client.py:1753 ../client.py:1807 ../client.py:2183
#, python-format
msgid "'%s' is not an install image"
msgstr "'%s' はインストールイメージではありません"

#: ../client.py:722
#, python-format
msgid ""
"install failed (inventory exception):\n"
"%s"
msgstr ""
"install が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:748 ../client.py:865
msgid ""
"\n"
"An unexpected error happened while preparing for install:"
msgstr ""
"\n"
"install の準備中に予期しないエラーが発生しました:"

#: ../client.py:757
#, python-format
msgid "installation failed: %s"
msgstr "インストールが失敗しました: %s"

#: ../client.py:776
#, python-format
msgid "An unexpected error happened during installation: %s"
msgstr "インストール中に予期しないエラーが発生しました: %s"

#: ../client.py:806
msgid "uninstall: at least one package name required"
msgstr "uninstall: パッケージ名を少なくとも 1 つ指定する必要があります"

#: ../client.py:809
msgid "uninstall: -v and -q may not be combined"
msgstr "uninstall: -v と -q を組み合わせることはできません"

#: ../client.py:832
#, python-format
msgid ""
"uninstall failed (inventory exception):\n"
"%s"
msgstr ""
"uninstall が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:874
#, python-format
msgid "uninstallation failed: %s"
msgstr "アンインストールが失敗しました: %s"

#: ../client.py:893
#, python-format
msgid "An unexpected error happened during uninstallation: %s"
msgstr "アンインストール中に予期しないエラーが発生しました: %s"

#: ../client.py:965
#, python-format
msgid "%s is not a valid server URL."
msgstr "%s は有効なサーバー URL ではありません。"

#: ../client.py:1057
msgid "info: -l and -r may not be combined"
msgstr "info: -l と -r を組み合わせることはできません"

#: ../client.py:1060
msgid "info: must request remote info for specific packages"
msgstr "info: 特定のパッケージではリモートの情報を要求する必要があります"

#: ../client.py:1106 ../gui/data/packagemanager.glade.h:49
#: ../packagemanager.py:1167
msgid "Installed"
msgstr "インストール済み"

#: ../client.py:1108
msgid "Not installed"
msgstr "インストール済みでない"

#: ../client.py:1112
msgid "          Name:"
msgstr "                    名前:"

#: ../client.py:1114
msgid "       Summary:"
msgstr "                    概要:"

#: ../client.py:1117
msgid "      Category:"
msgstr "                カテゴリ:"

#: ../client.py:1124
msgid "         State:"
msgstr "                    状態:"

#. XXX even more info on the publisher would be nice?
#: ../client.py:1127
msgid "     Publisher:"
msgstr "    出版社:"

#: ../client.py:1128
msgid "       Version:"
msgstr "             バージョン:"

#: ../client.py:1129
msgid " Build Release:"
msgstr "        ビルドリリース:"

#: ../client.py:1130
msgid "        Branch:"
msgstr "                    分岐:"

#: ../client.py:1131
msgid "Packaging Date:"
msgstr "パッケージ化の日付:"

#: ../client.py:1132
msgid "          Size:"
msgstr "                 サイズ:"

#: ../client.py:1133
msgid "          FMRI:"
msgstr "                  FMRI:"

#: ../client.py:1141 ../client.py:1471
msgid ""
"pkg: no packages matching the following patterns you specified are\n"
"installed on the system.  Try specifying -r to query remotely:"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージの中で、\n"
"システムにインストール済みのものが存在しません。-r を指定して、リモートで照会を行なってください:"

#: ../client.py:1145 ../client.py:1475
msgid ""
"pkg: no packages matching the following patterns you specified were\n"
"found in the catalog.  Try relaxing the patterns, refreshing, and/or\n"
"examining the catalogs:"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージが、カタログ内に見つか\n"
"りませんでした。パターンの条件緩和、再表示、カタログの検査のいずれか\n"
"、あるいはそのすべてを試してください:"

#: ../client.py:1161
#, python-format
msgid "'%s' matches multiple packages"
msgstr "'%s' は複数のパッケージに一致します"

#: ../client.py:1167
msgid "no license information could be found for the following packages:"
msgstr "次のパッケージのライセンス情報が見つかりませんでした:"

#: ../client.py:1322
msgid "contents: -l and -r may not be combined"
msgstr "contents: -l と -r を組み合わせることはできません"

#: ../client.py:1325
msgid "contents: must request remote contents for specific packages"
msgstr "contents: 特定のパッケージではリモートの内容を要求する必要があります"

#: ../client.py:1339
#, python-format
msgid "contents: -m and %s may not be specified at the same time"
msgstr "contents: -m と %s を同時に指定することはできません"

#: ../client.py:1344 ../client.py:1347
#, python-format
msgid "Invalid attribute '%s'"
msgstr "無効な属性 '%s'"

#: ../client.py:1407 ../client.py:1413 ../modules/client/api_errors.py:144
#, python-format
msgid "pkg: '%s' matches multiple packages"
msgstr "pkg: '%s' は複数のパッケージに一致します"

#: ../client.py:1490
#, python-format
msgid "pkg: %s/%s catalogs successfully updated:"
msgstr "pkg: %s/%s カタログの更新に成功しました:"

#: ../client.py:1513
#, python-format
msgid "Could not update catalog for '%s' due to insufficient permissions."
msgstr "アクセス権が十分でないため '%s' のカタログを更新できませんでした。"

#: ../client.py:1517
msgid "Could not update a catalog due to insufficient permissions."
msgstr "アクセス権が十分でないためカタログを更新できませんでした。"

#: ../client.py:1520
msgid ""
"Please try the command again using pfexec, or otherwise increase \n"
"    your permissions."
msgstr ""
"pfexec を使用してコマンドを再試行するか、\n"
"    アクセス権を取得してください。"

#: ../client.py:1554
msgid "'pkg publisher' will show a list of publishers."
msgstr "'pkg publisher' は発行元のリストを表示します。"

#: ../client.py:1612
msgid "requires a publisher name"
msgstr "発行元名が必要です"

#: ../client.py:1614
msgid "only one publisher name may be specified"
msgstr "指定できる発行元名は 1 つだけです"

#: ../client.py:1620
msgid "the -p and -d options may not be combined"
msgstr "-p オプションと -d オプションを組み合わせることはできません"

#: ../client.py:1644
msgid ""
"publisher does not exist. Use -O to define origin URI for new publisher."
msgstr ""
"発行元が存在しません。 -O を使用して新しい発行元の起点 URI を定義してください。"

#: ../client.py:1726
#, python-format
msgid ""
"The origin URIs for '%s' do not appear to point to a valid pkg server.\n"
"Please check the server's address and client's network configuration.\n"
"Additional details:\n"
"\n"
"%s"
msgstr ""
"'%s' の起点 URI は有効な pkg  サーバーを指していないようです。\n"
"サーバーのアドレスとクライアントのネットワーク構成を確認してください。\n"
"その他の詳細:\n"
"\n"
"%s"

#: ../client.py:1779
#, python-format
msgid "Removal failed for '%(pub)s': %(msg)s"
msgstr "'%(pub)s' の削除に失敗しました: %(msg)s"

#: ../client.py:1851
msgid "PUBLISHER"
msgstr "発行元"

#: ../client.py:1851
msgid "TYPE"
msgstr "タイプ"

#: ../client.py:1851
msgid "STATUS"
msgstr "状態"

#: ../client.py:1852
msgid "URI"
msgstr "URI"

#: ../client.py:1867
msgid "(preferred)"
msgstr "(優先)"

#: ../client.py:1869
msgid "(disabled)"
msgstr "(無効)"

#. XXX get the real origin status
#: ../client.py:1876
msgid "origin"
msgstr "起点"

#. XXX get the real mirror status
#: ../client.py:1880
msgid "mirror"
msgstr "ミラー"

#: ../client.py:1886
msgid "              SSL Key:"
msgstr "              SSL キー:"

#: ../client.py:1887
msgid "             SSL Cert:"
msgstr "             SSL 証明書:"

#: ../client.py:1899
msgid " Cert. Effective Date:"
msgstr " 証明書の発効日:"

#: ../client.py:1901
msgid "Cert. Expiration Date:"
msgstr "証明書の有効期限:"

#: ../client.py:1908
msgid "           Origin URI:"
msgstr "           起点 URI:"

#: ../client.py:1914
msgid "           Mirror URI:"
msgstr "           ミラー URI:"

#: ../client.py:1928
msgid "            Publisher:"
msgstr "    出版社:"

#: ../client.py:1929
msgid "                Alias:"
msgstr "                別名:"

#: ../client.py:1939
msgid "          Client UUID:"
msgstr "          クライアント UUID:"

#: ../client.py:1940
msgid "      Catalog Updated:"
msgstr "      カタログの更新:"

#: ../client.py:1942 ../client.py:1944
msgid "              Enabled:"
msgstr "              有効:"

#: ../client.py:1942
msgid "No"
msgstr "いいえ"

#: ../client.py:1944
msgid "Yes"
msgstr "はい"

#: ../client.py:1955
msgid "set-property: requires a property name and value"
msgstr "set-property: プロパティー名と値が必要です"

#: ../client.py:1958
msgid ""
"set-property: set-publisher must be used to change the preferred publisher"
msgstr ""
"set-property: 優先された発行元を変更するには set-publisher を使用する必要があります"

#: ../client.py:1982
msgid "unset-property: requires at least one property name"
msgstr "unset-property: プロパティー名を少なくとも 1 つ指定する必要があります"

#: ../client.py:1986
msgid ""
"unset-property: set-publisher must be used to change the preferred publisher"
msgstr ""
"unset-property: 優先された発行元を変更するには set-publisher を使用する必要があります"

#: ../client.py:1993
#, python-format
msgid "unset-property: no such property: %s"
msgstr "unset-property: そのようなプロパティーは存在しません: %s"

#: ../client.py:2014
#, python-format
msgid "property: no such property: %s"
msgstr "property: そのようなプロパティーは存在しません: %s"

#: ../client.py:2077 ../client.py:2112
msgid ""
"image-create requires publisher argument to be of the form '<prefix>=<url>'."
msgstr ""
"image-create では、発行元の引数が「<prefix>=<url>」の形式になっている必要があります。"

#: ../client.py:2086
msgid ""
"image-create requires variant arguments to be of the form '<name>=<value>'."
msgstr ""
"image-create では、バリアントの引数が「<name>=<value>」の形式になっている必要があります。"

#: ../client.py:2092
msgid "image-create requires a single image directory path"
msgstr "image-create では、単一のイメージディレクトリパスを指定する必要があります"

#: ../client.py:2097
#, python-format
msgid "pkg: set-publisher: SSL key file '%s' does not exist"
msgstr "pkg: set-publisher: SSL キーのファイル '%s' が存在しません"

#: ../client.py:2104
#, python-format
msgid "pkg: set-publisher: SSL key cert '%s' does not exist"
msgstr "pkg: set-publisher: SSL キーの証明書 '%s' が存在しません"

#: ../client.py:2109
msgid "image-create requires a publisher argument"
msgstr "image-create には発行元の引数が必要です"

#: ../client.py:2116
#, python-format
msgid "image-create requires that a prefix not match: %s"
msgstr "image-create では、接頭辞が一致しないことが要求されます: %s"

#: ../client.py:2121
msgid "image-create: publisher prefix has invalid characters"
msgstr "image-create: 発行元の接頭辞に無効な文字が含まれています"

#: ../client.py:2126
msgid "image-create: publisher URI is invalid"
msgstr "image-create: 発行元の URI が無効です"

#: ../client.py:2133
#, python-format
msgid "there is already an image at: %s"
msgstr "次の場所にすでにイメージが存在します: %s"

#: ../client.py:2134 ../client.py:2141
msgid "To override, use the -f (force) option."
msgstr "上書きするには、-f (force) オプションを使用します。"

#: ../client.py:2140
#, python-format
msgid "Non-empty directory: %s"
msgstr "空でないディレクトリ: %s"

#: ../client.py:2149
#, python-format
msgid "cannot create image at %s: %s"
msgstr "%s にイメージを作成できません: %s"

#: ../client.py:2156
#, python-format
msgid ""
"The URI '%s' does not appear to point to a valid pkg server.\n"
"Please check the server's address and client's network configuration.\n"
"Additional details:\n"
"\n"
"%s"
msgstr ""
"URI '%s' は有効な pkg  サーバーを指していないようです。\n"
"サーバーのアドレスとクライアントのネットワーク構成を確認してください。\n"
"その他の詳細:\n"
"\n"
"%s"

#: ../client.py:2177
#, python-format
msgid "rebuild-index: command does not take operands ('%s')"
msgstr "rebuild-index: コマンドはオペランドを取りません ('%s')"

#: ../client.py:2215
msgid "history: -H and -l may not be combined"
msgstr "history: -H と -l を組み合わせることはできません"

#: ../client.py:2219
msgid "TIME"
msgstr "時間"

#: ../client.py:2220
msgid "OPERATION"
msgstr "操作"

#: ../client.py:2220
msgid "CLIENT"
msgstr "クライアント"

#: ../client.py:2220
msgid "OUTCOME"
msgstr "結果"

#: ../client.py:2313
#, python-format
msgid "illegal global option -- %s"
msgstr "不正なグローバルオプション -- %s"

#: ../client.py:2321
#, python-format
msgid "%(opt)s takes argument of form name=value, not %(arg)s"
msgstr "%(opt)s は、%(arg)s ではなく、形式 name=value の引数を取ります"

#: ../client.py:2355 ../client.py:2365
#, python-format
msgid "-R not allowed for %s subcommand"
msgstr "-R は %s サブコマンドでは許可されていません"

#: ../client.py:2360 ../client.py:2466 ../publish.py:358
#, python-format
msgid "illegal %s option -- %s"
msgstr "不正な %s オプション -- %s"

#: ../client.py:2368
#, python-format
msgid "version: command does not take operands ('%s')"
msgstr "version: コマンドはオペランドを取りません ('%s')"

#: ../client.py:2393
msgid ""
"Could not find image.  Use the -R option or set $PKG_IMAGE to point\n"
"to an image, or change the working directory to one inside the image."
msgstr ""
"イメージが見つかりませんでした。-R オプションを使用するか $PKG_IMAGE を設定してイメージの場所を指定するか、\n"
"あるいは作業ディレクトリをイメージの内側に変更してください。"

#: ../client.py:2407
msgid "No image found."
msgstr "イメージが見つかりません。"

#: ../client.py:2413
#, python-format
msgid "client configuration error: %s"
msgstr "クライアント構成エラー: %s"

#: ../client.py:2458
msgid "History purged."
msgstr "履歴が削除されます。"

#: ../client.py:2463 ../publish.py:356
#, python-format
msgid "unknown subcommand '%s'"
msgstr "不明なサブコマンド '%s'"

#: ../client.py:2499
#, python-format
msgid ""
"\n"
"Maximum number of network retries exceeded during download. Details follow:\n"
"%s"
msgstr ""
"\n"
"ダウンロード中にネットワーク再試行の最大回数を超えました。詳細は次のとおりです:\n"
"%s"

#: ../client.py:2506
msgid ""
"An error was encountered while attempting to retrieve package or file data "
"for the requested operation."
msgstr ""
"要求された操作に対するパッケージまたはファイルデータの取得を"
"試行しているときに、エラーが発生しました。"

#: ../client.py:2513
msgid ""
"\n"
"Unable to contact a valid package depot. This may be due to a problem with "
"the server, network misconfiguration, or an incorrect pkg client "
"configuration.  Please check your network settings and attempt to contact "
"the server using a web browser."
msgstr ""
"\n"
"有効なパッケージデポに接続できません。原因としては、"
"サーバーの問題、ネットワーク構成の誤り、pkg クライアント構成の"
"誤りなどが考えられます。ネットワークの設定を確認し、Web ブラウザを使用して"
"サーバーに接続してみてください。"

#: ../client.py:2518
#, python-format
msgid ""
"\n"
"Additional details:\n"
"\n"
"%s"
msgstr ""
"\n"
"その他の詳細:\n"
"\n"
"%s"

#: ../client.py:2525
msgid ""
"An error was encountered while attempting to load history information\n"
"about past client operations."
msgstr ""
"以前のクライアント操作に関する履歴情報の読み込みを試行しているときに、\n"
"エラーが発生しました。"

#: ../client.py:2534
msgid ""
"An error was encountered while attempting to store information about the\n"
"current operation in client history."
msgstr ""
"現在の操作に関する情報をクライアント履歴に格納しようとしたときに、\n"
"エラーが発生しました。"

#: ../client.py:2544
msgid "An error was encountered while attempting to purge client history."
msgstr "クライアント履歴の削除を試行しているときに、エラーが発生しました。"

#: ../client.py:2551
#, python-format
msgid ""
"The pkg command appears out of sync with the libraries provided \n"
"by SUNWipkg. The client version is %(client)s while the library API version "
"is %(api)s"
msgstr ""
"pkg コマンドは、SUNWipkg で提供されているライブラリと同期がとれていない\n"
"ようです。クライアントのバージョンが %(client)s であるのに対して、ライブラリ API "
"のバージョンは %(api)s です。"

#: ../client.py:2563 ../publish.py:382
#, python-format
msgid ""
"\n"
"\n"
"This is an internal error.  Please let the developers know about this\n"
"problem by filing a bug at http://defect.opensolaris.org and including the\n"
"above traceback and this message.  The version of pkg(5) is '%s'."
msgstr ""
"\n"
"\n"
"これは内部エラーです。この問題を開発者に知らせるために、\n"
"http://defect.opensolaris.org でバグ情報を入力し、上記のトレースバック\n"
"とこのメッセージを含めてください。pkg(5) のバージョンは '%s' です。"

#. self.__add_package_to_category(_("All"),None,None,None);
#. Category names until xdg is imported.
#. from xdg.DesktopEntry import *
#. entry = DesktopEntry ()
#. directory = '/usr/share/desktop-directories'
#. for root, dirs, files in os.walk (directory):
#. for name in files:
#. entry.parse (os.path.join (root, name))
#. self.__add_category_to_section (entry.getName (),
#. _('Applications Desktop'))
#: ../gui/data/l10n.py:31 ../packagemanager.py:3524 ../packagemanager.py:3526
#: ../packagemanager.py:3551
msgid "Accessories"
msgstr "アクセサリ"

#: ../gui/data/l10n.py:32
msgid "Administration and Configuration"
msgstr "管理と構成"

#: ../gui/data/l10n.py:33
msgid "Applets"
msgstr "アプレット"

#: ../gui/data/l10n.py:34
msgid "Application and Web Servers"
msgstr "アプリケーションと Web サーバー"

#: ../gui/data/l10n.py:35
msgid "C"
msgstr "C"

#: ../gui/data/l10n.py:36
msgid "C++"
msgstr "C++"

#: ../gui/data/l10n.py:37
msgid "Configuration and Preferences"
msgstr "構成と設定"

#: ../gui/data/l10n.py:38 ../packagemanager.py:3569
msgid "Core"
msgstr "コア"

#: ../gui/data/l10n.py:39
msgid "Databases"
msgstr "データベース"

#: ../gui/data/l10n.py:40
msgid "Databases (System)"
msgstr "データベース (システム)"

#: ../gui/data/l10n.py:41
msgid "Desktop"
msgstr "デスクトップ"

#: ../gui/data/l10n.py:42
msgid "Display"
msgstr "ディスプレイ"

#: ../gui/data/l10n.py:43
msgid "Distribution Tools"
msgstr "ディストリビューションツール"

#: ../gui/data/l10n.py:44
msgid "Documentation"
msgstr "マニュアル"

#: ../gui/data/l10n.py:45
msgid "Enterprise Management"
msgstr "エンタープライズ管理"

#: ../gui/data/l10n.py:46
msgid "File Managers"
msgstr "ファイルマネージャー"

#: ../gui/data/l10n.py:47
msgid "File System"
msgstr "ファイルシステム"

#: ../gui/data/l10n.py:48
msgid "Fonts"
msgstr "フォント"

#: ../gui/data/l10n.py:49
msgid "GNOME and GTK+"
msgstr "GNOME と GTK+"

#: ../gui/data/l10n.py:50
msgid "GNU"
msgstr "GNU"

#: ../gui/data/l10n.py:51 ../packagemanager.py:3528 ../packagemanager.py:3532
#: ../packagemanager.py:3536 ../packagemanager.py:3553
msgid "Games"
msgstr "ゲーム"

#: ../gui/data/l10n.py:52
msgid "Graphics and Imaging"
msgstr "グラフィックスと画像処理"

#: ../gui/data/l10n.py:53
msgid "Hardware"
msgstr "ハードウェア"

#: ../gui/data/l10n.py:54
msgid "High Performance Computing"
msgstr "HPC"

#: ../gui/data/l10n.py:55
msgid "Integrated Development Environments"
msgstr "統合開発環境"

#: ../gui/data/l10n.py:56
msgid "Internationalization"
msgstr "国際化"

#: ../gui/data/l10n.py:57 ../packagemanager.py:3557
msgid "Internet"
msgstr "インターネット"

#: ../gui/data/l10n.py:58
msgid "Java"
msgstr "Java"

#: ../gui/data/l10n.py:59
msgid "Libraries"
msgstr "ライブラリ"

#: ../gui/data/l10n.py:60
msgid "Libraries (System)"
msgstr "ライブラリ (システム)"

#: ../gui/data/l10n.py:61
msgid "Localizations (Desktop)"
msgstr "言語単位 (デスクトップ)"

#: ../gui/data/l10n.py:62
msgid "Localizations (System)"
msgstr "言語単位 (システム)"

#: ../gui/data/l10n.py:63 ../packagemanager.py:3573
msgid "Media"
msgstr "メディア"

#: ../gui/data/l10n.py:64
msgid "Networking"
msgstr "ネットワーク処理"

#: ../gui/data/l10n.py:65 ../packagemanager.py:3559 ../packagemanager.py:3578
msgid "Office"
msgstr "オフィス"

#: ../gui/data/l10n.py:66
msgid "Other Languages"
msgstr "その他のプログラミング言語"

#: ../gui/data/l10n.py:67
msgid "Other Peripherals"
msgstr "その他の周辺装置"

#: ../gui/data/l10n.py:68
msgid "PHP"
msgstr "PHP"

#: ../gui/data/l10n.py:69
msgid "Packaging"
msgstr "パッケージ処理"

#: ../gui/data/l10n.py:70
msgid "Perl"
msgstr "Perl"

#: ../gui/data/l10n.py:71
msgid "Plug-ins and Run-times"
msgstr "プラグインとランタイム"

#: ../gui/data/l10n.py:72
msgid "Ports"
msgstr "ポート"

#: ../gui/data/l10n.py:73
msgid "Printing"
msgstr "印刷処理"

#: ../gui/data/l10n.py:74
msgid "Python"
msgstr "Python"

#: ../gui/data/l10n.py:75
msgid "Ruby"
msgstr "Ruby"

#: ../gui/data/l10n.py:76
msgid "Scripts"
msgstr "スクリプト"

#: ../gui/data/l10n.py:77
msgid "Security"
msgstr "セキュリティー"

#: ../gui/data/l10n.py:78
msgid "Services"
msgstr "サービス"

#: ../gui/data/l10n.py:79
msgid "Sessions"
msgstr "セッション"

#: ../gui/data/l10n.py:80
msgid "Shells"
msgstr "シェル"

#: ../gui/data/l10n.py:81
msgid "Software Management"
msgstr "ソフトウェア管理"

#: ../gui/data/l10n.py:82
msgid "Sound and Video"
msgstr "サウンドとビデオ"

#: ../gui/data/l10n.py:83
msgid "Source Code Management"
msgstr "ソースコード管理"

#: ../gui/data/l10n.py:84
msgid "Storage"
msgstr "ストレージ"

#: ../gui/data/l10n.py:85 ../packagemanager.py:1269
msgid "System"
msgstr "システム"

#: ../gui/data/l10n.py:86
msgid "System Utilities"
msgstr "システムユーティリティー"

#: ../gui/data/l10n.py:87
msgid "Text Tools"
msgstr "テキストツール"

#: ../gui/data/l10n.py:88
msgid "Trusted"
msgstr "トラステッド"

#: ../gui/data/l10n.py:89 ../packagemanager.py:3565
msgid "Universal Access"
msgstr "ユニバーサルアクセス"

#: ../gui/data/l10n.py:90
msgid "Virtualization"
msgstr "仮想化"

#: ../gui/data/l10n.py:91
msgid "Window Managers"
msgstr "ウィンドウマネージャー"

#: ../gui/data/l10n.py:92
msgid "X11"
msgstr "X11"

#: ../gui/data/l10n.py:93
msgid "X11 (System)"
msgstr "X11 (システム)"

#: ../gui/data/addmoresoftware.desktop.in.h:1
msgid "Add More Software"
msgstr "ソフトウェアの追加"

#: ../gui/data/addmoresoftware.desktop.in.h:2
#: ../gui/data/packagemanager.desktop.in.h:1
msgid "Install, update and remove software packages"
msgstr "ソフトウエアパッケージをインストール、更新または削除します"

#. XXX Remove and use _() where self._ and self.parent._ are being used
#: ../gui/data/packagemanager.desktop.in.h:2
#: ../gui/data/packagemanager.glade.h:59 ../gui/modules/webinstall.py:304
#: ../packagemanager.py:177 ../packagemanager.py:2076
#: ../packagemanager.py:3159
msgid "Package Manager"
msgstr "パッケージマネージャー"

#: ../gui/data/packagemanager.glade.h:1
msgid "<b>Add new repositories and manage existing ones.</b>"
msgstr "<b>新しいリポジトリの追加と既存のリポジトリの管理を行います。</b>"

#: ../gui/data/packagemanager.glade.h:2
msgid "<b>Apply the following changes:</b>"
msgstr "<b>次の変更を適用します:</b>"

#: ../gui/data/packagemanager.glade.h:3
msgid ""
"<b>Create New Boot Environment</b>\n"
"\n"
"Update All creates a new boot environment (BE) as a means of archiving the\n"
"current BE. The new BE consists of the updated packages and is the default "
"BE\n"
"when the system is rebooted.\n"
msgstr ""
"<b>新しいブート環境を作成します</b>\n"
"\n"
"「すべて更新」は、現在のブート環境 (BE) をアーカイブする手段として新しい BE を\n"
"作成します。新しい BE は、更新されたパッケージから構成され、システムの再起動時にはデフォルトの"
"BE\n"
"になります。\n"

#: ../gui/data/packagemanager.glade.h:9
msgid "<b>Delete, rename and activate boot environments.</b>"
msgstr "<b>ブート環境の削除、名前の変更、およびアーカイブを行います。</b>"

#: ../gui/data/packagemanager.glade.h:10
msgid "<b>Modify Repository URL</b>"
msgstr "<b>リポジトリ URL の変更</b>"

#: ../gui/data/packagemanager.glade.h:11
msgid "<b>PACKAGE NAME</b>"
msgstr "<b>パッケージ名</b>"

#: ../gui/data/packagemanager.glade.h:12
msgid "<b>Package Name</b>"
msgstr "<b>パッケージ名</b>"

#: ../gui/data/packagemanager.glade.h:13
msgid "<b>Review the packages to be removed:</b>"
msgstr "<b>削除するパッケージを確認してください:</b>"

#: ../gui/data/packagemanager.glade.h:14
msgid "<b>Search</b>"
msgstr "<b>検索</b>"

#: ../gui/data/packagemanager.glade.h:15
msgid "<b>Startup</b>"
msgstr "<b>起動</b>"

#: ../gui/data/packagemanager.glade.h:16
msgid "<b>_Mirrors</b>"
msgstr "<b>ミラー(_M)</b>"

#: ../gui/data/packagemanager.glade.h:17
msgid "<b>_SSL Key and Certificate</b>"
msgstr "<b>SSL キーと証明書(_S)</b>"

#: ../gui/data/packagemanager.glade.h:18
msgid "<big><b>Package Manager Web Installer</b></big>"
msgstr "<big><b>パッケージマネージャー Web インストーラ</b></big>"

#: ../gui/data/packagemanager.glade.h:19
msgid "<i>_Repository:</i>"
msgstr "<i>リポジトリ(_R):</i>"

#: ../gui/data/packagemanager.glade.h:20
msgid "About"
msgstr "バージョン情報"

#: ../gui/data/packagemanager.glade.h:21
msgid "About Glade"
msgstr "グレードについて"

#: ../gui/data/packagemanager.glade.h:22
msgid "B_rowse"
msgstr "参照(_R)"

#: ../gui/data/packagemanager.glade.h:23
msgid "Boot Environment Confirmation"
msgstr "ブート環境の確認"

#: ../gui/data/packagemanager.glade.h:24
msgid "Br_owse"
msgstr "参照(_O)"

#: ../gui/data/packagemanager.glade.h:25
msgid "Browse for SSL Certificate"
msgstr "SSL 証明書を参照"

#: ../gui/data/packagemanager.glade.h:26
msgid "Browse for SSL Key"
msgstr "SSL キーを参照"

#: ../gui/data/packagemanager.glade.h:27 ../um/data/updatemanager.glade.h:4
msgid "Checking for latest SUNWipkg and SUNWipkg-gui, please wait..."
msgstr "最新の SUNWipkg と SUNWipkg-gui をチェックしています。しばらくお待ちください..."

#: ../gui/data/packagemanager.glade.h:28
msgid "Checking package dependencies..."
msgstr "パッケージの依存関係をチェック中..."

#: ../gui/data/packagemanager.glade.h:29
msgid "Clear"
msgstr "クリア"

#: ../gui/data/packagemanager.glade.h:30
msgid "Click to get list of newest packages."
msgstr "最新のパッケージの一覧を取得する場合にクリックします。"

#: ../gui/data/packagemanager.glade.h:31
msgid "Click to update all installed packages."
msgstr "すべてのインストール済みパッケージを更新する場合にクリックします。"

#: ../gui/data/packagemanager.glade.h:32
msgid "Copy"
msgstr "コピー"

#: ../gui/data/packagemanager.glade.h:33
msgid ""
"Copyright 2009 Sun Microsystems, Inc.  \n"
"All rights reserved.\n"
"Use is subject to license terms."
msgstr ""
"Copyright 2009 Sun Microsystems, Inc.  \n"
"All rights reserved.\n"
"使用はライセンス契約条件に従うものとします。"

#: ../gui/data/packagemanager.glade.h:36
msgid "Cu_t"
msgstr "カット(_T)"

#: ../gui/data/packagemanager.glade.h:37
msgid "Currently active boot environment"
msgstr "現在アクティブになっているブート環境"

#: ../gui/data/packagemanager.glade.h:38
msgid "Cut action"
msgstr "アクションのカット"

#: ../gui/data/packagemanager.glade.h:39
msgid "Dependencies"
msgstr "依存関係"

#: ../gui/data/packagemanager.glade.h:40
msgid "Deselect selected packages"
msgstr "選択したパッケージを選択解除します"

#: ../gui/data/packagemanager.glade.h:41
msgid "Details"
msgstr "詳細"

#: ../gui/data/packagemanager.glade.h:42
msgid "Do not notify me about these repositories again."
msgstr "今後、これらのリポジトリについて通知しない。"

#: ../gui/data/packagemanager.glade.h:43 ../gui/modules/installupdate.py:100
#: ../um/data/updatemanager.glade.h:6 ../updatemanager.py:174
#: ../updatemanager.py:397 ../updatemanager.py:404 ../updatemanager.py:411
#: ../updatemanager.py:418 ../updatemanager.py:425
msgid "Download"
msgstr "ダウンロード"

#: ../gui/data/packagemanager.glade.h:44
msgid "Files"
msgstr "ファイル"

#: ../gui/data/packagemanager.glade.h:45 ../gui/modules/installupdate.py:101
#: ../updatemanager.py:190 ../updatemanager.py:398 ../updatemanager.py:405
#: ../updatemanager.py:412 ../updatemanager.py:419 ../updatemanager.py:426
msgid "Install"
msgstr "インストール"

#: ../gui/data/packagemanager.glade.h:46
msgid "Install or Update selected packages"
msgstr "選択したパッケージをインストールまたは更新します"

#: ../gui/data/packagemanager.glade.h:47 ../gui/modules/installupdate.py:237
msgid "Install/Update"
msgstr "インストール/更新"

#: ../gui/data/packagemanager.glade.h:48
msgid "Install/Upgrade Check"
msgstr "インストール/更新のチェック"

#: ../gui/data/packagemanager.glade.h:50
msgid "Legend:"
msgstr "説明文:"

#: ../gui/data/packagemanager.glade.h:51
msgid "License"
msgstr "ライセンス"

#: ../gui/data/packagemanager.glade.h:52
msgid "M_irror:"
msgstr "ミラー(_I):"

#: ../gui/data/packagemanager.glade.h:53
msgid "Manage Boot Environments"
msgstr "ブート環境を管理する"

#: ../gui/data/packagemanager.glade.h:54
msgid "Manage Repositories"
msgstr "リポジトリの管理"

#: ../gui/data/packagemanager.glade.h:55
msgid "Manage _Boot Environments..."
msgstr "ブート環境の管理(_B)..."

#: ../gui/data/packagemanager.glade.h:56
msgid "Modify Repository"
msgstr "リポジトリの変更"

#: ../gui/data/packagemanager.glade.h:57
msgid "Online Help"
msgstr "オンラインヘルプ"

#: ../gui/data/packagemanager.glade.h:58
msgid "Online _Help"
msgstr "オンラインヘルプ(_H)"

#: ../gui/data/packagemanager.glade.h:60
msgid "Package Manager Preferences"
msgstr "パッケージマネージャーの設定"

#: ../gui/data/packagemanager.glade.h:61
msgid "Paste"
msgstr "ペースト"

#: ../gui/data/packagemanager.glade.h:62
msgid "Pre_ferences"
msgstr "設定(_F)"

#: ../gui/data/packagemanager.glade.h:63
msgid "Preferences"
msgstr "設定"

#: ../gui/data/packagemanager.glade.h:64 ../gui/modules/installupdate.py:99
msgid "Preparation"
msgstr "準備"

#: ../gui/data/packagemanager.glade.h:65 ../gui/modules/webinstall.py:198
msgid "Proceed only if you trust this new repository "
msgstr "この新しいリポジトリを信頼する場合のみ続行してください"

#: ../gui/data/packagemanager.glade.h:66 ../um/data/updatemanager.glade.h:9
msgid "Processing"
msgstr "処理中"

#: ../gui/data/packagemanager.glade.h:67
msgid "Quit application"
msgstr "アプリケーションを終了します"

#: ../gui/data/packagemanager.glade.h:68
msgid "Reload"
msgstr "再読み込み"

#: ../gui/data/packagemanager.glade.h:69
msgid "Remote search error"
msgstr "リモート検索エラー"

#: ../gui/data/packagemanager.glade.h:70 ../gui/modules/installupdate.py:202
#: ../gui/modules/installupdate.py:205
msgid "Remove"
msgstr "削除"

#: ../gui/data/packagemanager.glade.h:71
msgid "Remove Confirmation"
msgstr "確認の削除"

#: ../gui/data/packagemanager.glade.h:72
msgid "Remove selected packages"
msgstr "選択したパッケージを削除します"

#: ../gui/data/packagemanager.glade.h:73
msgid "SSL C_ertificate: "
msgstr "SSL 証明書(_E): "

#: ../gui/data/packagemanager.glade.h:74
msgid "SSL Key and Certificate"
msgstr "SSL キーと証明書"

#: ../gui/data/packagemanager.glade.h:75
msgid "SSL _Certificate:"
msgstr "SSL 証明書(_C):"

#: ../gui/data/packagemanager.glade.h:76
msgid "SSL _Key:"
msgstr "SSL キー(_K):"

#: ../gui/data/packagemanager.glade.h:77
msgid "SSL _Key: "
msgstr "SSL キー(_K): "

#: ../gui/data/packagemanager.glade.h:78
msgid "Se_arch:"
msgstr "検索(_A):"

#: ../gui/data/packagemanager.glade.h:79
msgid "Search"
msgstr "検索"

#: ../gui/data/packagemanager.glade.h:80
msgid "Search All Repositories Error"
msgstr "すべてのリポジトリの検索エラー"

#: ../gui/data/packagemanager.glade.h:81
msgid ""
"Search All Repositories cannot be performed on the following\n"
"repositories:"
msgstr ""
"すべてのリポジトリの検索を次のリポジトリに対して\n"
"実行できません:"

#: ../gui/data/packagemanager.glade.h:83
msgid "Select All Items"
msgstr "すべての項目を選択"

#: ../gui/data/packagemanager.glade.h:84
msgid "Select Updates"
msgstr "更新を選択"

#: ../gui/data/packagemanager.glade.h:85
msgid "Select _All"
msgstr "すべて選択(_A)"

#: ../gui/data/packagemanager.glade.h:86
msgid "Select _Updates"
msgstr "更新を選択(_U)"

#: ../gui/data/packagemanager.glade.h:87
msgid "Select from the list to modify or remove existing repositories."
msgstr "既存のリポジトリを変更または削除する場合は、リストから選択してください。"

#: ../gui/data/packagemanager.glade.h:88
msgid "Select packages by marking the checkbox and click to Install/Update."
msgstr "チェックボックスにチェックマークを付けてパッケージを選択し、「インストール/更新」をクリックします。"

#: ../gui/data/packagemanager.glade.h:89
msgid "Select packages by marking the checkbox and click to Remove selected."
msgstr "チェックボックスにチェックマークを付けてパッケージを選択し、「選択したパッケージを削除します」をクリックします。"

#: ../gui/data/packagemanager.glade.h:90
msgid "Sho_w:"
msgstr "表示(_W):"

#: ../gui/data/packagemanager.glade.h:91
msgid "Short description"
msgstr "簡単な説明"

#: ../gui/data/packagemanager.glade.h:92
msgid "Start Page"
msgstr "開始ページ"

#: ../gui/data/packagemanager.glade.h:93
msgid "Start _Page"
msgstr "開始ページ(_P)"

#: ../gui/data/packagemanager.glade.h:94
msgid "The folllowing will be added to your system"
msgstr "次のものがシステムに追加されます"

#: ../gui/data/packagemanager.glade.h:95
msgid "This is a secure repository. Refer to the posted"
msgstr "このリポジトリはセキュリティーで保護されています。公開されている次のものを参照してください: "

#: ../gui/data/packagemanager.glade.h:96
msgid ""
"This repository requires a SSL Key and certificate.\n"
"Enter the location of these files in the spaces provided, or use the "
"Browse \n"
"buttons to provide their location."
msgstr ""
"このリポジトリには SSL キーと証明書が必要です。\n"
"これらのファイルの場所を各フィールドに入力するか、"
"「参照」\n"
"ボタンを使用して指定してください。"

#: ../gui/data/packagemanager.glade.h:99
msgid "Type text to search name and description of the package."
msgstr "パッケージの名前と説明を検索するためのテキストを入力します。"

#: ../gui/data/packagemanager.glade.h:100 ../gui/modules/installupdate.py:221
#: ../packagemanager.py:321 ../packagemanager.py:3475
msgid "Update All"
msgstr "すべて更新"

#: ../gui/data/packagemanager.glade.h:101
msgid "Update all packages"
msgstr "すべてのパッケージを更新します"

#: ../gui/data/packagemanager.glade.h:102 ../packagemanager.py:1277
msgid "Updates"
msgstr "更新"

#: ../gui/data/packagemanager.glade.h:103
msgid "_About"
msgstr "情報(_A)"

#: ../gui/data/packagemanager.glade.h:104
msgid "_Add"
msgstr "追加(_A)"

#: ../gui/data/packagemanager.glade.h:105
msgid "_Browse"
msgstr "参照(_B)"

#: ../gui/data/packagemanager.glade.h:106
msgid "_Clear"
msgstr "クリア(_C)"

#: ../gui/data/packagemanager.glade.h:107
msgid "_Copy"
msgstr "コピー(_C)"

#: ../gui/data/packagemanager.glade.h:108
msgid "_Deselect"
msgstr "選択解除(_D)"

#: ../gui/data/packagemanager.glade.h:109
msgid "_Edit"
msgstr "編集(_E)"

#: ../gui/data/packagemanager.glade.h:110
msgid "_Enable type ahead search (slow on large repositories)"
msgstr "先打ち検索を有効にする (大規模なリポジトリでは低速)(_E)"

#: ../gui/data/packagemanager.glade.h:111
msgid "_File"
msgstr "ファイル(_F)"

#: ../gui/data/packagemanager.glade.h:112
msgid "_Help"
msgstr "ヘルプ(_H)"

#: ../gui/data/packagemanager.glade.h:113
msgid "_Install / Update"
msgstr "インストール/更新(_I)"

#: ../gui/data/packagemanager.glade.h:114
msgid "_Instructions"
msgstr "使用方法(_I)"

#: ../gui/data/packagemanager.glade.h:115
msgid "_Manage Repositories..."
msgstr "リポジトリの管理(_M)..."

#: ../gui/data/packagemanager.glade.h:116
msgid "_Modify..."
msgstr "変更(_M)..."

#: ../gui/data/packagemanager.glade.h:117
msgid "_Name: "
msgstr "名前(_N): "

#: ../gui/data/packagemanager.glade.h:118
msgid "_Package"
msgstr "パッケージ(_P)"

#: ../gui/data/packagemanager.glade.h:119
msgid "_Paste"
msgstr "ペースト(_P)"

#: ../gui/data/packagemanager.glade.h:120
msgid "_Proceed"
msgstr "続行(_P)"

#: ../gui/data/packagemanager.glade.h:121
msgid "_Quit"
msgstr "終了(_Q)"

#: ../gui/data/packagemanager.glade.h:122
msgid "_Remove"
msgstr "削除(_R)"

#: ../gui/data/packagemanager.glade.h:123
msgid "_Show Start Page on startup     "
msgstr "起動時に開始ページを表示(_S)..."

#: ../gui/data/packagemanager.glade.h:124
msgid "_URL: "
msgstr "URL(_U): "

#: ../gui/data/packagemanager.glade.h:125 ../um/data/updatemanager.glade.h:17
msgid "_Update All"
msgstr "すべて更新(_U)"

#: ../gui/data/packagemanager.glade.h:126
msgid "gtk-cancel"
msgstr "gtk-cancel"

#: ../gui/data/packagemanager.glade.h:127
msgid "gtk-close"
msgstr "gtk-close"

#: ../gui/data/packagemanager.glade.h:128
msgid "gtk-help"
msgstr "gtk-help"

#: ../gui/data/packagemanager.glade.h:129
msgid "gtk-ok"
msgstr "gtk-ok"

#: ../gui/data/packagemanager.glade.h:130
msgid ""
"lf the repository requires a SSL key and certificate, or if it has mirrors, "
"add the new\n"
"repository, and then click Modify to add additional information."
msgstr ""
"リポジトリに SSL キーと証明書が必要な場合や、リポジトリにミラーが存在する場合は、"
"新しい\n"
"リポジトリを追加してから、「変更」をクリックして詳細を追加してください。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:1
msgid ""
"A boolean which determines if the Start Page should be shown on startup or "
"the initial list view."
msgstr ""
"起動時に「開始ページ」と初期リスト表示のどちらを表示するかを決定する"
"ブール値。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:2
msgid ""
"A boolean which determines if the search is executed dynamically as user "
"types or only when user hits the return key."
msgstr ""
"ユーザーが入力するにつれて動的に検索を実行するか、ユーザーが"
"Return キーを押したときだけ検索を実行するかを決定するブール値。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:3
msgid ""
"A string which determines if the remote search repository is shown or not in "
"the error dialog."
msgstr ""
"エラーダイアログにリモート検索リポジトリを表示するかどうかを決定する"
"ブール値。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:4
msgid ""
"An integer which identifies the initial show filter value to be displayed "
"when packagemanager starts. 0 corresponds to All Packages."
msgstr ""
"パッケージマネージャーの起動時に表示される表示フィルタの初期値を示す整数。"
"0 は「すべてのパッケージ」に対応します。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:5
msgid ""
"An integer which identifies the initial toplevel value to be displayed when "
"packagemanager starts. 0 corresponds to All Categories."
msgstr ""
"パッケージマネージャーの起動時に表示されるトップレベルの初期値を示す整数。"
"0 は「すべてのカテゴリ」に対応します。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:6
msgid ""
"Comma separated list of repositories which we do show if they doesn't "
"support remote search"
msgstr ""
"リポジトリでリモート検索がサポートされていない場合に表示する"
"コンマ区切りのリポジトリリスト。"

#: ../gui/data/packagemanager-preferences.schemas.in.h:7
msgid "Enable type ahead search"
msgstr "先打ち検索を有効にする"

#: ../gui/data/packagemanager-preferences.schemas.in.h:8
msgid "Initial section value"
msgstr "セクションの初期値"

#: ../gui/data/packagemanager-preferences.schemas.in.h:9
msgid "Initial show filter value"
msgstr "表示フィルタの初期値"

#: ../gui/data/packagemanager-preferences.schemas.in.h:10
msgid "Show Start Page on startup"
msgstr "起動時に「開始ページ」を表示"

#: ../gui/data/packagemanager-preferences.schemas.in.h:11
msgid "Start Page Update URL"
msgstr "「開始ページ」の更新 URL"

#: ../gui/data/packagemanager-preferences.schemas.in.h:12
msgid ""
"The location from which to fetch updates to the Package Manager Start Page."
msgstr ""
"パッケージマネージャーの「開始ページ」の更新を取得する場所。"

#: ../gui/modules/webinstall.py:109
#, python-format
msgid "GUI will not respond to any event! %s. Check webinstall.py signals"
msgstr "GUI はどのイベントにも応答しません。%s。webinstall.py のシグナルをチェックしてください"

#: ../gui/modules/webinstall.py:122
msgid ""
"\n"
" Add New Repository\n"
msgstr ""
"\n"
" 新規リポジトリを追加\n"

#: ../gui/modules/webinstall.py:125
msgid ""
"\n"
" Add New Repositories\n"
msgstr ""
"\n"
" 新規リポジトリを追加\n"

#: ../gui/modules/webinstall.py:130
msgid ""
"\n"
" All specified repositories and packages are already on the system.\n"
msgstr ""
"\n"
" 指定されたすべてのリポジトリとパッケージはすでにシステムに存在します。\n"

#: ../gui/modules/webinstall.py:139
#, python-format
msgid "\t%s "
msgstr "\t%s"

#: ../gui/modules/webinstall.py:143 ../packagemanager.py:686
#, python-format
msgid " (%s)\n"
msgstr " (%s)\n"

#: ../gui/modules/webinstall.py:148
msgid ""
"\n"
" Install Packages\n"
msgstr ""
"\n"
" パッケージをインストール\n"

#: ../gui/modules/webinstall.py:156
#, python-format
msgid "\t%s: "
msgstr "\t%s: "

#: ../gui/modules/webinstall.py:159 ../gui/modules/installupdate.py:807
#: ../gui/modules/installupdate.py:857 ../updatemanager.py:992
#, python-format
msgid "%s\n"
msgstr "%s\n"

#: ../gui/modules/webinstall.py:201
msgid "Proceed only if you trust these new repositories"
msgstr "これらの新しいリポジトリを信頼する場合のみ続行してください"

#: ../gui/modules/webinstall.py:247 ../gui/modules/webinstall.py:374
#: ../gui/modules/webinstall.py:383
msgid "Repository Error"
msgstr "リポジトリエラー"

#: ../gui/modules/webinstall.py:335
msgid "API Error"
msgstr "API エラー"

#: ../gui/modules/webinstall.py:352
msgid "Error"
msgstr "エラー"

#: ../gui/modules/webinstall.py:380
msgid "Error reading the p5i file."
msgstr "p5i ファイルの読み取り中にエラーが発生しました。"

#: ../gui/modules/beadmin.py:73
msgid ""
"The <b>libbe</b> library was not found on your system.\n"
"All functions for managing Boot Environments are disabled"
msgstr ""
"<b>libbe</b> ライブラリがシステム上に見つかりませんでした。\n"
"ブート環境を管理するためのすべての機能が無効になっています"

#: ../gui/modules/beadmin.py:81
msgid "BE management"
msgstr "BE 管理"

#: ../gui/modules/beadmin.py:154
#, python-format
msgid "GUI will not respond to any event! %s. Check beadmin.py signals"
msgstr "GUI はどのイベントにも応答しません。%s。beadmin.py のシグナルをチェックしてください"

#: ../gui/modules/beadmin.py:164
msgid "Loading Boot Environment Information"
msgstr "ブート環境情報の読み込み"

#: ../gui/modules/beadmin.py:166
msgid "Fetching BE entries..."
msgstr "BE エントリを取得しています..."

#: ../gui/modules/beadmin.py:193
msgid "Boot Environment"
msgstr "ブート環境"

#: ../gui/modules/beadmin.py:204
msgid "Created"
msgstr "作成済み"

#: ../gui/modules/beadmin.py:213
msgid "Size"
msgstr "サイズ"

#: ../gui/modules/beadmin.py:221
msgid "Active on Reboot"
msgstr "リブート時にアクティブ化"

#: ../gui/modules/beadmin.py:232
msgid "Delete"
msgstr "削除"

#: ../gui/modules/beadmin.py:247 ../gui/modules/repository.py:470
#: ../gui/modules/repository.py:539 ../gui/modules/repository.py:727
#: ../gui/modules/repository.py:746 ../gui/modules/repository.py:867
msgid "Applying changes"
msgstr "変更を適用する"

#: ../gui/modules/beadmin.py:249 ../gui/modules/repository.py:471
#: ../gui/modules/repository.py:540 ../gui/modules/repository.py:728
#: ../gui/modules/repository.py:747 ../gui/modules/repository.py:868
msgid "Applying changes, please wait ..."
msgstr "変更を適用しています。しばらくお待ちください..."

#: ../gui/modules/beadmin.py:278
msgid "Active on reboot:\n"
msgstr "リブート時にアクティブ化:\n"

#: ../gui/modules/beadmin.py:279
msgid "Delete boot environments:\n"
msgstr "ブート環境を削除:\n"

#: ../gui/modules/beadmin.py:280
msgid "Rename boot environments:\n"
msgstr "ブート環境の名前を変更:\n"

#: ../gui/modules/beadmin.py:319
msgid " to "
msgstr "変更後"

#: ../gui/modules/beadmin.py:373
msgid "<b>Couldn't change Active Boot Environment to:</b>\n"
msgstr "<b>アクティブブート環境を次のものに変更できませんでした:</b>\n"

#: ../gui/modules/beadmin.py:378
msgid "<b>Couldn't delete Boot Environments:</b>\n"
msgstr "<b>ブート環境を削除できませんでした:</b>\n"

#: ../gui/modules/beadmin.py:385
msgid "<b>Couldn't rename Boot Environments:</b>\n"
msgstr "<b>ブート環境の名前を変更できませんでした:</b>\n"

#: ../gui/modules/beadmin.py:388
#, python-format
msgid "%s <b>to</b> %s\n"
msgstr "%s <b>変更後</b> %s\n"

#: ../gui/modules/beadmin.py:407
msgid "BE error"
msgstr "BE エラー"

#: ../gui/modules/beadmin.py:492
msgid ""
"The <b>libbe</b> library couldn't  prepare list of Boot Environments.\n"
"All functions for managing Boot Environments are disabled"
msgstr ""
"<b>libbe</b> ライブラリはブート環境の一覧を準備できませんでした。\n"
"ブート環境を管理するためのすべての機能が無効になっています"

#: ../gui/modules/beadmin.py:522 ../gui/modules/beadmin.py:541
msgid "%m/%d/%y %H:%M"
msgstr "%Y 年 %m 月 %d 日 %H:%M"

#: ../gui/modules/beadmin.py:527 ../gui/modules/beadmin.py:546
#, python-format
msgid "Error conversion from UTF-8 to %s."
msgstr "UTF-8 から %s への変換でエラーが発生しました。"

#: ../gui/modules/beadmin.py:563
#, python-format
msgid "Error conversion from %s to UTF-8."
msgstr "%s から UTF-8 への変換でエラーが発生しました。"

#: ../gui/modules/installupdate.py:99
msgid "Preparing..."
msgstr "準備中..."

#: ../gui/modules/installupdate.py:100 ../gui/modules/installupdate.py:495
msgid "Downloading..."
msgstr "ダウンロード中..."

#: ../gui/modules/installupdate.py:101
msgid "Installing..."
msgstr "インストール中..."

#: ../gui/modules/installupdate.py:190
#, python-format
msgid "GUI will not respond to any event! %s. Check installupdate.py signals"
msgstr "GUI はどのイベントにも応答しません。%s。installupdate.py のシグナルをチェックしてください"

#. We are not showing the download stage in the main stage list
#: ../gui/modules/installupdate.py:202
msgid "Removing..."
msgstr "削除しています..."

#: ../gui/modules/installupdate.py:251
msgid "Canceling..."
msgstr "キャンセル中..."

#: ../gui/modules/installupdate.py:319
msgid "BE name is in use"
msgstr "BE 名は使用中です"

#: ../gui/modules/installupdate.py:321
msgid "BE name is invalid"
msgstr "BE 名が無効です"

#: ../gui/modules/installupdate.py:355
#, python-format
msgid "Ensuring %s is up to date..."
msgstr "%s が最新であることを確認しています..."

#: ../gui/modules/installupdate.py:376
msgid ""
"Accessing this restricted repository failed.\n"
"You either need to register to access this repository,\n"
"the certificate expired, or you need to accept the repository\n"
"certificate."
msgstr ""
"制限されたこのリポジトリへのアクセスに失敗しました。\n"
"証明書の期限が切れている場合は、登録して\n"
"このリポジトリへアクセスするか、またはリポジトリの証明書に\n"
"同意する必要があります。"

#: ../gui/modules/installupdate.py:386
msgid "Inventory exception:\n"
msgstr "目録の例外:\n"

#: ../gui/modules/installupdate.py:393
msgid ""
"Please check the network connection.\n"
"Is the repository accessible?"
msgstr ""
"ネットワーク接続を確認してください。\n"
"リポジトリにアクセスできますか?"

#: ../gui/modules/installupdate.py:403
#, python-format
msgid ""
"Please check the network connection.\n"
"Is the repository accessible?\n"
"\n"
"%s"
msgstr ""
"ネットワーク接続を確認してください。\n"
"リポジトリにアクセスできますか?\n"
"\n"
"%s"

#: ../gui/modules/installupdate.py:409
msgid ""
"pkg(5) appears to be out of date and should be\n"
"updated before running Update All.\n"
"Please update SUNWipkg package"
msgstr ""
"pkg(5) は古いようなので、「すべて更新」を\n"
"実行する前に更新すべきです。\n"
"SUNWipkg パッケージを更新してください"

#: ../gui/modules/installupdate.py:415
#, python-format
msgid ""
"Cannot remove:\n"
"\t%s\n"
"Due to the following packages that depend on it:\n"
msgstr ""
"削除できません:\n"
"\t%s\n"
"次のパッケージがこれに依存しているためです:\n"

#: ../gui/modules/installupdate.py:424
#, python-format
msgid ""
"\n"
"Failure of consistent use of pfexec or gksu when running\n"
"%s is often a source of this problem."
msgstr ""
"\n"
"多くの場合、%s の実行時に pfexec または gksu の使用方法を誤ったことが\n"
"この問題の原因です。"

#: ../gui/modules/installupdate.py:427
msgid ""
"\n"
"To rebuild index, please use the terminal command:"
msgstr ""
"\n"
"インデックスを再構築するには、次の端末コマンドを使用してください:"

#: ../gui/modules/installupdate.py:428
msgid ""
"\n"
"\tpfexec pkg rebuild-index"
msgstr ""
"\n"
"\tpfexec pkg rebuild-index"

#: ../gui/modules/installupdate.py:432
msgid ""
"There was an error during installation. The search\n"
"index is corrupted. You might want try to fix this\n"
"problem by running command:\n"
"\tpfexec pkg rebuild-index"
msgstr ""
"インストール中にエラーが発生しました。\n"
"検索ンデックスが壊れています。次のコマンドを実行することによって、\n"
"この問題の解決を試みることをお勧めします:\n"
"\tpfexec pkg rebuild-index"

#: ../gui/modules/installupdate.py:439
msgid ""
"This is an Live Image. The install\n"
"operation can't be performed."
msgstr ""
"これはライブイメージです。インストール\n"
"操作を実行できません。"

#: ../gui/modules/installupdate.py:444
#, python-format
msgid ""
"There was an error during installation.\n"
"The Plan of the operation is missing and the operation\n"
"can't be finished. You might want try to fix this\n"
"problem by restarting %s\n"
msgstr ""
"インストール中にエラーが発生しました。\n"
"操作の計画がないため\n"
"操作を完了できません。%s を再起動することによって、\n"
"この問題の解決を試みることをお勧めします\n"

#: ../gui/modules/installupdate.py:451
#, python-format
msgid ""
"There was an error during installation.\n"
"The State of the image is incorrect and the operation\n"
"can't be finished. You might want try to fix this\n"
"problem by restarting %s\n"
msgstr ""
"インストール中にエラーが発生しました。\n"
"イメージの状態が正しくないため\n"
"操作を完了できません。%s を再起動することによって、\n"
"この問題の解決を試みることをお勧めします\n"

#: ../gui/modules/installupdate.py:462
msgid "Specifying BE Name not supported.\n"
msgstr "BE 名を指定することはできません。\n"

#: ../gui/modules/installupdate.py:466
#, python-format
msgid "Invalid BE Name: %s.\n"
msgstr "無効な BE 名: %s。\n"

#: ../gui/modules/installupdate.py:491
#, python-format
msgid "Updating %s"
msgstr "%s を更新しています"

#: ../gui/modules/installupdate.py:497
msgid "Executing..."
msgstr "実行しています..."

#: ../gui/modules/installupdate.py:504
msgid "Gathering packages information, please wait..."
msgstr "パッケージ情報を収集しています。しばらくお待ちください..."

#: ../gui/modules/installupdate.py:526
msgid "All packages already installed."
msgstr "すべてのパッケージがすでにインストールされています。"

#: ../gui/modules/installupdate.py:531
msgid ""
"Selected package(s) cannot be updated on their own.\n"
"Click Update All to update all packages."
msgstr ""
"選択したパッケージは単独では更新できません。\n"
"「すべて更新」をクリックしてすべてのパッケージを更新してください。"

#: ../gui/modules/installupdate.py:534
msgid "Your system have been already updated."
msgstr "システムはすでに更新されています。"

#: ../gui/modules/installupdate.py:572 ../gui/modules/installupdate.py:607
msgid "No futher information available"
msgstr "利用できる詳細情報はありません"

#: ../gui/modules/installupdate.py:575 ../gui/modules/installupdate.py:598
msgid ""
"\n"
"Error:\n"
msgstr ""
"\n"
"エラー:\n"

#: ../gui/modules/installupdate.py:578 ../gui/modules/installupdate.py:588
msgid " - Failed </b>"
msgstr " - 失敗しました </b>"

#: ../gui/modules/installupdate.py:592
#, python-format
msgid ""
"An unknown error occured in the %s stage.\n"
"Please let the developers know about this problem\n"
"by filing a bug together with exception value at:\n"
msgstr ""
"%s 段階で不明なエラーが発生しました。\n"
"この問題を開発者に知らせるために、\n"
"バグ情報と例外の値を次のサイトで入力してください:\n"

#: ../gui/modules/installupdate.py:596
msgid ""
"http://defect.opensolaris.org\n"
"\n"
msgstr ""
"http://defect.opensolaris.org\n"
"\n"

#: ../gui/modules/installupdate.py:597
msgid "Exception value:\n"
msgstr "例外の値:\n"

#: ../gui/modules/installupdate.py:602
msgid "Exception traceback:\n"
msgstr "例外のトレースバック:\n"

#: ../gui/modules/installupdate.py:659
#, python-format
msgid "Downloaded %(current)s of %(total)s"
msgstr "%(current)s/%(total)s がダウンロードされました"

#: ../gui/modules/installupdate.py:679
msgid "Catalog refresh failed during install."
msgstr "インストール中にカタログの更新に失敗しました。"

#: ../gui/modules/installupdate.py:694
msgid "Catalog refresh failed during Update All."
msgstr "「すべて更新」の処理中にカタログの更新に失敗しました。"

#: ../gui/modules/installupdate.py:698
msgid "Installation completed successfully."
msgstr "インストールが正常に完了しました。"

#: ../gui/modules/installupdate.py:700
msgid "Packages removed successfully."
msgstr "パッケージが正常に削除されました。"

#: ../gui/modules/installupdate.py:702
msgid "Packages updated successfully."
msgstr "パッケージが正常に更新されました。"

#: ../gui/modules/installupdate.py:733
msgid "Not enough disk space, the selected action cannot "
msgstr "Not enough disk space, the selected action cannot "

#: ../gui/modules/installupdate.py:737
msgid "Not Enough Disk Space"
msgstr "ディスク容量の不足"

#: ../gui/modules/installupdate.py:755
msgid "Packages To Be Updated:\n"
msgstr "更新するパッケージ:\n"

#: ../gui/modules/installupdate.py:762
msgid "Packages To Be Installed:\n"
msgstr "インストールするパッケージ:\n"

#: ../gui/modules/installupdate.py:769
msgid "Packages To Be Removed:\n"
msgstr "削除するパッケージ:\n"

#: ../gui/modules/installupdate.py:827
#, python-format
msgid "Package %d of %d: %s\n"
msgstr "パッケージ %d/%d: %s\n"

#: ../gui/modules/installupdate.py:846
#, python-format
msgid "Evaluating: %s"
msgstr "評価中: %s"

#: ../gui/modules/repository.py:266
#, python-format
msgid "GUI will not respond to any event! %s. Check repository.py signals"
msgstr "GUI はどのイベントにも応答しません。%s。repository.py のシグナルをチェックしてください"

#: ../gui/modules/repository.py:309
msgid "Add New Repository"
msgstr "新規リポジトリを追加"

#: ../gui/modules/repository.py:317
msgid "<b>New Repository</b>"
msgstr "<b>新規リポジトリ</b>"

#: ../gui/modules/repository.py:363
msgid "Repository Name"
msgstr "リポジトリ名"

#: ../gui/modules/repository.py:372
msgid "Preferred"
msgstr "優先"

#: ../gui/modules/repository.py:384
msgid "Enabled"
msgstr "Enabled"

#: ../gui/modules/repository.py:505
#, python-format
msgid "Failed to disable %s.\n"
msgstr "%s を無効にできませんでした。\n"

#: ../gui/modules/repository.py:507
#, python-format
msgid "Failed to enable %s.\n"
msgstr "%s を有効にできませんでした。\n"

#: ../gui/modules/repository.py:513 ../gui/modules/repository.py:521
#: ../gui/modules/repository.py:531
#, python-format
msgid "Failed to disable %s."
msgstr "%s を無効にできませんでした。"

#: ../gui/modules/repository.py:515 ../gui/modules/repository.py:523
#: ../gui/modules/repository.py:533
#, python-format
msgid "Failed to enable %s."
msgstr "%s を有効にできませんでした。"

#: ../gui/modules/repository.py:516 ../gui/modules/repository.py:985
#: ../gui/modules/repository.py:1013
msgid ""
"\n"
"Please check your permissions."
msgstr ""
"\n"
"アクセス権を確認してください。"

#: ../gui/modules/repository.py:525 ../gui/modules/repository.py:995
msgid ""
"\n"
"Please check the network connection or URL.\n"
"Is the repository accessible?"
msgstr ""
"\n"
"ネットワーク接続または URL を確認してください。\n"
"リポジトリにアクセスできますか?"

#: ../gui/modules/repository.py:534
msgid ""
"\n"
"Unexpected error.\n"
msgstr ""
"\n"
"予期しないエラー。\n"

#: ../gui/modules/repository.py:577
msgid ""
"Couldn't change the preferred publisher.\n"
"Please check your permissions."
msgstr ""
"優先された発行元を変更できませんでした。\n"
"アクセス権を確認してください。"

#: ../gui/modules/repository.py:641
msgid "Name contains invalid characters"
msgstr "名前に無効な文字が含まれています"

#: ../gui/modules/repository.py:648
msgid "Name already in use"
msgstr "名前はすでに使用されています"

#: ../gui/modules/repository.py:669
msgid "URL is not valid"
msgstr "URL が無効です"

#: ../gui/modules/repository.py:855
#, python-format
msgid ""
"Unable to navigate to:\n"
"\t%s"
msgstr ""
"移動できません:\n"
"\t%s"

#: ../gui/modules/repository.py:856
msgid "Registration"
msgstr "登録"

#: ../gui/modules/repository.py:863
msgid "Adding New Repository"
msgstr "新規リポジトリを追加しています"

#: ../gui/modules/repository.py:864
#, python-format
msgid ""
"Adding:\n"
"\t%s (%s)..."
msgstr ""
"追加しています:\n"
"\t%s (%s)..."

#: ../gui/modules/repository.py:969
#, python-format
msgid ""
"Failed to add repository: %s\n"
"\n"
msgstr ""
"リポジトリの追加に失敗しました %s\n"
"\n"

#: ../gui/modules/repository.py:976
#, python-format
msgid "Failed to add %s.\n"
msgstr "%s の追加に失敗しました。\n"

#: ../gui/modules/repository.py:984 ../gui/modules/repository.py:993
#, python-format
msgid "Failed to add %s."
msgstr "%s の追加に失敗しました。"

#: ../gui/modules/repository.py:1012
#, python-format
msgid "Failed to delete %s."
msgstr "%s の削除に失敗しました。"

#: ../gui/modules/repository.py:1120 ../gui/modules/repository.py:1155
msgid "Specify SSL Key File"
msgstr "SSL キーのファイルを指定してください"

#: ../gui/modules/repository.py:1140 ../gui/modules/repository.py:1175
msgid "Specify SSL Certificate File"
msgstr "SSL 証明書のファイルを指定してください"

#. More Generic for WebInstall
#: ../gui/modules/repository.py:1212
msgid "Repository error"
msgstr "リポジトリエラー"

#: ../modules/actions/__init__.py:89
#, python-format
msgid ""
"unknown action type '%(type)s' in package '%(fmri)s' in action '%(action)s'"
msgstr ""
"アクション '%(action)s' のパッケージ '%(fmri)s のアクションタイプ '%(type)s' は不明です"

#: ../modules/actions/__init__.py:93
#, python-format
msgid "unknown action type '%(type)s' in action '%(action)s'"
msgstr "アクション '%(action)s' のアクションタイプ '%(type)s' は不明です"

#: ../modules/actions/__init__.py:106
#, python-format
msgid ""
"Malformed action in package '%(fmri)s' at position: %(pos)d:\n"
"    %(action)s\n"
"%(marker)s"
msgstr ""
"パッケージ'%(fmri)s' の次の位置にあるアクションの形式が不正です: %(pos)d:\n"
"    %(action)s\n"
"%(marker)s"

#: ../modules/actions/__init__.py:111
#, python-format
msgid ""
"Malformed action at position: %(pos)d:\n"
"    %(action)s\n"
"%(marker)s"
msgstr ""
"次の位置にあるアクションの形式が不正です: %(pos)d:\n"
"    %(action)s\n"
"%(marker)s"

#: ../modules/actions/__init__.py:137
#, python-format
msgid "invalid action in package %(fmri)s: %(action)s: %(error)s"
msgstr "パッケージ %(fmri)s のアクションが無効です: %(action)s: %(error)s"

#: ../modules/actions/__init__.py:140
#, python-format
msgid "invalid action, '%(action)s': %(error)s"
msgstr "無効なアクションです。'%(action)s': %(error)s"

#: ../modules/actions/__init__.py:164
#, python-format
msgid "required attribute '%s' was not provided."
msgstr "必須の属性 '%s' が指定されませんでした。"

#: ../modules/actions/__init__.py:221
#, python-format
msgid "required attribute, '%s', was not provided."
msgstr "必須の属性 '%s' が指定されませんでした。"

#: ../modules/client/api_errors.py:102
#, python-format
msgid ""
"Could not operate on %s\n"
"because of insufficient permissions. Please try the command again using "
"pfexec\n"
"or otherwise increase your privileges."
msgstr ""
"アクセス権が十分でないため %s を\n"
"操作できませんでした。"
"pfexec\n"
"を使用してコマンドを再試行するか、アクセス権を取得してください。"

#: ../modules/client/api_errors.py:107
msgid ""
"\n"
"Could not complete the operation because of insufficient permissions. "
"Please\n"
"try the command again using pfexec or otherwise increase your privileges.\n"
msgstr ""
"\n"
"アクセス権が十分でないため操作を完了できませんでした。"
"pfexec を使用してコマンドを再試行するか、\n"
"アクセス権を取得してください。\n"

#: ../modules/client/api_errors.py:118
#, python-format
msgid ""
"Could not operate on %s\n"
"because the file is in use. Please stop using the file and try the\n"
"operation again."
msgstr ""
"ファイルが使用中のため %s を\n"
"操作できませんでした。ファイルの使用を中止し、\n"
"操作を再試行してください。"

#: ../modules/client/api_errors.py:137
msgid ""
"pkg: The following pattern(s) did not match any packages in the current\n"
"catalog. Try relaxing the pattern, refreshing and/or examining the catalogs"
msgstr ""
"pkg: 次のパターンは、現在のカタログ内のどのパッケージにも一致しませんでした。\n"
"パターンの条件緩和、再表示、カタログの検査のいずれか、あるいはそのすべてを試してください"

#: ../modules/client/api_errors.py:150
#, python-format
msgid "pkg: '%s' matches no installed packages"
msgstr "pkg: '%s' はどのインストール済みパッケージにも一致しません"

#: ../modules/client/api_errors.py:153
#, python-format
msgid "pkg: '%s' is an illegal fmri"
msgstr "pkg: '%s' は不正な FMRI です"

#: ../modules/client/api_errors.py:157
msgid "pkg: the following package(s) violated constraints:"
msgstr "pkg: 次のパッケージが制約に違反しました:"

#: ../modules/client/api_errors.py:163
#, python-format
msgid "'%s' supports the following architectures: %s"
msgstr "'%s' は次のアーキテクチャーをサポートしています: %s"

#: ../modules/client/api_errors.py:164
#, python-format
msgid "Image architecture is defined as: %s"
msgstr "イメージのアーキテクチャーは次のように定義されています: %s"

#: ../modules/client/api_errors.py:193
msgid ""
"No matching package could be found for the following FMRIs in any of the "
"catalogs for the current publishers:\n"
msgstr ""
"次の FMRI に一致するパッケージが、現在の発行元のどのカタログにも見つかり"
"ませんでした:\n"

#: ../modules/client/api_errors.py:282
#, python-format
msgid ""
"The specified file is in an unrecognized format or does not contain valid "
"publisher information: %s"
msgstr ""
"指定されたファイルは、認識できない形式であるか、有効な発行元情報を"
"含んでいません: %s"

#: ../modules/client/api_errors.py:285
msgid ""
"The specified file is in an unrecognized format or does not contain valid "
"publisher information."
msgstr ""
"指定されたファイルは、認識できない形式であるか、有効な発行元情報を"
"含んでいません。"

#: ../modules/client/api_errors.py:294
msgid "Unsupported pkg(5) publisher information data format."
msgstr "pkg(5) 発行元情報としてサポートされていないデータ形式です。"

#: ../modules/client/api_errors.py:320
#, python-format
msgid ""
"Error encountered while retrieving data from '%s':\n"
"%s"
msgstr ""
"'%s' からデータ取得中にエラーが発生しました:\n"
"%s"

#: ../modules/client/api_errors.py:322
#, python-format
msgid "Error encountered while retrieving data from: %s"
msgstr "データの取得中にエラーが発生しました: %s"

#: ../modules/client/api_errors.py:330
#, python-format
msgid "'%s' is not a valid location."
msgstr "'%s' は有効な場所ではありません。"

#: ../modules/client/api_errors.py:342
#, python-format
msgid "'%s' is not a valid boot envirnment name."
msgstr "'%s' は有効なブート環境名ではありません。"

#: ../modules/client/api_errors.py:351
msgid ""
"Boot environment naming during package install is not supported on this\n"
"version of OpenSolaris. Please image-update without the --be-name option."
msgstr ""
"このバージョンの OpenSolaris では、パッケージのインストール中にブート環境の\n"
"名前を指定することはできません。--be-name オプションを指定せずに image-update を実行してください。"

#: ../modules/client/api_errors.py:357
msgid "Unable to clone the current boot environment."
msgstr "現在のブート環境を複製できません。"

#: ../modules/client/api_errors.py:370
#, python-format
msgid ""
"A problem occurred while attempting to rename the boot environment\n"
"currently named %(orig)s to %(dest)s."
msgstr ""
"ブート環境の名前を現在の %(orig)s から %(dest)s に\n"
"変更しようとしたときに問題が発生しました。"

#: ../modules/client/api_errors.py:381
#, python-format
msgid "Unable to mount %(name)s at %(mt)s"
msgstr "%(name)s を %(mt)s にマウントできません"

#: ../modules/client/api_errors.py:390
msgid ""
"Naming a boot environment when operating on a non-live image is\n"
"not allowed."
msgstr ""
"ライブ以外のイメージの操作中にブート環境の名前を指定することは\n"
"許可されていません"

#: ../modules/client/api_errors.py:401
msgid "Info does not recognize the following options:"
msgstr "Info では次のオプションは認識されません:"

#: ../modules/client/api_errors.py:403
msgid " '"
msgstr " '"

#: ../modules/client/api_errors.py:403
msgid "'"
msgstr "'"

#: ../modules/client/api_errors.py:413
msgid "Some servers failed to respond appropriately:\n"
msgstr "一部のサーバーが適切に応答できませんでした:\n"

#: ../modules/client/api_errors.py:416
#, python-format
msgid "    %(o)s: %(msg)s (%(code)d)\n"
msgstr "    %(o)s: %(msg)s (%(code)d)\n"

#: ../modules/client/api_errors.py:421
#, python-format
msgid "    %(o)s: %(to)s\n"
msgstr "    %(o)s: %(to)s\n"

#: ../modules/client/api_errors.py:425
#, python-format
msgid "    %(o)s: %(other)s\n"
msgstr "    %(o)s: %(other)s\n"

#: ../modules/client/api_errors.py:429
#, python-format
msgid "    %(o)s: %(msg)s\n"
msgstr "    %(o)s: %(msg)s\n"

#: ../modules/client/api_errors.py:434
#, python-format
msgid "%s appears not to be a valid package depot.\n"
msgstr "%s は有効なパッケージデポではないようです。\n"

#: ../modules/client/api_errors.py:457
msgid ""
"Search capabilities and performance are degraded.\n"
"To improve, run 'pkg rebuild-index'."
msgstr ""
"検索機能とパフォーマンスが低下しています。\n"
"改善するには、'pkg rebuild-index' を実行してください。"

#: ../modules/client/api_errors.py:468
msgid "This expression produces action results:\n"
msgstr "この式で生成される結果はアクションです:\n"

#: ../modules/client/api_errors.py:470
msgid "This expression produces package results:\n"
msgstr "この式で生成される結果はパッケージです:\n"

#: ../modules/client/api_errors.py:472
#, python-format
msgid ""
"%(ac_s)s%(ac_q)s%(pc_s)s%(pc_q)s'AND' and 'OR' require those expressions to "
"produce the same type of results."
msgstr ""
"%(ac_s)s%(ac_q)s%(pc_s)s%(pc_q)s'AND' と 'OR' では、これらの式から"
"同じタイプの結果が生成される必要があります。"

#: ../modules/client/api_errors.py:498
#, python-format
msgid "'%s' is not a valid publisher name."
msgstr "'%s' は有効な発行元名ではありません。"

#: ../modules/client/api_errors.py:506
#, python-format
msgid ""
"'%(value)s' is not a valid value for repository attribute '%(attribute)s'."
msgstr ""
"'%(value)s' はリポジトリ属性 '%(attribute)s' に有効な値ではありません。"

#: ../modules/client/api_errors.py:519
#, python-format
msgid "'%s' is not a valid repository collection type."
msgstr "'%s' は有効なリポジトリ収集タイプではありません。"

#: ../modules/client/api_errors.py:527
#, python-format
msgid "'%s' is not a valid URI."
msgstr "'%s' は有効な URI ではありません。"

#: ../modules/client/api_errors.py:535
#, python-format
msgid "'%s' is not a valid URI priority; integer value expected."
msgstr "'%s' は有効な URI 優先順位ではありません。整数値が必要です。"

#: ../modules/client/api_errors.py:547
#, python-format
msgid "'%s' is not a valid repository URI sort policy."
msgstr "'%s' は有効なリポジトリ URI ソートポリシーではありません。"

#: ../modules/client/api_errors.py:556
#, python-format
msgid "Publisher '%s' is disabled and cannot be used for packaging operations."
msgstr "発行元 '%s' は無効になっているため、パッケージ化の操作に使用することはできません。"

#: ../modules/client/api_errors.py:565
#, python-format
msgid "A publisher with the same name or alias as '%s' already exists."
msgstr "'%s' と同じ名前または同じ別名の発行元がすでに存在します。"

#: ../modules/client/api_errors.py:574
#, python-format
msgid ""
"A repository with the same name or origin URIs already exists for publisher "
"'%s'."
msgstr ""
"発行元 '%s' には、同じ名前または同じ起点 URI のリポジトリが"
"すでに存在します。"

#: ../modules/client/api_errors.py:583
#, python-format
msgid "Mirror '%s' already exists for the specified repository."
msgstr "指定されたリポジトリには、ミラー '%s' がすでに存在します。"

#: ../modules/client/api_errors.py:592
#, python-format
msgid "Origin '%s' already exists for the specified repository."
msgstr "指定されたリポジトリには、起点 '%s' がすでに存在します。"

#: ../modules/client/api_errors.py:601
msgid "The preferred publisher cannot be removed."
msgstr "優先された発行元を削除することはできません。"

#: ../modules/client/api_errors.py:609
msgid "Cannot remove the selected repository for a publisher."
msgstr "発行元の選択されたリポジトリを削除できません。"

#: ../modules/client/api_errors.py:618
#, python-format
msgid ""
"Publisher '%(pub)s' is disabled and cannot be set as the preferred publisher."
msgstr ""
"発行元 '%(pub)s' は無効になっているため、優先された発行元として設定することはできません。"

#: ../modules/client/api_errors.py:627
#, python-format
msgid "Unknown legal URI '%s'."
msgstr "正当な URI '%s' は不明です。"

#: ../modules/client/api_errors.py:635
#, python-format
msgid "Unknown publisher '%s'."
msgstr "発行元 '%s' は不明です。"

#: ../modules/client/api_errors.py:643
#, python-format
msgid "Unknown related URI '%s'."
msgstr "関連 URI '%s' は不明です。"

#: ../modules/client/api_errors.py:651
#, python-format
msgid "Unknown repository '%s'."
msgstr "リポジトリ '%s' は不明です。"

#: ../modules/client/api_errors.py:659
#, python-format
msgid "Unknown repository mirror '%s'."
msgstr "リポジトリのミラー '%s' は不明です。"

#: ../modules/client/api_errors.py:667
#, python-format
msgid "Unknown repository origin '%s'"
msgstr "リポジトリの起点 '%s' は不明です。"

#: ../modules/client/api_errors.py:678
#, python-format
msgid "The URI '%(uri)s' contains an unsupported scheme '%(scheme)s'."
msgstr "URI '%(uri)s' には、サポートされていないスキーマ '%(scheme)s' が含まれています。"

#: ../modules/client/api_errors.py:681
msgid "The specified URI contains an unsupported scheme."
msgstr "指定された URI には、サポートされていないスキーマが含まれています。"

#: ../modules/client/api_errors.py:689
#, python-format
msgid "'%(attr)s' is not supported for '%(scheme)s'."
msgstr "'%(attr)s' は '%(scheme)s' でサポートされていません。"

#: ../modules/client/api_errors.py:716
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s' needed to access '%(uri)s', "
"has expired.  Please install a valid certificate."
msgstr ""
"'%(uri)s' へのアクセスに必要な発行元 '%(pub)s' の証明書 '%(cert)s' の"
"有効期限が切れています。有効な証明書をインストールしてください。"

#: ../modules/client/api_errors.py:721
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s', has expired.  Please install "
"a valid certificate."
msgstr ""
"発行元 '%(pub)s' の証明書 '%(cert)s' の有効期限が切れています。"
"有効な証明書をインストールしてください。"

#: ../modules/client/api_errors.py:726
#, python-format
msgid ""
"Certificate '%(cert)s', needed to access '%(uri)s', has expired.  Please "
"install a valid certificate."
msgstr ""
"'%(uri)s' へのアクセスに必要な証明書 '%(cert)s' の有効期限が切れています。"
"有効な証明書をインストールしてください。"

#: ../modules/client/api_errors.py:729
#, python-format
msgid "Certificate '%s' has expired.  Please install a valid certificate."
msgstr "証明書 '%s' の有効期限が切れています。有効な証明書をインストールしてください。"

#: ../modules/client/api_errors.py:742
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s', needed to access '%(uri)s', "
"will expire in '%(days)s' days."
msgstr ""
"'%(uri)s' へのアクセスに必要な発行元 '%(pub)s' の証明書 '%(cert)s' は、"
"あと '%(days)s' 日で期限切れになります。"

#: ../modules/client/api_errors.py:747
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s' will expire in '%(days)s' "
"days."
msgstr ""
"発行元 '%(pub)s' の証明書 '%(cert)s' は、あと '%(days)s' 日で期限切れに"
"なります。"

#: ../modules/client/api_errors.py:751
#, python-format
msgid ""
"Certificate '%(cert)s', needed to access '%(uri)s', will expire in '%(days)"
"s' days."
msgstr ""
"'%(uri)s' へのアクセスに必要な証明書 '%(cert)s' は、あと '%(days)s' 日で期限切れに"
"なります。"

#: ../modules/client/api_errors.py:754
#, python-format
msgid "Certificate '%(cert)s' will expire in '%(days)s' days."
msgstr "証明書 '%(cert)s' は、あと '%(days)s' 日で期限切れになります。"

#: ../modules/client/api_errors.py:766
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s', needed to access '%(uri)s', "
"is invalid."
msgstr ""
"'%(uri)s' へのアクセスに必要な発行元 '%(pub)s' の証明書 '%(cert)s' が"
"無効です。"

#: ../modules/client/api_errors.py:770
#, python-format
msgid "Certificate '%(cert)s' for publisher '%(pub)s' is invalid."
msgstr "発行元 '%(pub)s' の証明書 '%(cert)s' が無効です。"

#: ../modules/client/api_errors.py:774
#, python-format
msgid "Certificate '%(cert)s' needed to access '%(uri)s' is invalid."
msgstr "'%(uri)s' へのアクセスに必要な証明書 '%(cert)s' が無効です。"

#: ../modules/client/api_errors.py:777
#, python-format
msgid "Invalid certificate '%s'."
msgstr "証明書 '%s' が無効です。"

#: ../modules/client/api_errors.py:788
#, python-format
msgid ""
"Unable to locate certificate '%(cert)s' for publisher '%(pub)s' needed to "
"access '%(uri)s'."
msgstr ""
"'%(uri)s' へのアクセスに必要な発行元 '%(pub)s' の証明書 '%(cert)s' が"
"見つかりません。"

#: ../modules/client/api_errors.py:793
#, python-format
msgid "Unable to locate certificate '%(cert)s' for publisher '%(pub)s'."
msgstr "発行元 '%(pub)s' の証明書 '%(cert)s' が見つかりません。"

#: ../modules/client/api_errors.py:797
#, python-format
msgid "Unable to locate certificate '%(cert)s' needed to access '%(uri)s'."
msgstr "'%(uri)s' へのアクセスに必要な証明書 '%(cert)s' が見つかりません。"

#: ../modules/client/api_errors.py:800
#, python-format
msgid "Unable to locate certificate '%s'."
msgstr "証明書 '%s' が見つかりません。"

#: ../modules/client/api_errors.py:812
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s', needed to access '%(uri)s', "
"has a future effective date."
msgstr ""
"'%(uri)s' へのアクセスに必要な発行元 '%(pub)s' の証明書 '%(cert)s' の発効日が"
"未来の日付になっています。"

#: ../modules/client/api_errors.py:817
#, python-format
msgid ""
"Certificate '%(cert)s' for publisher '%(pub)s' has a future effective date."
msgstr ""
"発行元 '%(pub)s' の証明書 '%(cert)s' の発効日が未来の日付になっています。"

#: ../modules/client/api_errors.py:821
#, python-format
msgid ""
"Certificate '%(cert)s' needed to access '%(uri)s' has a future effective "
"date."
msgstr ""
"'%(uri)s' へのアクセスに必要な証明書 '%(cert)s' の発効日が"
"未来の日付になっています。"

#: ../modules/client/api_errors.py:824
#, python-format
msgid "Certificate '%s' has a future effective date."
msgstr "証明書 '%s' の発効日が未来の日付になっています。"

#: ../modules/client/api_errors.py:834
#, python-format
msgid "Gave a bad response:%s"
msgstr "不正な応答でした:%s"

#: ../modules/client/bootenv.py:132
msgid "pkg: unable to create an auto snapshot. pkg recovery is disabled."
msgstr "pkg: 自動スナップショットを作成できません。pkg の復元が無効になっています。"

#: ../modules/client/bootenv.py:211
#, python-format
msgid "pkg: A system error %s was caught executing %s"
msgstr "pkg: システムエラー %s が %s の実行中に検出されました"

#: ../modules/client/bootenv.py:215
#, python-format
msgid ""
"pkg: '%s' failed. \n"
"with a return code of %d."
msgstr ""
"pkg: '%s' が失敗しました。\n"
"リターンコードは %d です。"

#: ../modules/client/bootenv.py:220
#, python-format
msgid "pkg: unable to activate %s"
msgstr "pkg: %s をアクティブにすることができません"

#: ../modules/client/bootenv.py:225
#, python-format
msgid "pkg: unable to unmount %s"
msgstr "pkg: %s をマウント解除できません"

#: ../modules/client/bootenv.py:231
#, python-format
msgid ""
"\n"
"A clone of %s exists and has been updated and activated.\n"
"On the next boot the Boot Environment %s will be mounted on '/'.\n"
"Reboot when ready to switch to this updated BE.\n"
msgstr ""
"\n"
"%s のクローンが存在しており、それが更新およびアクティブ化されました。\n"
"次回リブート時にはブート環境 %s が「/」にマウントされます。\n"
"準備が整ったらリブートしてこの更新済みの BE に切り替えてください。\n"

#: ../modules/client/bootenv.py:248
#, python-format
msgid "pkg: The system error %s was caught executing %s"
msgstr "pkg: システムエラー %s が %s の実行中に検出されました"

#: ../modules/client/bootenv.py:252
#, python-format
msgid ""
"pkg: '%s' failed \n"
"with a return code of %d."
msgstr ""
"pkg: '%s' が失敗しました \n"
"リターンコードは %d です。"

#: ../modules/client/bootenv.py:256
#, python-format
msgid "%s has been updated successfully"
msgstr "%s の更新に成功しました"

#: ../modules/client/bootenv.py:269
#, python-format
msgid ""
" The running system has not been modified. Modifications were only made to a "
"clone of the running system.  This clone is mounted at %s should you wish to "
"inspect it."
msgstr ""
" 稼働中のシステムは変更されませんでした。変更が加えられたのは、"
"稼働中のシステムのクローンに対してだけです。このクローンは %s にマウント"
"されているので、必要に応じて調査を行なってください。"

#: ../modules/client/bootenv.py:277
#, python-format
msgid "pkg: unable to rollback BE %s and restore image"
msgstr "pkg: BE %s をロールバックしてイメージを復元できません"

#: ../modules/client/bootenv.py:283
#, python-format
msgid "%s failed to be updated. No changes have been made to %s."
msgstr "%s の更新に失敗しました。%s は変更されていません。"

#: ../modules/client/bootenv.py:295
#, python-format
msgid "pkg: unable to destroy snapshot %s"
msgstr "pkg: スナップショット %s を破棄できません"

#: ../modules/client/bootenv.py:324
#, python-format
msgid "pkg: unable to create BE %s"
msgstr "pkg: BE %s を作成できません"

#: ../modules/client/bootenv.py:329
#, python-format
msgid "pkg: unable to mount BE %s on %s"
msgstr "pkg: BE %s を %s にマウントできません"

#: ../modules/client/bootenv.py:333
#, python-format
msgid ""
"The Boot Environment %s failed to be updated. A snapshot was taken before "
"the failed attempt and is mounted here %s. Use 'beadm unmount %s' and then "
"'beadm activate %s' if you wish to boot to this BE."
msgstr ""
"ブート環境 %s の更新に失敗しました。失敗した試行を行う前に取られたスナップショットが"
"存在しており、それが %s にマウントされています。この BE にブートする場合は、"
"「beadm unmount %s」を使用してから「beadm activate %s」を使用してください。"

#: ../modules/client/bootenv.py:346
#, python-format
msgid ""
"The Boot Environment %s failed to be updated. A snapshot was taken before "
"the failed attempt and has been restored so no changes have been made to %s."
msgstr ""
"ブート環境 %s の更新に失敗しました。失敗した試行を行う前に取られた"
"スナップショットが復元されたため、%s は変更されていません。"

#: ../modules/client/image.py:1370
msgid "This server is not a valid package depot."
msgstr "このサーバーは有効なパッケージデポではありません。"

#: ../modules/client/image.py:2298 ../modules/client/image.py:2371
msgid "Before evaluation:"
msgstr "評価前:"

#: ../modules/client/image.py:2319 ../modules/client/image.py:2380
msgid "After evaluation:"
msgstr "評価後:"

#: ../modules/client/image.py:2434
msgid "SUNWipkg update check failed."
msgstr "SUNWipkg の更新チェックが失敗しました。"

#: ../modules/misc.py:424
msgid "B"
msgstr "バイト"

#: ../modules/misc.py:425
msgid "kB"
msgstr "K バイト"

#: ../modules/misc.py:426
msgid "MB"
msgstr "M バイト"

#: ../modules/misc.py:427
msgid "GB"
msgstr "G バイト"

#: ../modules/misc.py:428
msgid "TB"
msgstr "T バイト"

#: ../modules/misc.py:429
msgid "PB"
msgstr "P バイト"

#: ../modules/misc.py:430 ../modules/misc.py:434
msgid "EB"
msgstr "E バイト"

#: ../modules/server/catalog.py:106
msgid "writable root not writable by current user id or group."
msgstr "現在のユーザー ID またはグループでは書き込みできない書き込み可能ルートです。"

#: ../modules/server/catalog.py:111
msgid "unable to write to index directory."
msgstr "インデックスディレクトリに書き込めません。"

#: ../packagemanager.py:212
msgid "_Current Repository"
msgstr "現在のリポジトリ(_C)"

#: ../packagemanager.py:213
msgid "Search Current Repository"
msgstr "現在のリポジトリを検索"

#: ../packagemanager.py:216
msgid "_All Repositories"
msgstr "すべてのリポジトリ(_A)"

#: ../packagemanager.py:217
msgid "Search All Repositories"
msgstr "すべてのリポジトリを検索"

#: ../packagemanager.py:324
msgid ""
"Checking SUNWipkg and SUNWipkg-gui versions\n"
"\n"
"Please wait ..."
msgstr ""
"SUNWipkg と SUNWipkg-gui のバージョンをチェックしています\n"
"\n"
"しばらくお待ちください..."

#: ../packagemanager.py:461
#, python-format
msgid "GUI will not respond to any event! %s.Check declare_signals()"
msgstr ""
"GUI がイベントに応答しません。%s。declare_signals() をチェックしてください"

#: ../packagemanager.py:520
msgid "All Repositories Search Results"
msgstr "すべてのリポジトリの検索結果"

#: ../packagemanager.py:549 ../packagemanager.py:1892
#: ../packagemanager.py:2026 ../packagemanager.py:3059
#: ../packagemanager.py:3501
msgid "All"
msgstr "すべて"

#: ../packagemanager.py:577
msgid "<html><head></head><body></body></html>"
msgstr "<html><head></head><body></body></html>"

#: ../packagemanager.py:641
#, python-format
msgid ""
"<html><head></head><body><H2>Welcome toPackageManager!</H2><br><font "
"color='#0000FF'>Warning: Unable to load Start Page:<br>%s</font></body></"
"html>"
msgstr ""
"<html><head></head><body><H2>パッケージマネージャーへようこそ</H2><br><font "
"color='#0000FF'>警告: 開始ページを読み込めません:<br>%s</font></body></"
"html>"

#: ../packagemanager.py:685
#, python-format
msgid "%s"
msgstr "%s"

#: ../packagemanager.py:737
msgid "Loading... "
msgstr "読み込み中... "

#: ../packagemanager.py:743
msgid "Stopped"
msgstr "停止しました"

#: ../packagemanager.py:757
msgid "Done"
msgstr "完了"

#: ../packagemanager.py:764
#, python-format
msgid ""
"<html><head></head><body><font color='#000000'>                    <a "
"href='stub'></a></font>                    <a href='pm?%s=internal&uri=%"
"s'>                    <IMG SRC = 'startpage_star.png'                     "
"style='border-style: none'></a> <br><br>                    <h2><font "
"color='#0000FF'>Warning: Unable to                     load URL</font></"
"h2><br>%s</body></html>"
msgstr ""
"<html><head></head><body><font color='#000000'>                    <a "
"href='stub'></a></font>                    <a href='pm?%s=internal&uri=%"
"s'>                    <IMG SRC = 'startpage_star.png'                     "
"style='border-style: none'></a> <br><br>                    <h2><font "
"color='#0000FF'>警告: URL を                     読み込めません</font></"
"h2><br>%s</body></html>"

#: ../packagemanager.py:793 ../packagemanager.py:805
msgid "No URI specified"
msgstr "URI が指定されていません"

#: ../packagemanager.py:827
msgid "Empty Action not supported"
msgstr "空のアクションはサポートされていません"

#: ../packagemanager.py:831
#, python-format
msgid "Action not supported: %s"
msgstr "アクションはサポートされていません: %s"

#: ../packagemanager.py:916 ../packagemanager.py:1014 ../updatemanager.py:584
msgid "Name"
msgstr "名前"

#: ../packagemanager.py:926
msgid "Status"
msgstr "状態"

#: ../packagemanager.py:935
msgid "Repository"
msgstr "リポジトリ"

#: ../packagemanager.py:940
msgid "Description"
msgstr "説明"

#: ../packagemanager.py:1101 ../packagemanager.py:1171
msgid "Updates Available"
msgstr "更新が使用可能です"

#: ../packagemanager.py:1169
msgid "Not Installed"
msgstr "インストールされていません"

#. We enable only first section and later we might enable the rest,
#. depending if there are some packages connected with them
#: ../packagemanager.py:1260
msgid "All Categories"
msgstr "すべてのカテゴリ"

#: ../packagemanager.py:1263
msgid "Meta Packages"
msgstr "メタパッケージ"

#: ../packagemanager.py:1264
msgid "Applications"
msgstr "アプリケーション"

#: ../packagemanager.py:1265
msgid "Desktop (GNOME)"
msgstr "デスクトップ (GNOME)"

#: ../packagemanager.py:1266
msgid "Development"
msgstr "開発"

#: ../packagemanager.py:1267
msgid "Distributions"
msgstr "ディストリビューション"

#: ../packagemanager.py:1268
msgid "Drivers"
msgstr "ドライバ"

#: ../packagemanager.py:1270
msgid "Web Services"
msgstr "Web サービス"

#: ../packagemanager.py:1273
msgid "All Packages"
msgstr "すべてのパッケージ"

#: ../packagemanager.py:1275
msgid "Installed Packages"
msgstr "インストール済みパッケージ"

#: ../packagemanager.py:1279
msgid "Non-installed Packages"
msgstr "インストールされていないパッケージ"

#: ../packagemanager.py:1282
msgid "Selected Packages"
msgstr "選択したパッケージ"

#. This can happen if load_catalogs has not been run
#: ../packagemanager.py:1472
msgid ""
"Unable to get status for search results.\n"
"The catalogs have not been loaded.\n"
"Please try after few seconds.\n"
msgstr ""
"検索結果の状態を取得できません。\n"
"カタログが読み込まれていません。\n"
"数秒後に再試行してください。\n"

#: ../packagemanager.py:1571
msgid "Fetching legal information..."
msgstr "使用条件情報を取得しています..."

#. Checking for Add... is fine enough, as the repository
#. name cannot contain "..." in the name.
#: ../packagemanager.py:1939 ../packagemanager.py:1959
#: ../packagemanager.py:2197
msgid "Add..."
msgstr "追加..."

#: ../packagemanager.py:2120
msgid "Refreshing catalogs"
msgstr "カタログの再表示中"

#: ../packagemanager.py:2121
msgid "Refreshing catalogs..."
msgstr "カタログの再表示中..."

#: ../packagemanager.py:2265
msgid "Selected for Removal:"
msgstr "選択された削除対象:"

#: ../packagemanager.py:2273
msgid "Selected for Install/Update:"
msgstr "選択されたインストール/更新対象:"

#: ../packagemanager.py:2277 ../packagemanager.py:2282
msgid "Select packages by marking checkbox\n"
msgstr "チェックボックスにチェックマークを付けてパッケージを選択してください\n"

#: ../packagemanager.py:2329
msgid "Package Name"
msgstr "パッケージ名"

#: ../packagemanager.py:2348
msgid "Fetching description..."
msgstr "説明を取得中..."

#: ../packagemanager.py:2352
msgid "Fetching information..."
msgstr "情報を取得中..."

#: ../packagemanager.py:2391
msgid ""
"\n"
"This might be caused by network problem while accessing the repository."
msgstr ""
"\n"
"リポジトリへのアクセス中にネットワークの問題が発生すると、このようになる場合があります。"

#: ../packagemanager.py:2394
msgid "Description not available for this package..."
msgstr "このパッケージの説明がありません..."

#: ../packagemanager.py:2397
msgid "Files Details not available for this package..."
msgstr "このパッケージのファイルの詳細がありません..."

#: ../packagemanager.py:2400
msgid "Dependencies info not available for this package..."
msgstr "このパッケージの依存性の情報がありません..."

#: ../packagemanager.py:2403
msgid "Information not available for this package..."
msgstr "このパッケージの情報がありません..."

#: ../packagemanager.py:2421
#, python-format
msgid "Root: %s\n"
msgstr "ルート: %s\n"

#: ../packagemanager.py:2422
msgid "Dependencies:\n"
msgstr "依存関係:\n"

#: ../packagemanager.py:2437
msgid "Summary:\t\t"
msgstr "概要:\t\t"

#: ../packagemanager.py:2438
msgid "Size:\t\t\t"
msgstr "サイズ:\t\t\t"

#: ../packagemanager.py:2439
msgid "Category:\t\t"
msgstr "カテゴリ:\t\t"

#: ../packagemanager.py:2440
msgid "Installed Version:\t"
msgstr "インストールされているバージョン:\t"

#: ../packagemanager.py:2442
msgid "Packaging Date:\t"
msgstr "パッケージ化の日付:\t"

#: ../packagemanager.py:2443
msgid "FMRI:\t\t\t"
msgstr "FMRI:\t\t\t"

#: ../packagemanager.py:2444
msgid "Repository:\t\t"
msgstr "リポジトリ:\t\t"

#: ../packagemanager.py:2449 ../packagemanager.py:2457 ../updatemanager.py:769
#: ../updatemanager.py:784
msgid "None"
msgstr "なし"

#: ../packagemanager.py:2482
msgid "Not available"
msgstr "使用不可"

#: ../packagemanager.py:2834
msgid ""
"Network problem.\n"
"\n"
msgstr ""
"ネットワークの問題。\n"
"\n"

#: ../packagemanager.py:2835
msgid "Details:\n"
msgstr "詳細:\n"

#: ../packagemanager.py:2837
msgid " catalogs successfully updated:\n"
msgstr " カタログの更新に成功しました:\n"

#: ../packagemanager.py:2860
msgid "Unknown error"
msgstr "不明なエラー"

#. Can't happen when all_known is true and no args,
#. but here for completeness.
#: ../packagemanager.py:2903
msgid ""
"Selected repository does not contain any packages.\n"
"Please reload the list of package."
msgstr ""
"選択されたリポジトリにはパッケージが含まれていません。\n"
"パッケージリストを再読み込みしてください。"

#: ../packagemanager.py:3144
#, python-format
msgid "Processing package entries: %d of %d"
msgstr "パッケージエントリを処理しています: %d/%d"

#: ../packagemanager.py:3247
msgid "Loading Repository Information"
msgstr "リポジトリ情報の読み込み中"

#: ../packagemanager.py:3249
msgid "Fetching package entries ..."
msgstr "パッケージエントリの取得中..."

#: ../packagemanager.py:3363
msgid "Searching..."
msgstr "検索中..."

#: ../packagemanager.py:3374
#, python-format
msgid "%s: first %d found"
msgstr "%s: 最初の %d が見つかりました"

#: ../packagemanager.py:3376
#, python-format
msgid "%s: %d found"
msgstr "%s: %d が見つかりました"

#: ../packagemanager.py:3395
#, python-format
msgid "%d listed"
msgstr "%d が一覧表示されました"

#: ../packagemanager.py:3396
#, python-format
msgid "%d selected"
msgstr "%d が選択されました"

#: ../packagemanager.py:3397
#, python-format
msgid "%d installed"
msgstr "%d がインストールされました"

#: ../packagemanager.py:3398
#, python-format
msgid "%s: %s , %s, %s."
msgstr "%s: %s、%s、%s。"

#: ../packagemanager.py:3470
msgid ""
"The Update All action is now complete and Package Manager will close.\n"
"\n"
"Review the posted release notes before rebooting your system:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"「すべて更新」アクションが完了しました。パッケージマネージャーは終了します。\n"
"\n"
"システムを再起動する前に、次の場所で公開されているリリースノートを確認してください:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../packagemanager.py:3486
msgid "Save selected..."
msgstr "選択した項目を保存..."

#: ../packagemanager.py:3487
msgid "Save selected packages..."
msgstr "選択したパッケージを保存..."

#: ../packagemanager.py:3530 ../packagemanager.py:3534
#: ../packagemanager.py:3538 ../packagemanager.py:3555
#: ../packagemanager.py:3571
msgid "Graphics"
msgstr "グラフィックス"

#: ../packagemanager.py:3552 ../packagemanager.py:3554
#: ../packagemanager.py:3556 ../packagemanager.py:3558
#: ../packagemanager.py:3560 ../packagemanager.py:3562
#: ../packagemanager.py:3564 ../packagemanager.py:3566
#: ../packagemanager.py:3568
msgid "Applications Desktop"
msgstr "アプリケーションデスクトップ"

#: ../packagemanager.py:3561
msgid "Sound & Video"
msgstr "サウンドとビデオ"

#: ../packagemanager.py:3563
msgid "System Tools"
msgstr "システムツール"

#. Can be twice :)
#: ../packagemanager.py:3567 ../packagemanager.py:3576
msgid "Developer Tools"
msgstr "開発者ツール"

#: ../packagemanager.py:3570 ../packagemanager.py:3572
#: ../packagemanager.py:3574 ../packagemanager.py:3577
msgid "Operating System"
msgstr "オペレーティングシステム"

#: ../packagemanager.py:3580
msgid "Office2"
msgstr "オフィス 2"

#: ../publish.py:78
msgid ""
"Usage:\n"
"        pkgsend [options] command [cmd_options] [operands]\n"
"\n"
"Packager subcommands:\n"
"        pkgsend create-repository\n"
"        pkgsend open [-en] pkg_fmri\n"
"        pkgsend add action arguments\n"
"        pkgsend import [-T file_pattern] bundlefile ...\n"
"        pkgsend include [-d basedir] manifest ...\n"
"        pkgsend close [-A]\n"
"\n"
"        pkgsend rename src_fmri dest_fmri\n"
"\n"
"Options:\n"
"        -s repo_uri     target repository URI\n"
"        --help or -?    display usage message\n"
"\n"
"Environment:\n"
"        PKG_REPO"
msgstr ""
"使用方法:\n"
"        pkgsend [options] command [cmd_options] [operands]\n"
"\n"
"パッケージャーのサブコマンド:\n"
"        pkgsend create-repository\n"
"        pkgsend open [-en] pkg_fmri\n"
"        pkgsend add action arguments\n"
"        pkgsend import [-T file_pattern] bundlefile ...\n"
"        pkgsend include [-d basedir] manifest ...\n"
"        pkgsend close [-A]\n"
"\n"
"        pkgsend rename src_fmri dest_fmri\n"
"\n"
"オプション:\n"
"        -s repo_uri     target repository URI\n"
"        --help or -?    display usage message\n"
"\n"
"環境:\n"
"        PKG_REPO"

#: ../publish.py:104
msgid "command does not take operands"
msgstr "コマンドはオペランドを取りません"

#: ../publish.py:128
msgid "only -e or -n may be specified"
msgstr "指定できるのは -e または -n だけです"

#: ../publish.py:131
msgid "open requires one package name"
msgstr "open ではパッケージ名を 1 つ指定する必要があります"

#: ../publish.py:157
msgid "No transaction ID specified using -t or in $PKG_TRANS_ID."
msgstr "-t の使用時、または $PKG_TRANS_ID でトランザクション ID が指定されていません。"

#: ../publish.py:171 ../publish.py:222 ../publish.py:274
msgid "No transaction ID specified in $PKG_TRANS_ID"
msgstr "$PKG_TRANS_ID にトランザクション ID が指定されていません"

#: ../publish.py:175 ../publish.py:204 ../publish.py:226 ../publish.py:286
msgid "No arguments specified for subcommand."
msgstr "サブコマンドに引数が指定されていません。"

#: ../publish.py:178
msgid "A filename must be provided for this action."
msgstr "このアクションにはファイル名を指定する必要があります。"

#: ../publish.py:326
#, python-format
msgid "pkgsend: illegal global option -- %s"
msgstr "pkgsend: 不正なグローバルオプション -- %s"

#: ../pull.py:51
msgid ""
"Usage:\n"
"        pkgrecv -s server [-d dir] pkgfmri ...\n"
"        pkgrecv -s server -n"
msgstr ""
"使用方法:\n"
"        pkgrecv -s server [-d dir] pkgfmri ...\n"
"        pkgrecv -s server -n"

#: ../pull.py:75
#, python-format
msgid "Unable to open manifest: %s"
msgstr "マニフェスト %s を開けません"

#: ../pull.py:111
#, python-format
msgid "Unable to download files from: %s"
msgstr "%s からファイルをダウンロードできません"

#: ../pull.py:120 ../pull.py:165
#, python-format
msgid "Unable to create directory: %s"
msgstr "ディレクトリ %s を作成できません"

#: ../pull.py:138
#, python-format
msgid "Unable to extract file: %s"
msgstr "ファイル %s を抽出できません"

#: ../pull.py:153
#, python-format
msgid "Unable to download manifest %s from %s"
msgstr "マニフェスト %s を %s からダウンロードできません"

#: ../pull.py:173
#, python-format
msgid "Unable to open file: %s"
msgstr "ファイル %s を開けません"

#: ../pull.py:180
#, python-format
msgid "Error occurred while reading from: %s"
msgstr "%s からの読み取り中にエラーが発生しました"

#: ../pull.py:186
#, python-format
msgid "Error occurred while writing to: %s"
msgstr "%s への書き込み中にエラーが発生しました"

#: ../pull.py:225
#, python-format
msgid "Unable to download catalog from: %s"
msgstr "%s からカタログをダウンロードできません"

#: ../pull.py:235
#, python-format
msgid "Error while reading from: %s"
msgstr "%s からの読み取り中にエラーが発生しました"

#: ../pull.py:262
#, python-format
msgid "Illegal option -- %s"
msgstr "不正なオプション -- %s"

#: ../pull.py:275
msgid "must specify a server"
msgstr "サーバーを指定する必要があります"

#: ../pull.py:282
msgid "-n takes no options"
msgstr "-n はオプションを取りません"

#: ../pull.py:290
msgid "must specify at least one pkgfmri"
msgstr "pkgfmri は少なくとも 1 つ指定する必要があります"

#: ../pull.py:302
#, python-format
msgid "%(fmri)s is an illegal fmri: %(error)s"
msgstr "%(fmri)s は不正な FMRI です: %(error)s"

#: ../pull.py:315
msgid "No files to retrieve."
msgstr "取得対象のファイルが存在しません。"

#: ../um/data/updatemanager-preferences.schemas.in.h:1
msgid ""
"A text message describing the updates is displayed near the panel's "
"Notification Area when updates become available if set to true."
msgstr ""
"true に設定された場合、更新が使用可能になった際に、その更新を"
"説明するテキストメッセージがパネルの通知領域の近くに表示されます。"

#: ../um/data/updatemanager-preferences.schemas.in.h:2
msgid "How often to check for updates"
msgstr "更新のチェック頻度"

#: ../um/data/updatemanager-preferences.schemas.in.h:3
msgid ""
"How often to check for updates. The valid values are Daily, Weekly, Monthly, "
"Never"
msgstr ""
"更新のチェック頻度を指定します。有効な値は「毎日」、"
"「毎週」、「毎月」、「なし」です"

#: ../um/data/updatemanager-preferences.schemas.in.h:4
msgid "Start delay"
msgstr "開始遅延"

#: ../um/data/updatemanager-preferences.schemas.in.h:5
msgid "The notify icon is displayed on startup if set to true."
msgstr "true に設定された場合、起動時に通知アイコンが表示されます。"

#: ../um/data/updatemanager-preferences.schemas.in.h:6
msgid ""
"The time, in seconds, that the updatemanagernotifier should wait, after "
"starting, before checking for updates."
msgstr ""
"開始したあとで更新をチェックする前に updatemanagernotifier が"
"待機する秒数。"

#: ../um/data/updatemanager-preferences.schemas.in.h:7
msgid ""
"The updatemanagernotifier program terminates after the user activates the "
"icon in the notification area if set to true."
msgstr ""
"true に設定された場合、ユーザーが通知領域のアイコンをアクティブにすると、"
"updatemanagernotifier プログラムは終了します。"

#: ../um/data/updatemanager-preferences.schemas.in.h:8
msgid "Whether to always display the icon on startup"
msgstr "起動時に常にアイコンを表示するかどうか"

#: ../um/data/updatemanager-preferences.schemas.in.h:9
msgid "Whether to display text message when updates are available"
msgstr "更新が使用可能になった際にテキストメッセージを表示するかどうか"

#: ../um/data/updatemanager-preferences.schemas.in.h:10
msgid "Whether to terminate updatemanagernotiifer after icon activation."
msgstr "アイコンがアクティブになった際に updatemanagernotiifer を終了するかどうか。"

#: ../um/data/updatemanager.desktop.in.h:1
msgid "Install available updates"
msgstr "使用可能な更新をインストールします"

#: ../um/data/updatemanager.desktop.in.h:2 ../um/data/updatemanager.glade.h:10
#: ../updatemanager.py:953 ../updatemanagernotifier.py:350
msgid "Update Manager"
msgstr "更新マネージャー"

#: ../um/data/updatemanager.glade.h:1
msgid "<b>Evaluate</b>"
msgstr "<b>評価</b>"

#: ../um/data/updatemanager.glade.h:2
msgid "<b>Latest Version _Details</b>"
msgstr "<b>最新バージョンの詳細(_D)</b>"

#: ../um/data/updatemanager.glade.h:3
msgid "<b>_Details</b>"
msgstr "<b>詳細(_D)</b>"

#: ../um/data/updatemanager.glade.h:5
msgid "Close dialog when _finished"
msgstr "終了時にダイアログを閉じる(_F)"

#: ../um/data/updatemanager.glade.h:7 ../updatemanager.py:206
#: ../updatemanager.py:399 ../updatemanager.py:406 ../updatemanager.py:413
#: ../updatemanager.py:420 ../updatemanager.py:427
msgid "Index"
msgstr "インデックス"

#: ../um/data/updatemanager.glade.h:8
msgid "Install Update"
msgstr "更新のインストール"

#: ../um/data/updatemanager.glade.h:11 ../updatemanager.py:564
msgid ""
"Updates are available for the following packages.\n"
"Select the packages you want to update and click Install."
msgstr ""
"使用可能な更新が存在するパッケージは、次のとおりです。\n"
"更新するパッケージを選択し、「インストール」をクリックしてください。"

#: ../um/data/updatemanager.glade.h:13
msgid "_Cancel"
msgstr "キャンセル(_C)"

#: ../um/data/updatemanager.glade.h:14
msgid "_Install Updates"
msgstr "更新のインストール(_I)"

#: ../um/data/updatemanager.glade.h:15
msgid "_OK"
msgstr "了解(_O)"

#: ../um/data/updatemanager.glade.h:16
msgid "_Select all Updates"
msgstr "すべての更新を選択(_S)"

#: ../um/data/updatemanagernotifier.desktop.in.h:1
msgid "Notify user when updates are available"
msgstr "更新が使用可能になった際にユーザーに通知します"

#: ../um/data/updatemanagernotifier.desktop.in.h:2
msgid "Update Manager Notifier"
msgstr "更新マネージャー通知"

#: ../updatemanager.py:122
#, python-format
msgid "Fetching catalog: '%s' ..."
msgstr "カタログ '%s' の取得中..."

#: ../updatemanager.py:126
msgid "Fetching catalog"
msgstr "カタログの取得中"

#: ../updatemanager.py:129
msgid "Creating Plan ... "
msgstr "計画の作成中... "

#: ../updatemanager.py:140
msgid "Creating Plan"
msgstr "計画の作成中"

#: ../updatemanager.py:151
#, python-format
msgid "Verifying: %s ..."
msgstr "%s の検証中..."

#: ../updatemanager.py:158
msgid "Verifying"
msgstr "検証中"

#: ../updatemanager.py:172
msgid "Completed"
msgstr "完了"

#: ../updatemanager.py:357
#, python-format
msgid "GUI will not respond to any event! %s. Check updatemanager.py signals"
msgstr "GUI はどのイベントにも応答しません。%s。updatemanager.py のシグナルをチェックしてください"

#: ../updatemanager.py:396 ../updatemanager.py:403 ../updatemanager.py:410
#: ../updatemanager.py:417 ../updatemanager.py:424
msgid "Evaluate"
msgstr "評価"

#: ../updatemanager.py:432
msgid "Evaluate - canceling..."
msgstr "評価 - キャンセル中..."

#: ../updatemanager.py:436
msgid "Download - canceling..."
msgstr "ダウンロード - キャンセル中..."

#: ../updatemanager.py:441
msgid "Evaluate - failed"
msgstr "評価 - 失敗しました"

#: ../updatemanager.py:445
msgid "Download - failed"
msgstr "ダウンロード - 失敗しました"

#: ../updatemanager.py:449
msgid "Install - failed"
msgstr "インストール - 失敗しました"

#: ../updatemanager.py:453
msgid "Index - failed"
msgstr "インデックス - 失敗しました"

#: ../updatemanager.py:571
msgid ""
"Updates are available for the following packages.\n"
"Click Update All to create a new boot environment and install all packages "
"into it."
msgstr ""
"更新が可能なパッケージは、次のとおりです。\n"
"新しいブート環境を作成し、その中にすべてのパッケージをインストールするには、"
"「すべて更新」をクリックします。"

#: ../updatemanager.py:599
msgid "Latest Version"
msgstr "最新バージョン"

#: ../updatemanager.py:608
msgid "Size (Meg)"
msgstr "サイズ (M バイト)"

#: ../updatemanager.py:690
#, python-format
msgid "count: %d"
msgstr "カウント: %d"

#: ../updatemanager.py:715 ../updatemanager.py:725
msgid "Error\n"
msgstr "エラー\n"

#: ../updatemanager.py:718
#, python-format
msgid "'%s' is not an install image\n"
msgstr "'%s' はインストールイメージではありません\n"

#: ../updatemanager.py:728
#, python-format
msgid "Version mismatch: expected %s received %s\n"
msgstr "バージョンの不一致: 期待値 %s 実際値 %s\n"

#: ../updatemanager.py:733
msgid "<b>No Updates available.</b>"
msgstr "<b>使用可能な更新は存在しません。</b>"

#: ../updatemanager.py:789
#, python-format
msgid ""
"\n"
"Summary:\t\t\t%s\n"
"Size:       \t\t\t%s\n"
"Category:\t\t\t%s\n"
"Latest Version:\t\t%s\n"
"Installed Version:\t%s\n"
"Packaging Date:\t%s\n"
"FMRI:       \t\t\t%s\n"
"Repository:       \t\t%s\n"
msgstr ""
"\n"
"概要:\t\t\t%s\n"
"サイズ:       \t\t\t%s\n"
"カテゴリ:\t\t\t%s\n"
"最新バージョン:\t\t%s\n"
"インストールされているバージョン:\t%s\n"
"パッケージ化の日付:\t%s\n"
"FMRI:       \t\t\t%s\n"
"リポジトリ:       \t\t%s\n"

#: ../updatemanager.py:819 ../updatemanagernotifier.py:309
#, python-format
msgid "%s is not valid image, trying root image"
msgstr "%s は有効なイメージではありません。ルートイメージを試しています"

#: ../updatemanager.py:829 ../updatemanagernotifier.py:319
#, python-format
msgid "%s is not valid root image, return None"
msgstr "%s は有効なルートイメージではありません。None を返します"

#: ../updatemanager.py:867
#, python-format
msgid ""
"\n"
"Fetching details for %s ..."
msgstr ""
"\n"
"%s の詳細の取得中..."

#: ../updatemanager.py:891
msgid ""
"\n"
"No details available"
msgstr ""
"\n"
"使用可能な詳細が存在しません"

#: ../updatemanager.py:932
msgid ""
"\n"
"Canceling update, please wait ..."
msgstr ""
"\n"
"更新のキャンセル中。しばらくお待ちください..."

#: ../updatemanager.py:937
msgid ""
"\n"
"Unable to cancel at this time."
msgstr ""
"\n"
"この時点でキャンセルすることはできません。"

#: ../updatemanager.py:940
msgid "Installing Updates"
msgstr "更新のインストール中"

#: ../updatemanager.py:963
msgid "ERROR"
msgstr "エラー"

#: ../updatemanager.py:965
msgid "Following Incorporated package(s) cannot be updated:"
msgstr "次の組み込みパッケージは更新できません:"

#: ../updatemanager.py:969
msgid "Update using: Update All\n"
msgstr "更新方法: すべて更新\n"

#: ../updatemanager.py:986 ../updatemanager.py:1116 ../updatemanager.py:1151
msgid ""
"\n"
"ERROR"
msgstr ""
"\n"
"エラー"

#: ../updatemanager.py:989
#, python-format
msgid ""
"%s\n"
"%s"
msgstr ""
"%s\n"
"%s"

#: ../updatemanager.py:1001
#, python-format
msgid ""
"\n"
"Update All finished successfully in %1.f mins\n"
"\n"
msgstr ""
"\n"
"「すべて更新」が %1.f 分で正常に終了しました\n"
"\n"

#: ../updatemanager.py:1006
msgid ""
"\n"
"Update All finished successfully in < 1 min\n"
"\n"
msgstr ""
"\n"
"「すべて更新」が 1 分未満で正常に終了しました\n"
"\n"

#: ../updatemanager.py:1009
msgid ""
"Review the posted release notes before rebooting your system:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"システムを再起動する前に、次の場所で公開されているリリースノートを確認してください:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../updatemanager.py:1018
msgid "Update All Completed"
msgstr "「すべて更新」が完了しました"

#: ../updatemanager.py:1035
msgid "Nothing selected to update."
msgstr "更新対象として何も選択されていません。"

#: ../updatemanager.py:1042
msgid "Updating ..."
msgstr "更新中..."

#: ../updatemanager.py:1048
msgid ""
"\n"
"Evaluate\n"
msgstr ""
"\n"
"評価\n"

#: ../updatemanager.py:1054
msgid "Update error in plan install:"
msgstr "計画インストール時の更新エラー:"

#: ../updatemanager.py:1064
msgid "Update unexpected API error:"
msgstr "更新時の予期しない API エラー:"

#: ../updatemanager.py:1069
msgid "Update unexpected error:"
msgstr "更新時の予期しないエラー:"

#: ../updatemanager.py:1092
msgid "Packages to be installed:"
msgstr "インストールするパッケージ:"

#: ../updatemanager.py:1096
msgid "Update"
msgstr "更新"

#: ../updatemanager.py:1097
msgid "Update finished successfully."
msgstr "更新が正常に終了しました。"

#: ../updatemanager.py:1118
#, python-format
msgid ""
"%s Download failed:\n"
"%s"
msgstr ""
"%s ダウンロードが失敗しました:\n"
"%s"

#: ../updatemanager.py:1125 ../updatemanager.py:1160
#, python-format
msgid "%s exceded available disc space"
msgstr "%s が、使用可能なディスク容量を超えました"

#: ../updatemanager.py:1130 ../updatemanager.py:1135 ../updatemanager.py:1165
#: ../updatemanager.py:1170
#, python-format
msgid "%s unexpected error:"
msgstr "%s の予期しないエラー:"

#: ../updatemanager.py:1153
#, python-format
msgid ""
"%s Execute plan failed:\n"
"%s"
msgstr ""
"%s 計画の実行が失敗しました:\n"
"%s"

#: ../updatemanager.py:1187
msgid ""
"Not enough disc space, the Update All action cannot be performed.\n"
"\n"
"Click OK to manage your existing BEs and free up disk space or Cancel to "
"cancel Update All."
msgstr ""
"ディスク容量が不足しているため「すべて更新」アクションを実行できません。\n"
"\n"
"既存の BE を管理してディスク容量を解放する場合は「了解」をクリックし、「すべて更新」を取り消す場合は"
"「取消し」をクリックしてください。"

#: ../updatemanager.py:1191
msgid "Not Enough Disc Space"
msgstr "ディスク容量が不足しています"

#: ../updatemanager.py:1359
msgid ""
"\n"
"Download\n"
msgstr ""
"\n"
"ダウンロード\n"

#: ../updatemanager.py:1366
#, python-format
msgid "\tpkg %d/%d: \tfiles %d/%d \txfer %.2f/%.2f(meg)"
msgstr "\tpkg %d/%d: \tファイル %d/%d \t転送 %.2f/%.2f (M バイト)"

#: ../updatemanager.py:1383
msgid ""
"\n"
"Install\n"
msgstr ""
"\n"
"インストール\n"

#: ../updatemanager.py:1385 ../updatemanager.py:1389
#, python-format
msgid "\t%s\t%d/%d actions"
msgstr "\t%s\t%d/%d アクション"

#: ../updatemanager.py:1407
msgid "Index\n"
msgstr "インデックス\n"

#: ../updatemanager.py:1408 ../updatemanager.py:1412
#, python-format
msgid "\t%-25s\t%d/%d actions"
msgstr "\t%-25s\t%d/%d アクション"

#: ../updatemanager.py:1494
msgid "Checking for new software"
msgstr "新しいソフトウェアのチェック中"

#: ../updatemanagernotifier.py:329
msgid "Updates are available"
msgstr "更新が使用可能です"

#: ../updatemanagernotifier.py:351
msgid ""
"Updates available\n"
"Please click on icon to update."
msgstr ""
"更新が使用可能です\n"
"更新する場合はアイコンをクリックしてください。"

#: ../updatemanagernotifier.py:426
msgid "Another instance of UpdateManagerNotify is running"
msgstr "UpdateManagerNotify の別のインスタンスが実行中です"
