# Copyright (C) 2008 Sun Microsystems, Inc
# This file is distributed under the same license as the packagemanager package.
#
# Desktop Discuss <desktop-discuss@opensolaris.org>
#
msgid ""
msgstr ""
"Project-Id-Version: packagemanager HEAD\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2008-05-29 17:42+0900\n"
"PO-Revision-Date: 2008-05-13 22:01+0900\n"
"Last-Translator: desktop-discuss@opensolaris.org\n"
"Language-Team: desktop-discuss@opensolaris.org\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../client.py:109
msgid ""
"Usage:\n"
"        pkg [options] command [cmd_options] [operands]\n"
"\n"
"Basic subcommands:\n"
"        pkg install [-nvq] [--no-refresh] [--no-index] package...\n"
"        pkg uninstall [-nrvq] [--no-index] package...\n"
"        pkg list [-aHsuvf] [package...]\n"
"        pkg image-update [-fnvq] [--no-refresh] [--no-index]\n"
"        pkg refresh [--full] [authority ...]\n"
"        pkg version\n"
"        pkg help\n"
"\n"
"Advanced subcommands:\n"
"        pkg info [-lr] [--license] [pkg_fmri_pattern ...]\n"
"        pkg search [-lrI] [-s server] token\n"
"        pkg verify [-Hqv] [pkg_fmri_pattern ...]\n"
"        pkg fix [pkg_fmri_pattern ...]\n"
"        pkg contents [-Hmr] [-o attribute ...] [-s sort_key]\n"
"            [-t action_type ... ] [pkg_fmri_pattern ...]\n"
"        pkg image-create [-fFPUz] [--force] [--full|--partial|--user] [--"
"zone]\n"
"            [-k ssl_key] [-c ssl_cert] [--no-refresh] -a <prefix>=<url> dir\n"
"\n"
"        pkg set-property propname propvalue\n"
"        pkg unset-property propname ...\n"
"        pkg property [-H] [propname ...]\n"
"\n"
"        pkg set-authority [-P] [-k ssl_key] [-c ssl_cert] [--reset-uuid]\n"
"            [-O origin_url] [-m mirror_to_add | --add-mirror=mirror_to_add]\n"
"            [-M mirror_to_remove | --remove-mirror=mirror_to_remove]\n"
"            [--no-refresh] authority\n"
"        pkg unset-authority authority ...\n"
"        pkg authority [-HP] [authority ...]\n"
"        pkg history [-Hl]\n"
"        pkg purge-history\n"
"        pkg rebuild-index\n"
"\n"
"Options:\n"
"        -R dir\n"
"        -D/--debug name=value\n"
"\n"
"Environment:\n"
"        PKG_IMAGE"
msgstr ""
"使用方法:\n"
"        pkg [options] command [cmd_options] [operands]\n"
"\n"
"基本的なサブコマンド:\n"
"        pkg install [-nvq] [--no-refresh] [--no-index] package...\n"
"        pkg uninstall [-fnrvq] [--no-index] package...\n"
"        pkg list [-aHsuvf] [package...]\n"
"        pkg image-update [-fnvq] [--no-refresh] [--no-index]\n"
"        pkg refresh [--full] [authority ...]\n"
"        pkg version\n"
"        pkg help\n"
"\n"
"高度なサブコマンド:\n"
"        pkg info [-lr] [--license] [pkg_fmri_pattern ...]\n"
"        pkg search [-lrI] [-s server] token\n"
"        pkg verify [-Hqv] [pkg_fmri_pattern ...]\n"
"        pkg fix [pkg_fmri_pattern ...]\n"
"        pkg contents [-Hmr] [-o attribute ...] [-s sort_key]\n"
"            [-t action_type ... ] [pkg_fmri_pattern ...]\n"
"        pkg image-create [-fFPUz] [--force] [--full|--partial|--user] [--"
"zone]\n"
"            [-k ssl_key] [-c ssl_cert] [--no-refresh] -a <prefix>=<url> dir\n"
"\n"
"        pkg set-property propname propvalue\n"
"        pkg unset-property propname ...\n"
"        pkg property [-H] [propname ...]\n"
"\n"
"        pkg set-authority [-P] [-k ssl_key] [-c ssl_cert] [--reset-uuid]\n"
"            [-O origin_url] [-m mirror_to_add | --add-mirror=mirror_to_add]\n"
"            [-M mirror_to_remove | --remove-mirror=mirror_to_remove]\n"
"            [--no-refresh] authority\n"
"        pkg unset-authority authority ...\n"
"        pkg authority [-HP] [authority ...]\n"
"        pkg history [-Hl]\n"
"        pkg purge-history\n"
"        pkg rebuild-index\n"
"\n"
"オプション:\n"
"        -R dir\n"
"        -D/--debug name=value\n"
"\n"
"環境:\n"
"        PKG_IMAGE"

#: ../client.py:203
msgid "-s and -v may not be combined"
msgstr "-s と -v を組み合わせることはできません"

#: ../client.py:317 ../client.py:930 ../client.py:1190
msgid "no packages installed"
msgstr "インストール済みのパッケージが存在しません"

#: ../client.py:324
msgid "No specified packages have available updates"
msgstr "指定されたパッケージの中で、使用可能な更新を持つものは存在しません"

#: ../client.py:327
msgid "No installed packages have available updates"
msgstr "インストール済みパッケージの中で、使用可能な更新を持つものは存在しません"

#: ../client.py:353
#, python-format
msgid "no packages matching '%s' %s"
msgstr "'%s' に一致するパッケージが存在しません %s"

#: ../client.py:387
msgid "verify: -v and -q may not be combined"
msgstr "verify: -v と -q を組み合わせることはできません"

#: ../client.py:442
msgid ""
"pkg: no packages matching the following patterns you specified are\n"
"installed on the system.\n"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージの中で、\n"
"システムにインストール済みのものは存在しません。\n"

#: ../client.py:452
#, python-format
msgid ""
"\n"
"All other patterns matched installed packages.  %s"
msgstr ""
"\n"
"ほかのパターンは、すべてインストール済みパッケージに一致しました。  %s"

#: ../client.py:487
msgid "image-update: -v and -q may not be combined"
msgstr "image-update: -v と -q を組み合わせることはできません"

#: ../client.py:490
#, python-format
msgid "image-update: command does not take operands ('%s')"
msgstr "image-update: コマンドはオペランドを取りません ('%s')"

#: ../client.py:500 ../client.py:533
#, python-format
msgid "No image rooted at '%s'"
msgstr "'%s' をルートに持つイメージは存在しません"

#: ../client.py:513 ../updatemanager.py:1008
msgid "No updates available for this image."
msgstr "このイメージで使用可能な更新は存在しません。"

#: ../client.py:559
#, python-format
msgid ""
"image-update failed (inventory exception):\n"
"%s"
msgstr ""
"image-update が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:527
msgid ""
"WARNING: pkg(5) appears to be out of date, and should be updated before\n"
"running image-update.\n"
msgstr ""
"警告: pkg(5) が古いようなので、image-update を実行する前に\n"
"これを更新すべきです。\n"

#: ../client.py:529
msgid ""
"Please update pkg(5) using 'pfexec pkg install SUNWipkg' and then retry\n"
"the image-update."
msgstr ""
"「pfexec pkg install SUNWipkg」を使って pkg(5) を更新したあとで、\n"
"image-update を再試行してください。"

#: ../client.py:552
msgid ""
"\n"
"An unexpected error happened while preparing for image-update:"
msgstr ""
"\n"
"image-update の準備中に予期しないエラーが発生しました:"

#: ../client.py:559
#, python-format
msgid "image-update failed: %s"
msgstr "image-update が失敗しました: %s"

#: ../client.py:562
msgid "image-update cannot be done on live image"
msgstr "ライブイメージに image-update を実行することはできません"

#: ../client.py:573
#, python-format
msgid ""
"\n"
"An unexpected error happened during image-update: %s"
msgstr ""
"\n"
"image-update の実行中に予期しないエラーが発生しました: %s"

#: ../client.py:579
msgid ""
"NOTE: Please review release notes posted at:\n"
"   http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"注: 次の場所で公開されているリリースノートを確認してください:\n"
"   http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../client.py:612
msgid "install: at least one package name required"
msgstr "install: パッケージ名を少なくとも 1 つ指定する必要があります"

#: ../client.py:615
msgid "install: -v and -q may not be combined"
msgstr "install: -v と -q を組み合わせることはできません"

#: ../client.py:630 ../client.py:731 ../client.py:1346 ../updatemanager.py:746
#, python-format
msgid "'%s' is not an install image"
msgstr "'%s' はインストールイメージではありません"

#: ../client.py:636
msgid "Nothing to install in this image (is this package already installed?)"
msgstr "このイメージにはインストールするものが存在しません (このパッケージはすでにインストールされていますか?)"

#: ../client.py:646
#, python-format
msgid ""
"install failed (inventory exception):\n"
"%s"
msgstr ""
"install が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:669 ../client.py:766
msgid ""
"\n"
"An unexpected error happened while preparing for install:"
msgstr ""
"\n"
"install の準備中に予期しないエラーが発生しました:"

#: ../client.py:678
#, python-format
msgid "installation failed: %s"
msgstr "インストールが失敗しました: %s"

#: ../client.py:689
#, python-format
msgid "An unexpected error happened during installation: %s"
msgstr "インストール中に予期しないエラーが発生しました: %s"

#: ../client.py:713
msgid "uninstall: at least one package name required"
msgstr "uninstall: パッケージ名を少なくとも 1 つ指定する必要があります"

#: ../client.py:716
msgid "uninstall: -v and -q may not be combined"
msgstr "uninstall: -v と -q を組み合わせることはできません"

#: ../client.py:822
#, python-format
msgid ""
"uninstall failed (inventory exception):\n"
"%s"
msgstr ""
"uninstall が失敗しました (目録の例外):\n"
"%s"

#: ../client.py:775
#, python-format
msgid "uninstallation failed: %s"
msgstr "アンインストールが失敗しました: %s"

#: ../client.py:786
#, python-format
msgid "An unexpected error happened during uninstallation: %s"
msgstr "アンインストール中に予期しないエラーが発生しました: %s"

#: ../client.py:909
msgid "info: -l and -r may not be combined"
msgstr "info: -l と -r を組み合わせることはできません"

#: ../client.py:912
msgid "info: must request remote info for specific packages"
msgstr "info: 特定のパッケージではリモートの情報を要求する必要があります"

#: ../client.py:943
msgid "Installed"
msgstr "インストール済み"

#: ../client.py:945
msgid "Not installed"
msgstr "インストール済みでない"

#: ../client.py:969 ../client.py:1284
msgid ""
"pkg: no packages matching the following patterns you specified are\n"
"installed on the system.  Try specifying -r to query remotely:"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージの中で、\n"
"システムにインストール済みのものが存在しません。-r を指定して、リモートで照会を行なってください:"

#: ../client.py:973 ../client.py:1288
msgid ""
"pkg: no packages matching the following patterns you specified were\n"
"found in the catalog.  Try relaxing the patterns, refreshing, and/or\n"
"examining the catalogs:"
msgstr ""
"pkg: 指定された次のパターンに一致するパッケージが、カタログ内に見つか\n"
"りませんでした。パターンの条件緩和、再表示、カタログの検査のいずれか\n"
"、あるいはそのすべてを試してください:"

#: ../client.py:989
#, python-format
msgid "'%s' matches multiple packages"
msgstr "'%s' は複数のパッケージに一致します"

#: ../client.py:1146
msgid "contents: -l and -r may not be combined"
msgstr "contents: -l と -r を組み合わせることはできません"

#: ../client.py:1149
msgid "contents: must request remote contents for specific packages"
msgstr "contents: 特定のパッケージではリモートの内容を要求する必要があります"

#: ../client.py:1163
#, python-format
msgid "contents: -m and %s may not be specified at the same time"
msgstr "contents: -m と %s を同時に指定することはできません"

#: ../client.py:1168 ../client.py:1171
#, python-format
msgid "Invalid attribute '%s'"
msgstr "無効な属性 '%s'"

#: ../client.py:1229 ../client.py:1235 ../modules/client/api_errors.py:106
#, python-format
msgid "pkg: '%s' matches multiple packages"
msgstr "pkg: '%s' は複数のパッケージに一致します"

#: ../client.py:1303
#, python-format
msgid "pkg: %s/%s catalogs successfully updated:"
msgstr "pkg: %s/%s カタログの更新に成功しました:"

#: ../client.py:1352
#, python-format
msgid ""
"%s is not a recognized authority to refresh. \n"
"'pkg authority' will show a list of authorities."
msgstr ""
"%s は再表示するために認識されたオーソリティーではありません。\n"
"「pkg authority」を実行するとオーソリティーの一覧が表示されます。"

#: ../client.py:1402
msgid "pkg: set-authority: one and only one authority may be set"
msgstr "pkg: set-authority: 設定できるオーソリティーは 1 つだけです"

#: ../client.py:1402
msgid "set-authority: one and only one authority may be set"
msgstr "set-authority: 設定できるオーソリティーは 1 つだけです"

#: ../client.py:1410
#, python-format
msgid "set-authority: SSL key file '%s' does not exist"
msgstr "set-authority: SSL キーのファイル '%s' が存在しません"

#: ../client.py:1417
#, python-format
msgid "set-authority: SSL key cert '%s' does not exist"
msgstr "set-authority: SSL キーの証明書 '%s' が存在しません"

#: ../client.py:1423
msgid ""
"set-authority: authority does not exist. Use -O to define origin URL for new "
"authority"
msgstr ""
"set-authority: オーソリティーが存在しません。-O を使って新しいオーソリティーの元となる URL を"
"定義してください"

#: ../client.py:1428
msgid "set-authority: authority name has invalid characters"
msgstr "set-authority: オーソリティー名に無効な文字が含まれています"

#: ../client.py:1432
msgid "set-authority: authority URL is invalid"
msgstr "set-authority: オーソリティーの URL が無効です"

#: ../client.py:1444
#, python-format
msgid "set-authority failed: %s"
msgstr "set-authority が失敗しました: %s"

#: ../client.py:1454
msgid "set-authority: added mirror's URL is invalid"
msgstr "set-authority: 追加されたミラーの URL が無効です"

#: ../client.py:1458
msgid "set-authority: mirror already exists"
msgstr "set-authority: ミラーがすでに存在しています"

#: ../client.py:1466
msgid "set-authority: removed mirror has bad URL"
msgstr "set-authority: 削除されたミラーの URL が不正です"

#: ../client.py:1470
msgid "set-authority: mirror does not exist"
msgstr "set-authority: ミラーが存在しません"

#: ../client.py:1492
#, python-format
msgid "unset-authority: no such authority: %s"
msgstr "unset-authority: そのようなオーソリティーは存在しません: %s"

#: ../client.py:1497
msgid "unset-authority: removal of preferred authority not allowed."
msgstr "unset-authority: 優先オーソリティーを削除することはできません。"

#: ../client.py:1540
#, python-format
msgid "authority: no such authority: %s"
msgstr "authority: そのようなオーソリティーは存在しません: %s"

#: ../client.py:1556
#, python-format
msgid "SSL certificate for %sis invalid or non-existent."
msgstr "%s の SSL 証明書が、無効であるか存在しません。"

#: ../client.py:1559
#, python-format
msgid "Please check file at %s"
msgstr "%s のファイルを確認してください"

#: ../client.py:1598
msgid "pkg: set-property: requires a property name and value"
msgstr "pkg: set-property: プロパティー名と値が必要です"

#: ../client.py:1598
msgid "set-property: requires a property name and value"
msgstr "set-property: プロパティー名と値が必要です"

#: ../client.py:1603
#, python-format
msgid "set-property failed: %s"
msgstr "set-property が失敗しました: %s"

#: ../client.py:1618
msgid "pkg: unset-property requires at least one property name"
msgstr "pkg: unset-property では、プロパティー名を少なくとも 1 つ指定する必要があります"

#: ../client.py:1618
msgid "unset-property: requires at least one property name"
msgstr "unset-property: プロパティー名を少なくとも 1 つ指定する必要があります"

#: ../client.py:1624
#, python-format
msgid "unset-property: no such property: %s"
msgstr "unset-property: そのようなプロパティーは存在しません: %s"

#: ../client.py:1640
#, python-format
msgid "property: no such property: %s"
msgstr "property: そのようなプロパティーは存在しません: %s"

#: ../client.py:1695 ../client.py:1720
msgid ""
"image-create requires authority argument to be of the form '<prefix>=<url>'."
msgstr ""
"image-create では、オーソリティーの引数が「<prefix>=<url>」の形式になっている必要があります。"

#: ../client.py:1700
msgid "image-create requires a single image directory path"
msgstr "image-create では、単一のイメージディレクトリパスを指定する必要があります"

#: ../client.py:1705
#, python-format
msgid "pkg: set-authority: SSL key file '%s' does not exist"
msgstr "pkg: set-authority: SSL キーのファイル '%s' が存在しません"

#: ../client.py:1712
#, python-format
msgid "pkg: set-authority: SSL key cert '%s' does not exist"
msgstr "pkg: set-authority: SSL キーの証明書 '%s' が存在しません"

#: ../client.py:1724
#, python-format
msgid "image-create requires that a prefix not match: %s"
msgstr "image-create では、接頭辞が一致しないことが要求されます: %s"

#: ../client.py:1729
msgid "image-create: authority prefix has invalid characters"
msgstr "image-create: オーソリティーの接頭辞に無効な文字が含まれています"

#: ../client.py:1734
msgid "image-create: authority URL is invalid"
msgstr "image-create: オーソリティーの URL が無効です"

#: ../client.py:1741
#, python-format
msgid "cannot create image at %s: %s"
msgstr "%s にイメージを作成できません: %s"

#: ../client.py:1764
#, python-format
msgid "rebuild-index: command does not take operands ('%s')"
msgstr "rebuild-index: コマンドはオペランドを取りません ('%s')"

#: ../client.py:1797
msgid "history: -H and -l may not be combined"
msgstr "history: -H と -l を組み合わせることはできません"

#: ../client.py:1801
msgid "TIME"
msgstr "時間"

#: ../client.py:1802
msgid "OPERATION"
msgstr "操作"

#: ../client.py:1802
msgid "CLIENT"
msgstr "クライアント"

#: ../client.py:1802
msgid "OUTCOME"
msgstr "結果"

#: ../client.py:1879
#, python-format
msgid "illegal global option -- %s"
msgstr "不正なグローバルオプション -- %s"

#: ../client.py:1899 ../client.py:2005
#, python-format
msgid "illegal %s option -- %s"
msgstr "不正な %s オプション -- %s"

#: ../client.py:1904
#, python-format
msgid "version: command does not take operands ('%s')"
msgstr "version: コマンドはオペランドを取りません ('%s')"

#: ../client.py:1938
msgid ""
"Could not find image.  Use the -R option or set $PKG_IMAGE to point\n"
"to an image, or change the working directory to one inside the image."
msgstr ""
"イメージが見つかりませんでした。-R オプションを使用するか $PKG_IMAGE を設定してイメージの場所を指定するか、\n"
"あるいは作業ディレクトリをイメージの内側に変更してください。"

#: ../client.py:1952
msgid "No image found."
msgstr "イメージが見つかりません。"

#: ../client.py:1997
msgid "History purged."
msgstr "履歴が削除されます。"

#: ../client.py:2002
#, python-format
msgid "unknown subcommand '%s'"
msgstr "不明なサブコマンド '%s'"

#: ../client.py:2028
#, python-format
msgid ""
"\n"
"Maximum (%d) network retries exceeded during download. Details follow:\n"
"%s"
msgstr ""
"\n"
"ダウンロード中にネットワーク再試行の最大回数 (%d) を超えました。詳細は次のとおりです:\n"
"%s"

#: ../client.py:2036
msgid ""
"An error was encountered while attempting to retrieve package or file data "
"for the requested operation."
msgstr ""
"要求された操作に対するパッケージまたはファイルデータの取得を"
"試行しているときに、エラーが発生しました。"

#: ../client.py:2045
msgid ""
"An error was encountered while attempting to load history information\n"
"about past client operations."
msgstr ""
"以前のクライアント操作に関する履歴情報の読み込みを試行しているときに、\n"
"エラーが発生しました。"

#: ../client.py:2054
msgid ""
"An error was encountered while attempting to store information about the\n"
"current operation in client history."
msgstr ""
"現在の操作に関する情報をクライアント履歴に格納しようとしたときに、\n"
"エラーが発生しました。"

#: ../client.py:2064
msgid "An error was encountered while attempting to purge client history."
msgstr "クライアント履歴の削除を試行しているときに、エラーが発生しました。"

#: ../client.py:2073
#, python-format
msgid ""
"\n"
"\n"
"This is an internal error.  Please let the developers know about this\n"
"problem by filing a bug athttp://defect.opensolaris.org and including the\n"
"abovetraceback and this message.  The version of pkg(5) is '%s'."
msgstr ""
"\n"
"\n"
"これは内部エラーです。この問題を開発者に知らせるために、\n"
"http://defect.opensolaris.org でバグ情報を入力し、上記のトレースバック\n"
"とこのメッセージを含めてください。pkg(5) のバージョンは '%s' です。"

#: ../gui/data/l10n.py:6
msgid "Communication"
msgstr "通信"

#: ../gui/data/l10n.py:7
msgid "Mail"
msgstr "メール"

#: ../gui/data/l10n.py:8
msgid "Localization"
msgstr "言語単位"

#: ../gui/data/l10n.py:9
msgid "Social Software"
msgstr "ソーシャルソフトウェア"

#: ../gui/data/l10n.py:10
msgid "Viewer"
msgstr "ビューア"

#: ../gui/data/l10n.py:11
msgid "RasterGraphics"
msgstr "ラスターグラフィックス"

#: ../gui/data/l10n.py:12
msgid "2DGraphics"
msgstr "2D グラフィックス"

#: ../gui/data/l10n.py:13
msgid "Photography"
msgstr "写真"

#: ../gui/data/l10n.py:14
msgid "CLI tools"
msgstr "CLI ツール"

#: ../gui/data/l10n.py:15
msgid "Print"
msgstr "印刷"

#: ../gui/data/packagemanager.desktop.in.h:1
msgid "Install, update and remove software packages"
msgstr "ソフトウエアパッケージをインストール、更新または削除します"

#: ../gui/data/packagemanager.desktop.in.h:2
#: ../gui/data/packagemanager.glade.h:67 ../packagemanager.py:102
msgid "Package Manager"
msgstr "パッケージマネージャー"

#: ../gui/data/packagemanager.glade.h:1
msgid "\n"
msgstr "\n"

#: ../gui/data/packagemanager.glade.h:3
msgid ""
"- Delete old Boot Environments to free up disk space.\n"
"- Set the Active BE for next reboot."
msgstr ""
"- 古いブート環境を削除してディスク領域を解放します。\n"
"- 次回リブート時のアクティブ BE を設定します。"

#: ../gui/data/packagemanager.glade.h:5
msgid ""
"6 packages will be installed\n"
"28 packages will be updated\n"
"\n"
"20.1 MB will be downloaded"
msgstr ""
"6 パッケージがインストールされます\n"
"28 パッケージが更新されます\n"
"\n"
"20.1M バイトがダウンロードされます"

#: ../gui/data/packagemanager.glade.h:9
msgid "<b>Active Boot Environment changed to:</b>"
msgstr "<b>変更後のアクティブブート環境:</b>"

#: ../gui/data/packagemanager.glade.h:10
msgid "<b>Boot Environments to be deleted:</b>"
msgstr "<b>削除するブート環境:</b>"

#: ../gui/data/packagemanager.glade.h:11
msgid "<b>Can't establish a connection to the repository</b>"
msgstr "<b>リポジトリへの接続を確立できません</b>"

#: ../gui/data/packagemanager.glade.h:12
msgid "<b>Edit Repositories</b>"
msgstr "<b>リポジトリの編集</b>"

#: ../gui/data/packagemanager.glade.h:13
msgid "<b>Manage Your Boot Environments</b>"
msgstr "<b>ブート環境の管理</b>"

#: ../gui/data/packagemanager.glade.h:14
msgid "<b>Modify Repository</b>"
msgstr "<b>リポジトリの変更</b>"

#: ../gui/data/packagemanager.glade.h:15
msgid "<b>PACKAGE NAME</b>"
msgstr "<b>パッケージ名</b>"

#: ../gui/data/packagemanager.glade.h:16
msgid "<b>Summary</b>"
msgstr "<b>概要</b>"

#: ../gui/data/packagemanager.glade.h:17
msgid "<i>Repository:</i>"
msgstr "<i>リポジトリ:</i>"

#: ../gui/data/packagemanager.glade.h:18
msgid "About"
msgstr "バージョン情報"

#: ../gui/data/packagemanager.glade.h:19
msgid "About Glade"
msgstr "グレードについて"

#: ../gui/data/packagemanager.glade.h:20
msgid "Architecture (CPU):"
msgstr "アーキテクチャ (CPU):"

#: ../gui/data/packagemanager.glade.h:21
msgid "BE Management Changes Confirmation"
msgstr "BE 管理変更の確認"

#: ../gui/data/packagemanager.glade.h:22
msgid "Boot Environment Management"
msgstr "ブート環境の管理"

#: ../gui/data/packagemanager.glade.h:23
msgid "Build type:"
msgstr "ビルドタイプ:"

#: ../gui/data/packagemanager.glade.h:24
msgid "By managing Boot Environments you may:"
msgstr "ブート環境を管理することで次のことが行えます:"

#: ../gui/data/packagemanager.glade.h:25
msgid "Cancel"
msgstr "キャンセル"

#: ../gui/data/packagemanager.glade.h:26 ../um/data/updatemanager.glade.h:11
msgid "Checking for latest SUNWipkg and SUNWipkg-gui, please wait..."
msgstr "最新の SUNWipkg と SUNWipkg-gui をチェックしています。しばらくお待ちください..."

#: ../gui/data/packagemanager.glade.h:27 ../gui/modules/installupdate.py:188
msgid "Checking package dependencies..."
msgstr "パッケージの依存関係をチェック中..."

#: ../gui/data/packagemanager.glade.h:28
msgid "Clear"
msgstr "クリア"

#: ../gui/data/packagemanager.glade.h:29 ../gui/modules/installupdate.py:590
msgid "Close"
msgstr "閉じる"

#: ../gui/data/packagemanager.glade.h:30
msgid "Copy"
msgstr "コピー"

#: ../gui/data/packagemanager.glade.h:31
msgid ""
"Copyright 2008 Sun Microsystems, Inc.  \n"
"All rights reserved.\n"
"Use is subject to license terms."
msgstr ""
"Copyright 2008 Sun Microsystems, Inc.  \n"
"All rights reserved.\n"
"使用はライセンス契約条件に従うものとします。"

#: ../gui/data/packagemanager.glade.h:34
msgid "Currently Active Boot Environment"
msgstr "現在アクティブになっているブート環境"

#: ../gui/data/packagemanager.glade.h:35
msgid "Custom Package Options"
msgstr "カスタムパッケージのオプション"

#: ../gui/data/packagemanager.glade.h:36
msgid "Cut"
msgstr "カット"

#: ../gui/data/packagemanager.glade.h:37
msgid "Cut action"
msgstr "アクションのカット"

#: ../gui/data/packagemanager.glade.h:38
msgid "Debug"
msgstr "デバッグ"

#: ../gui/data/packagemanager.glade.h:39
msgid "Dependencies"
msgstr "依存関係"

#: ../gui/data/packagemanager.glade.h:40
msgid "Deselect"
msgstr "選択解除"

#: ../gui/data/packagemanager.glade.h:41
msgid "Deselect selected packages"
msgstr "選択したパッケージを選択解除します"

#: ../gui/data/packagemanager.glade.h:42
msgid "Downloading Packages"
msgstr "パッケージのダウンロード中"

#: ../gui/data/packagemanager.glade.h:43
msgid "Downloading files..."
msgstr "ファイルのダウンロード中..."

#: ../gui/data/packagemanager.glade.h:44
msgid "Edit Repositories"
msgstr "リポジトリの編集"

#: ../gui/data/packagemanager.glade.h:45
msgid "Edit Repositories..."
msgstr "リポジトリの編集..."

#: ../gui/data/packagemanager.glade.h:46
msgid ""
"Enter the repository name and URL you want to add as a new package source. \n"
"Select from the list to modify or remove existing repositories."
msgstr ""
"新しいパッケージソースとして追加するリポジトリの名前と URL を入力してください。\n"
"既存のリポジトリを変更または削除する場合は、リストから選択してください。"

#: ../gui/data/packagemanager.glade.h:48
msgid "Files Details"
msgstr "ファイルの詳細"

#: ../gui/data/packagemanager.glade.h:49
msgid "General Info"
msgstr "一般情報"

#: ../gui/data/packagemanager.glade.h:50
msgid ""
"In some cases, when Update action is performed, a new Boot Environment is "
"created."
msgstr ""
"場合によっては、更新アクションの実行時に新しいブート環境が"
"作成されます。"

#: ../gui/data/packagemanager.glade.h:51
msgid "Install / Update"
msgstr "インストール/更新"

#: ../gui/data/packagemanager.glade.h:52
msgid "Install / Update Confirmation"
msgstr "インストール/更新の確認"

#: ../gui/data/packagemanager.glade.h:53
msgid "Install or Update selected packages"
msgstr "選択したパッケージをインストールまたは更新します"

#: ../gui/data/packagemanager.glade.h:54
msgid "Install/Update"
msgstr "インストール/更新"

#: ../gui/data/packagemanager.glade.h:55
msgid "Install/Upgrade Check"
msgstr "インストール/更新のチェック"

#: ../gui/data/packagemanager.glade.h:56
msgid "Installing Packages"
msgstr "パッケージのインストール中"

#: ../gui/data/packagemanager.glade.h:57 ../gui/modules/installupdate.py:456
msgid "Installing Packages..."
msgstr "パッケージのインストール中..."

#: ../gui/data/packagemanager.glade.h:58 ../packagemanager.py:1014
msgid "Licenses"
msgstr "ライセンス"

#: ../gui/data/packagemanager.glade.h:59
msgid "Modify Repository"
msgstr "リポジトリの変更"

#: ../gui/data/packagemanager.glade.h:60
msgid "Network Problem"
msgstr "ネットワークの問題"

#: ../gui/data/packagemanager.glade.h:61
msgid "Next"
msgstr "次へ"

#: ../gui/data/packagemanager.glade.h:62
msgid "Non-Debug"
msgstr "デバッグなし"

#: ../gui/data/packagemanager.glade.h:63
msgid "OK"
msgstr "了解"

#: ../gui/data/packagemanager.glade.h:64
msgid "Ok"
msgstr "了解"

#: ../gui/data/packagemanager.glade.h:65
msgid "Online Help"
msgstr "オンラインヘルプ"

#: ../gui/data/packagemanager.glade.h:66
msgid "Package Download Preferences"
msgstr "パッケージダウンロードの設定"

#: ../gui/data/packagemanager.glade.h:68
msgid "Paste"
msgstr "ペースト"

#: ../gui/data/packagemanager.glade.h:69
msgid "Please check your Internet settings."
msgstr "インターネット設定をチェックしてください。"

#: ../gui/data/packagemanager.glade.h:70 ../um/data/updatemanager.glade.h:16
msgid "Processing"
msgstr "処理中"

#: ../gui/data/packagemanager.glade.h:71
msgid "Quit"
msgstr "終了"

#: ../gui/data/packagemanager.glade.h:72
msgid "Quit application"
msgstr "アプリケーションを終了します"

#: ../gui/data/packagemanager.glade.h:73
msgid "Reload"
msgstr "再読み込み"

#: ../gui/data/packagemanager.glade.h:74
msgid "Remove"
msgstr "削除"

#: ../gui/data/packagemanager.glade.h:75 ../gui/modules/installupdate.py:146
msgid "Remove Check"
msgstr "チェックの削除"

#: ../gui/data/packagemanager.glade.h:76 ../gui/modules/installupdate.py:138
#: ../gui/modules/installupdate.py:584
msgid "Remove Confirmation"
msgstr "確認の削除"

#: ../gui/data/packagemanager.glade.h:77
msgid "Remove selected packages"
msgstr "選択したパッケージを削除します"

#: ../gui/data/packagemanager.glade.h:78 ../gui/modules/installupdate.py:144
msgid "Removing Packages"
msgstr "パッケージを削除中"

#: ../gui/data/packagemanager.glade.h:79 ../gui/modules/installupdate.py:148
msgid "Removing Packages..."
msgstr "パッケージを削除中..."

#: ../gui/data/packagemanager.glade.h:80
msgid "Reset"
msgstr "リセット"

#: ../gui/data/packagemanager.glade.h:81
msgid ""
"Review the Boot Environments to change\n"
"Click OK to proceed"
msgstr ""
"変更するブート環境を確認してください\n"
"処理を続行する場合は「了解」をクリックしてください"

#: ../gui/data/packagemanager.glade.h:83
msgid "SPARC"
msgstr "SPARC"

#: ../gui/data/packagemanager.glade.h:84
msgid "Search:"
msgstr "検索:"

#: ../gui/data/packagemanager.glade.h:85
msgid "Select All"
msgstr "すべて選択"

#: ../gui/data/packagemanager.glade.h:86
msgid "Select All Items"
msgstr "すべての項目を選択"

#: ../gui/data/packagemanager.glade.h:87
msgid "Select Updates"
msgstr "更新を選択"

#: ../gui/data/packagemanager.glade.h:88
msgid ""
"Select default download preferences for all packages.\n"
"Click Reset to reset download preferences to the initial settings."
msgstr ""
"すべてのパッケージ用にデフォルトのダウンロード設定を選択します。\n"
"ダウンロード設定を初期設定に戻すには「リセット」をクリックします。"

#: ../gui/data/packagemanager.glade.h:90
msgid "Short description"
msgstr "簡単な説明"

#: ../gui/data/packagemanager.glade.h:91
msgid "Show Details"
msgstr "詳細を表示"

#: ../gui/data/packagemanager.glade.h:92
msgid "Show:"
msgstr "表示:"

#: ../gui/data/packagemanager.glade.h:93
msgid ""
"This action affects other packages.\n"
"Review the packages to be installed or updated.\n"
"Click Next to continue."
msgstr ""
"このアクションは他のパッケージに影響を与えます。\n"
"インストールまたは更新されるパッケージを確認します。\n"
"続行するには「次へ」をクリックします。"

#: ../gui/data/packagemanager.glade.h:96
msgid ""
"This action affects other packages.\n"
"Review the packages to be removed.\n"
"Click Next to continue."
msgstr ""
"このアクションは他のパッケージに影響を与えます。\n"
"削除されるパッケージを確認します。\n"
"続行するには「次へ」をクリックします。"

#. Load the catalogs from the repository, its a long
#. running tasks so need a progress dialog
#: ../gui/data/packagemanager.glade.h:99 ../packagemanager.py:178
#: ../packagemanager.py:726 ../packagemanager.py:749 ../packagemanager.py:765
#: ../packagemanager.py:1981 ../packagemanager.py:1995
#: ../um/data/updatemanager.glade.h:17 ../updatemanager.py:928
#: ../updatemanager.py:1045 ../updatemanager.py:1222
msgid "Update All"
msgstr "すべて更新"

#: ../gui/data/packagemanager.glade.h:100
msgid "Update all packages"
msgstr "すべてのパッケージを更新します"

#: ../gui/data/packagemanager.glade.h:101
msgid "X86"
msgstr "X86"

#: ../gui/data/packagemanager.glade.h:102
msgid "_Add"
msgstr "追加(_A)"

#: ../gui/data/packagemanager.glade.h:103 ../um/data/updatemanager.glade.h:21
msgid "_Cancel"
msgstr "キャンセル(_C)"

#: ../gui/data/packagemanager.glade.h:104
msgid "_Close"
msgstr "閉じる(_C)"

#: ../gui/data/packagemanager.glade.h:105
msgid "_Edit"
msgstr "編集(_E)"

#: ../gui/data/packagemanager.glade.h:106
msgid "_File"
msgstr "ファイル(_F)"

#: ../gui/data/packagemanager.glade.h:107
msgid "_Help"
msgstr "ヘルプ(_H)"

#: ../gui/data/packagemanager.glade.h:108
msgid "_Modify..."
msgstr "変更(_M)..."

#: ../gui/data/packagemanager.glade.h:109
msgid "_Name: "
msgstr "名前(_N): "

#: ../gui/data/packagemanager.glade.h:110 ../um/data/updatemanager.glade.h:23
msgid "_OK"
msgstr "了解(_O)"

#: ../gui/data/packagemanager.glade.h:111
msgid "_Package"
msgstr "パッケージ(_P)"

#: ../gui/data/packagemanager.glade.h:112
msgid "_Remove"
msgstr "削除(_R)"

#: ../gui/data/packagemanager.glade.h:113
msgid "_Settings"
msgstr "設定(_S)"

#: ../gui/data/packagemanager.glade.h:114
msgid "_URL: "
msgstr "URL(_U): "

#: ../gui/modules/beadmin.py:69
msgid "The <b>libbe</b> library was not "
msgstr "<b>libbe</b> ライブラリは"

#: ../gui/modules/beadmin.py:77
msgid "BE management"
msgstr "BE 管理"

#: ../gui/modules/beadmin.py:150
#, python-format
msgid ""
"GUI will not respond to any event! %s.                             Check "
"beadmin.py signals"
msgstr ""
"GUI はどのイベントにも応答しません。%s。                             "
"beadmin.py のシグナルをチェックしてください"

#: ../gui/modules/beadmin.py:162
msgid "Loading Boot Environment Information"
msgstr "ブート環境情報の読み込み"

#: ../gui/modules/beadmin.py:164
msgid "Fetching BE entries..."
msgstr "BE エントリを取得しています..."

#: ../gui/modules/beadmin.py:192
msgid "Boot Environment"
msgstr "ブート環境"

#: ../gui/modules/beadmin.py:200
msgid "Created"
msgstr "作成済み"

#: ../gui/modules/beadmin.py:209
msgid "Size"
msgstr "サイズ"

#: ../gui/modules/beadmin.py:217
msgid "Active on Reboot"
msgstr "リブート時にアクティブ化"

#: ../gui/modules/beadmin.py:228
msgid "Delete"
msgstr "削除"

#: ../gui/modules/beadmin.py:245 ../gui/modules/repository.py:286
#: ../gui/modules/repository.py:302 ../gui/modules/repository.py:332
msgid "Applying changes"
msgstr "変更を適用する"

#: ../gui/modules/beadmin.py:247 ../gui/modules/repository.py:287
#: ../gui/modules/repository.py:303 ../gui/modules/repository.py:333
msgid "Applying changes, please wait ..."
msgstr "変更を適用しています。しばらくお待ちください..."

#: ../gui/modules/beadmin.py:287
msgid "No change"
msgstr "変更なし"

#: ../gui/modules/beadmin.py:291
#, python-format
msgid "%d BE's will be deleted"
msgstr "%d 個の BE が削除されます"

#: ../gui/modules/beadmin.py:299
msgid "The Active BE will be changed upon reboot"
msgstr "リブート時にアクティブ BE が変更されます"

#: ../gui/modules/beadmin.py:303
msgid "No change\n"
msgstr "変更なし\n"

#: ../gui/modules/beadmin.py:339
msgid "<b>Couldn't change Active "
msgstr "<b>アクティブ BE を変更できませんでした"

#: ../gui/modules/beadmin.py:344
msgid "<b>Couldn't delete Boot "
msgstr "<b>ブート環境を削除できませんでした"

#: ../gui/modules/beadmin.py:410
msgid "The <b>libbe</b> library couldn't  "
msgstr "<b>libbe</b> ライブラリは"

#: ../gui/modules/beadmin.py:434
msgid "%a %b %d %H:%M %Y"
msgstr "%Y 年 %m 月 %d 日(%a) %H:%M"

#: ../gui/modules/beadmin.py:441 ../gui/modules/beadmin.py:451
msgid "%m/%d/%y %H:%M"
msgstr "%Y 年 %m 月 %d 日 %H:%M"

#: ../gui/modules/installupdate.py:72
msgid "The version of the API is not correct.\n"
msgstr "API のバージョンが正しくありません。\n"

#: ../gui/modules/installupdate.py:77
msgid "The image was not found."
msgstr "イメージが見つかりませんでした。"

#: ../gui/modules/installupdate.py:140
msgid "This action affects other packages.\n"
msgstr "このアクションはほかのパッケージに影響を与えます。\n"

#: ../gui/modules/installupdate.py:177
#, python-format
msgid ""
"GUI will not respond to any event! %s.                             Check "
"installupdate.py signals"
msgstr ""
"GUI はどのイベントにも応答しません。%s。                             "
"installupdate.py のシグナルをチェックしてください"

#: ../gui/modules/installupdate.py:198 ../gui/modules/installupdate.py:223
msgid "Canceling..."
msgstr "キャンセル中..."

#: ../gui/modules/installupdate.py:282
msgid "Evaluation started.\n"
msgstr "評価が開始されました。\n"

#: ../gui/modules/installupdate.py:292
msgid "Invalid repository certificate."
msgstr "無効なリポジトリ証明書。"

#: ../gui/modules/installupdate.py:309
msgid "Install failed.\n"
msgstr "インストールが失敗しました。\n"

#: ../gui/modules/installupdate.py:321 ../gui/modules/installupdate.py:394
msgid "Please check the network "
msgstr "ネットワークを確認してください"

#: ../gui/modules/installupdate.py:416
msgid "Preparing to download packages, please wait..."
msgstr "パッケージのダウンロード準備中です。しばらくお待ちください..."

#: ../gui/modules/installupdate.py:464 ../gui/modules/installupdate.py:478
#: ../gui/modules/installupdate.py:491
msgid "There was an error during installation."
msgstr "インストール中にエラーが発生しました。"

#: ../gui/modules/installupdate.py:545
#, python-format
msgid "Evaluating: %s\n"
msgstr "評価中: %s\n"

#: ../gui/modules/installupdate.py:559
#, python-format
msgid "%d packages will be updated\n"
msgstr "%d パッケージが更新されます\n"

#: ../gui/modules/installupdate.py:562
#, python-format
msgid "%d package will be updated\n"
msgstr "%d パッケージが更新されます\n"

#: ../gui/modules/installupdate.py:565
#, python-format
msgid ""
"%d packages will be installed\n"
"\n"
msgstr ""
"%d パッケージがインストールされます\n"
"\n"

#: ../gui/modules/installupdate.py:568
#, python-format
msgid ""
"%d package will be installed\n"
"\n"
msgstr ""
"%d パッケージがインストールされます\n"
"\n"

#: ../gui/modules/installupdate.py:571
#, python-format
msgid ""
"%d packages will be removed\n"
"\n"
msgstr ""
"%d パッケージが削除されます\n"
"\n"

#: ../gui/modules/installupdate.py:574
#, python-format
msgid ""
"%d package will be removed\n"
"\n"
msgstr ""
"%d パッケージが削除されます\n"
"\n"

#: ../gui/modules/installupdate.py:579
#, python-format
msgid "%s will be downloaded"
msgstr "%s がダウンロードされます"

#: ../gui/modules/installupdate.py:586
msgid "This action couldn't be finished.\n"
msgstr "このアクションを終了できませんでした。\n"

#: ../gui/modules/installupdate.py:598
msgid "None of the packages will be removed"
msgstr "パッケージは 1 つも削除されません"

#: ../gui/modules/installupdate.py:678
msgid "Downloading: "
msgstr "ダウンロード中: "

#: ../gui/modules/installupdate.py:701
msgid "Creating packages index..."
msgstr "パッケージのインデックスを作成しています..."

#: ../gui/modules/repository.py:137
#, python-format
msgid ""
"GUI will not respond to any event! %s.                             Check "
"repository.py signals"
msgstr ""
"GUI はどのイベントにも応答しません。%s。                             "
"repository.py のシグナルをチェックしてください"

#: ../gui/modules/repository.py:150
msgid "Repository Name"
msgstr "リポジトリ名"

#: ../gui/modules/repository.py:155
msgid "Preferred"
msgstr "優先"

#: ../gui/modules/repository.py:223
msgid "Couldn't change"
msgstr "変更できませんでした"

#: ../gui/modules/repository.py:377 ../gui/modules/repository.py:391
#, python-format
msgid "Failed to modify %s."
msgstr "%s の変更に失敗しました。"

#: ../gui/modules/repository.py:419
#, python-format
msgid ""
"Invalid URL:\n"
"%s"
msgstr ""
"無効な URL:\n"
"%s"

#: ../gui/modules/repository.py:435 ../gui/modules/repository.py:448
#, python-format
msgid "Failed to add %s."
msgstr "%s の追加に失敗しました。"

#: ../gui/modules/repository.py:469
#, python-format
msgid "Failed to delete %s."
msgstr "%s の削除に失敗しました。"

#: ../modules/client/api_errors.py:100
#, python-format
msgid ""
"        pkg: no package matching '%s' could be found in current catalog\n"
"        suggest relaxing pattern, refreshing and/or examining catalogs"
msgstr ""
"        pkg: '%s' に一致するパッケージが現在のカタログ内で見つかりませんでした\n"
"        パターンの条件緩和、再表示、カタログの検査のいずれか、またはそのすべてを実行することをお勧めします"

#: ../modules/client/bootenv.py:130
msgid "pkg: unable to create an auto snapshot. pkg recovery is disabled."
msgstr "pkg: 自動スナップショットを作成できません。pkg の復元が無効になっています。"

#: ../modules/client/bootenv.py:165 ../modules/client/bootenv.py:308
#, python-format
msgid "pkg: unable to create BE %s"
msgstr "pkg: BE %s を作成できません"

#: ../modules/client/bootenv.py:170
#, python-format
msgid "pkg: attempt to mount %s failed."
msgstr "pkg: %s のマウントの試行が失敗しました。"

#: ../modules/client/bootenv.py:195
#, python-format
msgid "pkg: A system error %s was caught executing %s"
msgstr "pkg: システムエラー %s が %s の実行中に検出されました"

#: ../modules/client/bootenv.py:195
#, python-format
msgid "pkg: A system error %(e)s was caught executing %(join_cmd)s"
msgstr "pkg: システムエラー %(e)s が %(join_cmd)s の実行中に検出されました"

#: ../modules/client/bootenv.py:199
#, python-format
msgid ""
"pkg: '%s' failed. \n"
"with a return code of %d."
msgstr ""
"pkg: '%s' が失敗しました。\n"
"リターンコードは %d です。"

#: ../modules/client/bootenv.py:204
#, python-format
msgid "pkg: unable to activate %s"
msgstr "pkg: %s をアクティブにすることができません"

#: ../modules/client/bootenv.py:209
#, python-format
msgid "pkg: unable to unmount %s"
msgstr "pkg: %s をマウント解除できません"

#: ../modules/client/bootenv.py:215
#, python-format
msgid ""
"A clone of %s exists and has been updated and activated. On next boot the "
"Boot Environment %s will be mounted on '/'. Reboot when ready to switch to "
"this updated BE."
msgstr ""
"%s のクローンが存在しており、それが更新およびアクティブ化されました。"
"次回リブート時にはブート環境 %s が「/」にマウントされます。"
"準備が整ったらリブートしてこの更新済みの BE に切り替えてください。"

#: ../modules/client/bootenv.py:232
#, python-format
msgid "pkg: The system error %s was caught executing %s"
msgstr "pkg: システムエラー %s が %s の実行中に検出されました"

#: ../modules/client/bootenv.py:232
#, python-format
msgid "pkg: The system error %(e)s was caught executing %(join_cmd)s"
msgstr "pkg: システムエラー %(e)s が %(join_cmd)s の実行中に検出されました"

#: ../modules/client/bootenv.py:236
#, python-format
msgid ""
"pkg: '%s' failed \n"
"with a return code of %d."
msgstr ""
"pkg: '%s' が失敗しました \n"
"リターンコードは %d です。"

#: ../modules/client/bootenv.py:240
#, python-format
msgid "%s has been updated successfully"
msgstr "%s の更新に成功しました"

#: ../modules/client/bootenv.py:253
#, python-format
msgid ""
" The running system has not been modified. Modifications were only made to a "
"clone of the running system.  This clone is mounted at %s should you wish to "
"inspect it."
msgstr ""
" 稼働中のシステムは変更されませんでした。変更が加えられたのは、"
"稼働中のシステムのクローンに対してだけです。このクローンは %s にマウント"
"されているので、必要に応じて調査を行なってください。"

#: ../modules/client/bootenv.py:261
#, python-format
msgid "pkg: unable to rollback BE %s and restore image"
msgstr "pkg: BE %s をロールバックしてイメージを復元できません"

#: ../modules/client/bootenv.py:267
#, python-format
msgid "%s failed to be updated. No changes have been made to %s."
msgstr "%s の更新に失敗しました。%s は変更されていません。"

#: ../modules/client/bootenv.py:279
#, python-format
msgid "pkg: unable to destroy snapshot %s"
msgstr "pkg: スナップショット %s を破棄できません"

#: ../modules/client/bootenv.py:313
#, python-format
msgid "pkg: unable to mount BE %s on %s"
msgstr "pkg: BE %s を %s にマウントできません"

#: ../modules/client/bootenv.py:317
#, python-format
msgid ""
"The Boot Environment %s failed to be updated. A snapshot was taken before "
"the failed attempt and is mounted here %s. Use 'beadm unmount %s' and then "
"'beadm activate %s' if you wish to boot to this BE."
msgstr ""
"ブート環境 %s の更新に失敗しました。失敗した試行を行う前に取られたスナップショットが"
"存在しており、それが %s にマウントされています。この BE にブートする場合は、"
"「beadm unmount %s」を使用してから「beadm activate %s」を使用してください。"

#: ../modules/client/bootenv.py:330
#, python-format
msgid ""
"The Boot Environment %s failed to be updated. A snapshot was taken before "
"the failed attempt and has been restored so no changes have been made to %s."
msgstr ""
"ブート環境 %s の更新に失敗しました。失敗した試行を行う前に取られた"
"スナップショットが復元されたため、%s は変更されていません。"

#: ../modules/client/image.py:475
#, python-format
msgid "Certificate for authority %s not found"
msgstr "オーソリティー %s の証明書が見つかりません"

#: ../modules/client/image.py:477
#, python-format
msgid "File was supposed to exist at  path %s"
msgstr "パス %s にファイルが存在しているはずでした"

#: ../modules/client/image.py:484
#, python-format
#msgid "Certificate for authority %s at %s has an invalid format."
#msgstr "%2$s にあるオーソリティー %1$s の証明書の形式が無効です。"

#: ../modules/client/image.py:518
#, python-format
msgid ""
"Certificate for authority %(pfx)s at %(ssl_cert)s has an invalid format."
msgstr ""
"%(ssl_cert)s にあるオーソリティー %(pfx)s の証明書の形式が無効です。"

#: ../modules/client/image.py:490
#, python-format
msgid "Certificate for authority %s has expired"
msgstr "オーソリティー %s の証明書の有効期限が切れています。"

#: ../modules/client/image.py:492
msgid "Please install a valid certificate"
msgstr "有効な証明書をインストールしてください"

#: ../modules/client/image.py:505
#, python-format
msgid "Certificate for authority %s is invalid"
msgstr "オーソリティー %s の証明書が無効です"

#: ../modules/client/image.py:507
msgid "Certificate effective date is in the future"
msgstr "証明書の実効日付が未来になっています"

#: ../modules/client/image.py:519
#, python-format
msgid "Certificate for authority %s will expire in %d days"
msgstr "オーソリティー %s の証明書の有効期限があと %d 日で切れます"

#: ../modules/client/image.py:2106 ../modules/client/image.py:2161
msgid "Before evaluation:"
msgstr "評価前:"

#: ../modules/client/image.py:2122 ../modules/client/image.py:2170
msgid "After evaluation:"
msgstr "評価後:"

#: ../modules/client/image.py:2224
msgid "SUNWipkg update check failed."
msgstr "SUNWipkg の更新チェックが失敗しました。"

#: ../modules/misc.py:384
msgid "B"
msgstr "バイト"

#: ../modules/misc.py:385
msgid "kB"
msgstr "K バイト"

#: ../modules/misc.py:386
msgid "MB"
msgstr "M バイト"

#: ../modules/misc.py:387
msgid "GB"
msgstr "G バイト"

#: ../modules/misc.py:388
msgid "TB"
msgstr "T バイト"

#: ../modules/misc.py:389
msgid "PB"
msgstr "P バイト"

#: ../modules/misc.py:390
msgid "EB"
msgstr "E バイト"

#: ../modules/server/catalog.py:227
#, python-format
msgid "ERROR building search database, rc: %s"
msgstr "検索データベースの構築時にエラーが発生しました、rc: %s"

#: ../packagemanager.py:181
msgid ""
"Checking SUNWipkg and SUNWipkg-gui versions\n"
"\n"
"Please wait ..."
msgstr ""
"SUNWipkg と SUNWipkg-gui のバージョンをチェックしています\n"
"\n"
"しばらくお待ちください..."

#: ../packagemanager.py:250
#, python-format
msgid "GUI will not respond to any event! %s."
msgstr "GUI はどのイベントにも応答しません。%s。"

#: ../packagemanager.py:338 ../packagemanager.py:390 ../updatemanager.py:620
msgid "Name"
msgstr "名前"

#: ../packagemanager.py:345
msgid "Status"
msgstr "状態"

#: ../packagemanager.py:356
msgid "Installed Version"
msgstr "インストール済みバージョン"

#: ../packagemanager.py:364 ../updatemanager.py:635
msgid "Latest Version"
msgstr "最新バージョン"

#: ../packagemanager.py:372
msgid "Rating"
msgstr "定格"

#: ../packagemanager.py:376
msgid "Description"
msgstr "説明"

#: ../packagemanager.py:465 ../packagemanager.py:1568
#: ../packagemanager.py:1577 ../packagemanager.py:2016
msgid "All"
msgstr "すべて"

#: ../packagemanager.py:467
msgid "Meta Packages"
msgstr "メタパッケージ"

#: ../packagemanager.py:468 ../packagemanager.py:2062
#: ../packagemanager.py:2064 ../packagemanager.py:2066
#: ../packagemanager.py:2068 ../packagemanager.py:2070
#: ../packagemanager.py:2072 ../packagemanager.py:2074
#: ../packagemanager.py:2076 ../packagemanager.py:2078
msgid "Applications Desktop"
msgstr "アプリケーションデスクトップ"

#: ../packagemanager.py:469
msgid "Applications Web-Based"
msgstr "アプリケーション Web ベース"

#: ../packagemanager.py:470 ../packagemanager.py:2080
#: ../packagemanager.py:2082 ../packagemanager.py:2084
#: ../packagemanager.py:2087
msgid "Operating System"
msgstr "オペレーティングシステム"

#: ../packagemanager.py:471
msgid "User Environment"
msgstr "ユーザーの環境"

#: ../packagemanager.py:472
msgid "Web Infrastructure"
msgstr "Web インフラストラクチャー"

#: ../packagemanager.py:475
msgid "All Packages"
msgstr "すべてのパッケージ"

#: ../packagemanager.py:477
msgid "Installed Packages"
msgstr "インストール済みパッケージ"

#: ../packagemanager.py:478
msgid "Updates"
msgstr "更新"

#: ../packagemanager.py:479
msgid "Non-installed Packages"
msgstr "インストールされていないパッケージ"

#. self.filter_list.append([self._('Locked Packages'), ])
#. self.filter_list.append(["", ])
#: ../packagemanager.py:483
msgid "Selected Packages"
msgstr "選択したパッケージ"

#: ../packagemanager.py:728
msgid "Checking SUNWipkg and SUNWipkg-gui versions\n"
msgstr "SUNWipkg と SUNWipkg-gui のバージョンをチェックしています\n"

#. Prompt user
#: ../packagemanager.py:745
msgid "Newer versions of SUNWipkg and "
msgstr "SUNWipkg と次のものの新しいバージョン"

#: ../packagemanager.py:762
msgid "Update All was not "
msgstr "「すべて更新」が次のものではありませんでした"

#: ../packagemanager.py:801
msgid "Refreshing catalogs"
msgstr "カタログの再表示中"

#: ../packagemanager.py:802
msgid "Refreshing catalogs..."
msgstr "カタログの再表示中..."

#: ../packagemanager.py:941
msgid "Fetching description..."
msgstr "説明を取得中..."

#: ../packagemanager.py:942 ../packagemanager.py:943 ../packagemanager.py:944
msgid "Fetching information..."
msgstr "情報を取得中..."

#: ../packagemanager.py:948
msgid "Description not available for this package..."
msgstr "このパッケージの説明がありません..."

#: ../packagemanager.py:950
msgid "Files Details not available for this package..."
msgstr "このパッケージのファイルの詳細がありません..."

#: ../packagemanager.py:952
msgid "Dependencies info not available for this package..."
msgstr "このパッケージの依存性の情報がありません..."

#: ../packagemanager.py:954
msgid "Information not available for this package..."
msgstr "このパッケージの情報がありません..."

#: ../packagemanager.py:957
#, python-format
msgid "Root: %s\n"
msgstr "ルート: %s\n"

#: ../packagemanager.py:958
msgid "Dependencies:\n"
msgstr "依存関係:\n"

#: ../packagemanager.py:961
msgid ""
"Information for installed package:\n"
"\n"
msgstr ""
"インストール済みパッケージの情報:\n"
"\n"

#: ../packagemanager.py:964
msgid ""
"Information for latest available package:\n"
"\n"
msgstr ""
"最新の利用可能なパッケージの情報:\n"
"\n"

#: ../packagemanager.py:976
msgid "depend"
msgstr "従属"

#: ../packagemanager.py:980
msgid "dir"
msgstr "ディレクトリ"

#: ../packagemanager.py:983
msgid "file"
msgstr "ファイル"

#: ../packagemanager.py:986
msgid "hardlink"
msgstr "ハードリンク"

#: ../packagemanager.py:989
msgid "link"
msgstr "リンク"

#: ../packagemanager.py:992
msgid "legacy"
msgstr "旧バージョン"

#: ../packagemanager.py:993
msgid "pkg"
msgstr "パッケージ"

#: ../packagemanager.py:995
msgid "desc"
msgstr "説明"

#: ../packagemanager.py:997
#, python-format
msgid "  Description:\t%s\n"
msgstr "  説明:\t%s\n"

#: ../packagemanager.py:1000
#, python-format
msgid "  Name:\t\t%s\n"
msgstr "  名前:\t\t%s\n"

#: ../packagemanager.py:1001
#, python-format
msgid "  FMRI:\t\t%s\n"
msgstr "  FMRI:\t\t%s\n"

#: ../packagemanager.py:1002
#, python-format
msgid "  Version:\t\t%s\n"
msgstr "  バージョン:\t\t%s\n"

#: ../packagemanager.py:1004
#, python-format
msgid "  Packaged:\t%s\n"
msgstr "  パッケージ化されました:\t%s\n"

#: ../packagemanager.py:1330
msgid " catalogs successfully updated:\n"
msgstr " カタログの更新に成功しました:\n"

#: ../packagemanager.py:1351
msgid "Unknown error"
msgstr "不明なエラー"

#: ../packagemanager.py:1368
#, python-format
msgid "%s is not a valid root image, return None"
msgstr "%s は有効なルートイメージではありません。None を返します"

#. Can't happen when all_known is true and no args,
#. but here for completeness.
#: ../packagemanager.py:1391
msgid "Error occured while getting list of packages"
msgstr "パッケージリストの取得中にエラーが発生しました"

#: ../packagemanager.py:1684
#, python-format
msgid "Processing package entries: %d of %d"
msgstr "パッケージエントリを処理しています: %d/%d"

#: ../packagemanager.py:1695
msgid "Packagemanager error"
msgstr "packagemanager エラー"

#: ../packagemanager.py:1802
msgid "Loading Repository Information"
msgstr "リポジトリ情報の読み込み中"

#: ../packagemanager.py:1804
msgid "Fetching package entries ..."
msgstr "パッケージエントリの取得中..."

#: ../packagemanager.py:1923
#, python-format
msgid "%d packages listed"
msgstr "%d パッケージがリストされました"

#: ../packagemanager.py:1924
#, python-format
msgid "%d installed"
msgstr "%d がインストールされました"

#: ../packagemanager.py:1925
#, python-format
msgid "%d selected"
msgstr "%d が選択されました"

#: ../packagemanager.py:1926
#, python-format
msgid "%d broken"
msgstr "%d が壊れています"

#. 2790: As IPS and IPS-GUI have been updated the IPS GUI must be shutdown
#. and restarted
#: ../packagemanager.py:1978
msgid "SUNWipkg and SUNWipkg-gui have been "
msgstr "SUNWipkg と SUNWipkg-gui が、"

#: ../packagemanager.py:1991
msgid "Update All has completed and Package "
msgstr "「すべて更新」が完了し、パッケージ"

#. self.__add_package_to_category(_("All"),None,None,None);
#. Category names until xdg is imported.
#. from xdg.DesktopEntry import *
#. entry = DesktopEntry ()
#. directory = '/usr/share/desktop-directories'
#. for root, dirs, files in os.walk (directory):
#. for name in files:
#. entry.parse (os.path.join (root, name))
#. self.__add_category_to_section (entry.getName (), #. self._('Applications Desktop'))
#: ../packagemanager.py:2034 ../packagemanager.py:2036
#: ../packagemanager.py:2061
msgid "Accessories"
msgstr "アクセサリ"

#: ../packagemanager.py:2038 ../packagemanager.py:2042
#: ../packagemanager.py:2046 ../packagemanager.py:2063
msgid "Games"
msgstr "ゲーム"

#: ../packagemanager.py:2040 ../packagemanager.py:2044
#: ../packagemanager.py:2048 ../packagemanager.py:2065
#: ../packagemanager.py:2081
msgid "Graphics"
msgstr "グラフィックス"

#: ../packagemanager.py:2067
msgid "Internet"
msgstr "インターネット"

#: ../packagemanager.py:2069 ../packagemanager.py:2088
msgid "Office"
msgstr "オフィス"

#: ../packagemanager.py:2071
msgid "Sound & Video"
msgstr "サウンドとビデオ"

#: ../packagemanager.py:2073
msgid "System Tools"
msgstr "システムツール"

#: ../packagemanager.py:2075
msgid "Universal Access"
msgstr "ユニバーサルアクセス"

#. Can be twice :)
#: ../packagemanager.py:2077 ../packagemanager.py:2086
msgid "Developer Tools"
msgstr "開発者ツール"

#: ../packagemanager.py:2079
msgid "Core"
msgstr "コア"

#: ../packagemanager.py:2083
msgid "Media"
msgstr "メディア"

#: ../packagemanager.py:2090
msgid "Office2"
msgstr "オフィス 2"

#: ../publish.py:56
msgid ""
"Usage:\n"
"        pkgsend [options] command [cmd_options] [operands]\n"
"\n"
"Packager subcommands:\n"
"        pkgsend open [-en] pkg_fmri\n"
"        pkgsend add action arguments \n"
"        pkgsend import [-T file_pattern] bundlefile ...\n"
"        pkgsend include [-d basedir] manifest ...\n"
"        pkgsend close [-A]\n"
"\n"
"        pkgsend rename src_fmri dest_fmri\n"
"\n"
"Options:\n"
"        -s repo_url     destination repository server URL prefix\n"
"\n"
"Environment:\n"
"        PKG_REPO"
msgstr ""
"使用方法:\n"
"        pkgsend [options] command [cmd_options] [operands]\n"
"\n"
"パッケージャーのサブコマンド:\n"
"        pkgsend open [-en] pkg_fmri\n"
"        pkgsend add action arguments \n"
"        pkgsend import [-T file_pattern] bundlefile ...\n"
"        pkgsend include [-d basedir] manifest ...\n"
"        pkgsend close [-A]\n"
"\n"
"        pkgsend rename src_fmri dest_fmri\n"
"\n"
"オプション:\n"
"        -s repo_url     destination repository server URL prefix\n"
"\n"
"環境:\n"
"        PKG_REPO"

#: ../publish.py:83
#, python-format
msgid "pkgsend: %s failed (status %s)%s"
msgstr "pkgsend: %s が失敗しました (状態 %s)%s"

#: ../publish.py:99
msgid "pkgsend: open requires one package name"
msgstr "pkgsend: open ではパッケージ名を 1 つ指定する必要があります"

#: ../publish.py:109
msgid "pkgsend: no transaction ID provided in response"
msgstr "pkgsend: 応答にトランザクション ID が指定されていません"

#: ../publish.py:135
msgid "No transaction ID specified"
msgstr "トランザクション ID が指定されていません"

#: ../publish.py:155 ../publish.py:197 ../publish.py:248
msgid "No transaction ID specified in $PKG_TRANS_ID"
msgstr "$PKG_TRANS_ID にトランザクション ID が指定されていません"

#: ../publish.py:306
#, python-format
msgid "pkgsend: illegal global option -- %s"
msgstr "pkgsend: 不正なグローバルオプション -- %s"

#: ../publish.py:332
#, python-format
msgid "pkgsend: unknown subcommand '%s'"
msgstr "pkgsend: 不明なサブコマンド '%s'"

#: ../publish.py:336
#, python-format
msgid "pkgsend: illegal %s option -- %s"
msgstr "pkgsend: 不正な %s オプション -- %s"

#: ../pull.py:51
msgid ""
"Usage:\n"
"        pkgrecv -s server [-d dir] pkgfmri ...\n"
"        pkgrecv -s server -n"
msgstr ""
"使用方法:\n"
"        pkgrecv -s server [-d dir] pkgfmri ...\n"
"        pkgrecv -s server -n"

#: ../pull.py:74
#, python-format
msgid "Unable to open manifest: %s"
msgstr "マニフェスト %s を開けません"

#: ../pull.py:110
#, python-format
msgid "Unable to download files from: %s"
msgstr "%s からファイルをダウンロードできません"

#: ../pull.py:119 ../pull.py:164
#, python-format
msgid "Unable to create directory: %s"
msgstr "ディレクトリ %s を作成できません"

#: ../pull.py:137
#, python-format
msgid "Unable to extract file: %s"
msgstr "ファイル %s を抽出できません"

#: ../pull.py:152
#, python-format
msgid "Unable to download manifest %s from %s"
msgstr "マニフェスト %s を %s からダウンロードできません"

#: ../pull.py:152
#, python-format
msgid "Unable to download manifest %(get_url_path)s from %(server_url)s"
msgstr "マニフェスト %(get_url_path)s を %(server_url)s からダウンロードできません"

#: ../pull.py:172
#, python-format
msgid "Unable to open file: %s"
msgstr "ファイル %s を開けません"

#: ../pull.py:179
#, python-format
msgid "Error occurred while reading from: %s"
msgstr "%s からの読み取り中にエラーが発生しました"

#: ../pull.py:185
#, python-format
msgid "Error occurred while writing to: %s"
msgstr "%s への書き込み中にエラーが発生しました"

#: ../pull.py:224
#, python-format
msgid "Unable to download catalog from: %s"
msgstr "%s からカタログをダウンロードできません"

#: ../pull.py:234
#, python-format
msgid "Error while reading from: %s"
msgstr "%s からの読み取り中にエラーが発生しました"

#: ../pull.py:259
#, python-format
msgid "Illegal option -- %s"
msgstr "不正なオプション -- %s"

#: ../pull.py:272
msgid "must specify a server"
msgstr "サーバーを指定する必要があります"

#: ../pull.py:279
msgid "-n takes no options"
msgstr "-n はオプションを取りません"

#: ../pull.py:287
msgid "must specify at least one pkgfmri"
msgstr "pkgfmri は少なくとも 1 つ指定する必要があります"

#: ../pull.py:299
#, python-format
msgid "pkgfmri %s needs a version string"
msgstr "pkgfmri %s ではバージョン文字列を指定する必要があります"

#: ../pull.py:311
msgid "No files to retrieve."
msgstr "取得対象のファイルが存在しません。"

#: ../um/data/updatemanager-preferences.schemas.in.h:1
msgid ""
"A text message describing the updates is displayed near the panel's "
"Notification Area when updates become available if set to true."
msgstr ""
"true に設定された場合、更新が使用可能になった際に、その更新を"
"説明するテキストメッセージがパネルの通知領域の近くに表示されます。"

#: ../um/data/updatemanager-preferences.schemas.in.h:2
msgid "How often to check for updates"
msgstr "更新のチェック頻度"

#: ../um/data/updatemanager-preferences.schemas.in.h:3
msgid ""
"How often to check for updates. The valid values are Daily, Weekly, Monthly, "
"Never"
msgstr ""
"更新のチェック頻度を指定します。有効な値は「毎日」、"
"「毎週」、「毎月」、「なし」です"

#: ../um/data/updatemanager-preferences.schemas.in.h:4
msgid "Start delay"
msgstr "開始遅延"

#: ../um/data/updatemanager-preferences.schemas.in.h:5
msgid "The notify icon is displayed on startup if set to true."
msgstr "true に設定された場合、起動時に通知アイコンが表示されます。"

#: ../um/data/updatemanager-preferences.schemas.in.h:6
msgid ""
"The time, in seconds, that the updatemanagernotifier should wait, after "
"starting, before checking for updates."
msgstr ""
"開始したあとで更新をチェックする前に updatemanagernotifier が"
"待機する秒数。"

#: ../um/data/updatemanager-preferences.schemas.in.h:7
msgid "Whether to always display the icon on startup"
msgstr "起動時に常にアイコンを表示するかどうか"

#: ../um/data/updatemanager-preferences.schemas.in.h:8
msgid "Whether to display text message when updates are available"
msgstr "更新が使用可能になった際にテキストメッセージを表示するかどうか"

#: ../um/data/updatemanager.desktop.in.h:1
msgid "Install available updates"
msgstr "使用可能な更新をインストールします"

#: ../um/data/updatemanager.desktop.in.h:2 ../um/data/updatemanager.glade.h:18
#: ../updatemanagernotifier.py:266
msgid "Update Manager"
msgstr "更新マネージャー"

#: ../um/data/updatemanager.glade.h:1
msgid "<b>Boot Environment Name: </b>"
msgstr "<b>ブート環境名: </b>"

#: ../um/data/updatemanager.glade.h:2
msgid ""
"<b>Create New Boot Environment</b>\n"
"\n"
"Update All will create a new boot environment (BE) as a means\n"
"of archiving older software and sets it to be the default BE when\n"
"rebooting.\n"
"\n"
"An updated clone of the active BE is about to be created."
msgstr ""
"<b>新しいブート環境の作成</b>\n"
"\n"
"「すべて更新」を実行すると、古いソフトウェアを保存する手段として\n"
"新しいブート環境 (BE) が作成され、それがリブート時にデフォルトの\n"
" BE になります。\n"
"\n"
"アクティブ BE の更新済みクローンがまもなく作成されます。"

#: ../um/data/updatemanager.glade.h:9
msgid "<b>Evaluate</b>"
msgstr "<b>評価</b>"

#: ../um/data/updatemanager.glade.h:10
msgid "<b>_Details</b>"
msgstr "<b>詳細(_D)</b>"

#: ../um/data/updatemanager.glade.h:12
msgid "Close dialog when _finished"
msgstr "終了時にダイアログを閉じる(_F)"

#: ../um/data/updatemanager.glade.h:13 ../updatemanager.py:168
#: ../updatemanager.py:408 ../updatemanager.py:415 ../updatemanager.py:422
#: ../updatemanager.py:429 ../updatemanager.py:436
msgid "Download"
msgstr "ダウンロード"

#: ../um/data/updatemanager.glade.h:14 ../updatemanager.py:200
#: ../updatemanager.py:410 ../updatemanager.py:417 ../updatemanager.py:424
#: ../updatemanager.py:431 ../updatemanager.py:438
msgid "Index"
msgstr "インデックス"

#: ../um/data/updatemanager.glade.h:15
msgid "Install Update"
msgstr "更新のインストール"

#: ../um/data/updatemanager.glade.h:19 ../updatemanager.py:599
msgid ""
"Updates are available for the following packages.\n"
"Select the packages you want to update and click Install."
msgstr ""
"使用可能な更新が存在するパッケージは、次のとおりです。\n"
"更新するパッケージを選択し、「インストール」をクリックしてください。"

#: ../um/data/updatemanager.glade.h:22
msgid "_Install Updates"
msgstr "更新のインストール(_I)"

#: ../um/data/updatemanager.glade.h:24
msgid "_Proceed"
msgstr "続行(_P)"

#: ../um/data/updatemanager.glade.h:25
msgid "_Select all Updates"
msgstr "すべての更新を選択(_S)"

#: ../um/data/updatemanager.glade.h:26
msgid "_Update All"
msgstr "すべて更新(_U)"

#: ../um/data/updatemanagernotifier.desktop.in.h:1
msgid "Notify user when updates are available"
msgstr "更新が使用可能になった際にユーザーに通知します"

#: ../um/data/updatemanagernotifier.desktop.in.h:2
msgid "Update Manager Notifier"
msgstr "更新マネージャー通知"

#: ../updatemanager.py:116
#, python-format
msgid "Fetching catalog: '%s' ..."
msgstr "カタログ '%s' の取得中..."

#: ../updatemanager.py:120
msgid "Fetching catalog"
msgstr "カタログの取得中"

#: ../updatemanager.py:123
msgid "Creating Plan ... "
msgstr "計画の作成中... "

#: ../updatemanager.py:134
msgid "Creating Plan"
msgstr "計画の作成中"

#: ../updatemanager.py:145
#, python-format
msgid "Verifying: %s ..."
msgstr "%s の検証中..."

#: ../updatemanager.py:152
msgid "Verifying"
msgstr "検証中"

#: ../updatemanager.py:166
msgid "Completed"
msgstr "完了"

#: ../updatemanager.py:184 ../updatemanager.py:409 ../updatemanager.py:416
#: ../updatemanager.py:423 ../updatemanager.py:430 ../updatemanager.py:437
msgid "Install"
msgstr "インストール"

#: ../updatemanager.py:368
#, python-format
msgid ""
"GUI will not respond to any event! %s.                             Check "
"updatemanager.py signals"
msgstr ""
"GUI はどのイベントにも応答しません。%s。                             "
"updatemanager.py のシグナルをチェックしてください"

#: ../updatemanager.py:407 ../updatemanager.py:414 ../updatemanager.py:421
#: ../updatemanager.py:428 ../updatemanager.py:435
msgid "Evaluate"
msgstr "評価"

#: ../updatemanager.py:443
msgid "Evaluate - canceling..."
msgstr "評価 - キャンセル中..."

#: ../updatemanager.py:447
msgid "Download - canceling..."
msgstr "ダウンロード - キャンセル中..."

#: ../updatemanager.py:452
msgid "Evaluate - failed"
msgstr "評価 - 失敗しました"

#: ../updatemanager.py:456
msgid "Download - failed"
msgstr "ダウンロード - 失敗しました"

#: ../updatemanager.py:460
msgid "Install - failed"
msgstr "インストール - 失敗しました"

#: ../updatemanager.py:464
msgid "Index - failed"
msgstr "インデックス - 失敗しました"

#: ../updatemanager.py:606
msgid ""
"Updates are available for the following packages.\n"
"Click Update All to create a new boot environment and install all packages "
"into it."
msgstr ""
"更新が可能なパッケージは、次のとおりです。\n"
"新しいブート環境を作成し、その中にすべてのパッケージをインストールするには、"
"「すべて更新」をクリックします。"

#: ../updatemanager.py:644
msgid "Size (Meg)"
msgstr "サイズ (M バイト)"

#: ../updatemanager.py:725
#, python-format
msgid "count: %d"
msgstr "カウント: %d"

#: ../updatemanager.py:744 ../updatemanager.py:752
msgid "Error\n"
msgstr "エラー\n"

#: ../updatemanager.py:761
#, python-format
msgid "'%s' is not an install image\n"
msgstr "'%s' はインストールイメージではありません\n"

#: ../updatemanager.py:755
#, python-format
msgid "Version mismatch: expected %s received %s\n"
msgstr "バージョンの不一致: 期待値 %s 実際値 %s\n"

#: ../updatemanager.py:766
msgid ""
"\n"
"No Updates available"
msgstr ""
"\n"
"使用可能な更新が存在しません"

#: ../updatemanager.py:797
#, python-format
msgid ""
"\n"
"Description: \t%s\n"
"Name:        \t%s\n"
"FMRI:        "
msgstr ""
"\n"
"説明: \t%s\n"
"名前:        \t%s\n"
"FMRI:        "

#: ../updatemanager.py:819 ../updatemanagernotifier.py:227
#, python-format
msgid "%s is not valid image, trying root image"
msgstr "%s は有効なイメージではありません。ルートイメージを試しています"

#: ../updatemanager.py:829 ../updatemanagernotifier.py:237
#, python-format
msgid "%s is not valid root image, return None"
msgstr "%s は有効なルートイメージではありません。None を返します"

#: ../updatemanager.py:863
#, python-format
msgid ""
"\n"
"Fetching details for %s ..."
msgstr ""
"\n"
"%s の詳細の取得中..."

#: ../updatemanager.py:879
msgid ""
"\n"
"No details available"
msgstr ""
"\n"
"使用可能な詳細が存在しません"

#: ../updatemanager.py:908
msgid ""
"\n"
"Canceling update, please wait ..."
msgstr ""
"\n"
"更新のキャンセル中。しばらくお待ちください..."

#: ../updatemanager.py:913
msgid ""
"\n"
"Unable to cancel at this time."
msgstr ""
"\n"
"この時点でキャンセルすることはできません。"

#: ../updatemanager.py:916
msgid "Installing Updates"
msgstr "更新のインストール中"

#: ../updatemanager.py:948
msgid "ERROR"
msgstr "エラー"

#: ../updatemanager.py:950
msgid "Following Incorporated package(s) cannot be updated:"
msgstr "次の組み込みパッケージは更新できません:"

#: ../updatemanager.py:954
msgid "Update using: Update All\n"
msgstr "更新方法: すべて更新\n"

#: ../updatemanager.py:971 ../updatemanager.py:1163 ../updatemanager.py:1194
msgid ""
"\n"
"ERROR"
msgstr ""
"\n"
"エラー"

#: ../updatemanager.py:974
#, python-format
msgid ""
"%s\n"
"%s"
msgstr ""
"%s\n"
"%s"

#: ../updatemanager.py:977
#, python-format
msgid "%s\n"
msgstr "%s\n"

#: ../updatemanager.py:988 ../updatemanager.py:1103
msgid ""
"\n"
"Evaluate\n"
msgstr ""
"\n"
"評価\n"

#: ../updatemanager.py:997 ../updatemanager.py:1016
msgid "Update All failed during catalog refresh\n"
msgstr "「すべて更新」がカタログ再表示中に失敗しました\n"

#: ../updatemanager.py:1003
msgid "This is not an opensolaris image\n"
msgstr "これは OpenSolaris イメージではありません\n"

#: ../updatemanager.py:1021
msgid "Update All failure in plan creation:"
msgstr "「すべて更新」が計画作成時に失敗しました:"

#: ../updatemanager.py:1027
msgid "pkg(5) appears to be out of date and should be\n"
msgstr "pkg(5) は古いようなので、更新すべきです\n"

#: ../updatemanager.py:1036
msgid "Update All API failure in evaluation:"
msgstr "「すべて更新」の評価時に API 障害が発生しました:"

#: ../updatemanager.py:1041
msgid "Update All unexpected error in evaluation:"
msgstr "「すべて更新」の評価時に予期しないエラーが発生しました:"

#: ../updatemanager.py:1046
msgid "Update All finished successfully.\n"
msgstr "「すべて更新」が正常に終了しました。\n"

#: ../updatemanager.py:1064
#, python-format
msgid ""
"\n"
"Update All finished successfully in %1.f mins\n"
"\n"
msgstr ""
"\n"
"「すべて更新」が %1.f 分で正常に終了しました\n"
"\n"

#: ../updatemanager.py:1069
msgid ""
"\n"
"Update All finished successfully in < 1 min\n"
"\n"
msgstr ""
"\n"
"「すべて更新」が 1 分未満で正常に終了しました\n"
"\n"

#: ../updatemanager.py:1073
msgid "Please reboot after reviewing the release notes posted at:\n"
msgstr "次の場所で公開されているリリースノートを確認したあと、リブートしてください:\n"

#: ../updatemanager.py:1093
msgid "Nothing selected to update."
msgstr "更新対象として何も選択されていません。"

#: ../updatemanager.py:1097
msgid "Updating ..."
msgstr "更新中..."

#: ../updatemanager.py:1111
msgid "Update unexpected API error:"
msgstr "更新時の予期しない API エラー:"

#: ../updatemanager.py:1116
msgid "Update unexpected error:"
msgstr "更新時の予期しないエラー:"

#: ../updatemanager.py:1139
msgid "Packages to be installed:"
msgstr "インストールするパッケージ:"

#: ../updatemanager.py:1143
msgid "Update"
msgstr "更新"

#: ../updatemanager.py:1144
msgid "Update finished successfully."
msgstr "更新が正常に終了しました。"

#: ../updatemanager.py:1165
#, python-format
msgid ""
"%s Download failed:\n"
"%s"
msgstr ""
"%s ダウンロードが失敗しました:\n"
"%s"

#: ../updatemanager.py:1172
#, python-format
msgid "%s exceded available disc quota"
msgstr "%s が、使用可能なディスク割り当てを超えました"

#: ../updatemanager.py:1177 ../updatemanager.py:1201
#, python-format
msgid "%s unexpected error:"
msgstr "%s の予期しないエラー:"

#: ../updatemanager.py:1196
#, python-format
msgid ""
"%s Execute plan failed:\n"
"%s"
msgstr ""
"%s 計画の実行が失敗しました:\n"
"%s"

#: ../updatemanager.py:1218
msgid "Not enough disc space: the Update All action cannot "
msgstr "ディスク容量が不足しています: 「すべて更新」アクションはできません"

#: ../updatemanager.py:1390
msgid ""
"\n"
"Download\n"
msgstr ""
"\n"
"ダウンロード\n"

#: ../updatemanager.py:1397
#, python-format
msgid "\tpkg %d/%d: \tfiles %d/%d \txfer %.2f/%.2f(meg)"
msgstr "\tpkg %d/%d: \tファイル %d/%d \t転送 %.2f/%.2f (M バイト)"

#: ../updatemanager.py:1414
msgid ""
"\n"
"Install\n"
msgstr ""
"\n"
"インストール\n"

#: ../updatemanager.py:1416 ../updatemanager.py:1420
#, python-format
msgid "\t%s\t%d/%d actions"
msgstr "\t%s\t%d/%d アクション"

#: ../updatemanager.py:1436
msgid "Index\n"
msgstr "インデックス\n"

#: ../updatemanager.py:1437 ../updatemanager.py:1441
#, python-format
msgid "\t%-25s\t%d/%d actions"
msgstr "\t%-25s\t%d/%d アクション"

#: ../updatemanager.py:1505
msgid "Checking for new software"
msgstr "新しいソフトウェアのチェック中"

#: ../updatemanagernotifier.py:247
msgid "Updates are available"
msgstr "更新が使用可能です"

#: ../updatemanagernotifier.py:267
msgid ""
"Updates available\n"
"Please click on icon to update."
msgstr ""
"更新が使用可能です\n"
"更新する場合はアイコンをクリックしてください。"

#: ../updatemanagernotifier.py:331
msgid "Another instance of UpdateManagerNotify is running"
msgstr "UpdateManagerNotify の別のインスタンスが実行中です"

#: ../client.py:402
#, python-format
msgid "Created ZFS snapshot: %s"
msgstr "作成された ZFS スナップショット: %s"

#: ../client.py:1039
msgid "          Name:"
msgstr "                    名前:"

#: ../client.py:1040
msgid "       Summary:"
msgstr "                    概要:"

#: ../client.py:1047
msgid "      Category:"
msgstr "                カテゴリ:"

#: ../client.py:1041
msgid "         State:"
msgstr "                    状態:"

#. XXX even more info on the authority would be nice?
#: ../client.py:1044
msgid "     Authority:"
msgstr "                    権限:"

#: ../client.py:1045
msgid "       Version:"
msgstr "             バージョン:"

#: ../client.py:1046
msgid " Build Release:"
msgstr "        ビルドリリース:"

#: ../client.py:1047
msgid "        Branch:"
msgstr "                    分岐:"

#: ../client.py:1048
msgid "Packaging Date:"
msgstr "パッケージ化の日付:"

#: ../client.py:1049
msgid "          Size:"
msgstr "                 サイズ:"

#: ../client.py:1050
msgid "          FMRI:"
msgstr "                  FMRI:"

#: ../client.py:1811
msgid "image-create requires an authority argument"
msgstr "image-create には権限の引数が必要です"

#: ../client.py:1835
#, python-format
msgid "there is already an image at: %s"
msgstr "次の場所にすでにイメージが存在します: %s"

#: ../client.py:1836 ../client.py:1843
msgid "To override, use the -f (force) option."
msgstr "上書きするには、-f (force) オプションを使用します。"

#: ../client.py:1842
#, python-format
msgid "Non-empty directory: %s"
msgstr "空でないディレクトリ: %s"

#: ../client.py:1996
#, python-format
msgid "%s takes argument of form name=value, not %s"
msgstr "%s は、%s ではなく、形式 name=value の引数を取ります"

#: ../client.py:2018 ../client.py:2028
#, python-format
msgid "-R not allowed for %s subcommand"
msgstr "-R は %s サブコマンドでは許可されていません"

#: ../client.py:2196
#, python-format
msgid ""
"The pkg command appears out of sync with the libraries provided \n"
"by SUNWipkg. The client version is %(client)s while the library API version "
"is %(api)s"
msgstr ""
"pkg コマンドは、SUNWipkg で提供されているライブラリと同期がとれていない\n"
"ようです。クライアントのバージョンが %(client)s であるのに対して、ライブラリ API "
"のバージョンは %(api)s です。"

#: ../client.py:2208
#, python-format
msgid ""
"\n"
"\n"
"This is an internal error.  Please let the developers know about this\n"
"problem by filing a bug at http://defect.opensolaris.org and including the\n"
"above traceback and this message.  The version of pkg(5) is '%s'."
msgstr ""
"\n"
"\n"
"これは内部エラーです。この問題を開発者に知らせるために、\n"
"http://defect.opensolaris.org でバグ情報を入力し、上記のトレースバック\n"
"とこのメッセージを含めてください。pkg(5) のバージョンは '%s' です。"

#: ../gui/data/l10n.py:32
msgid "Administration and Configuration"
msgstr "管理と構成"

#: ../gui/data/l10n.py:33
msgid "Applets"
msgstr "アプレット"

#: ../gui/data/l10n.py:34
msgid "Application and Web Servers"
msgstr "アプリケーションと Web サーバー"

#: ../gui/data/l10n.py:35
msgid "C"
msgstr "C"

#: ../gui/data/l10n.py:36
msgid "C++"
msgstr "C++"

#: ../gui/data/l10n.py:37
msgid "Configuration and Preferences"
msgstr "構成と設定"

#: ../gui/data/l10n.py:39
msgid "Databases"
msgstr "データベース"

#: ../gui/data/l10n.py:40
msgid "Databases (System)"
msgstr "データベース (システム)"

#: ../gui/data/l10n.py:40
msgid "Desktop"
msgstr "デスクトップ"

#: ../gui/data/l10n.py:41
msgid "Display"
msgstr "ディスプレイ"

#: ../gui/data/l10n.py:42
msgid "Distribution Tools"
msgstr "ディストリビューションツール"

#: ../gui/data/l10n.py:43
msgid "Documentation"
msgstr "マニュアル"

#: ../gui/data/l10n.py:44
msgid "Enterprise Management"
msgstr "エンタープライズ管理"

#: ../gui/data/l10n.py:45
msgid "File Managers"
msgstr "ファイルマネージャー"

#: ../gui/data/l10n.py:46
msgid "File System"
msgstr "ファイルシステム"

#: ../gui/data/l10n.py:47
msgid "Fonts"
msgstr "フォント"

#: ../gui/data/l10n.py:48
msgid "GNOME and GTK+"
msgstr "GNOME と GTK+"

#: ../gui/data/l10n.py:49
msgid "GNU"
msgstr "GNU"

#: ../gui/data/l10n.py:51
msgid "Graphics and Imaging"
msgstr "グラフィックスと画像処理"

#: ../gui/data/l10n.py:52
msgid "Hardware"
msgstr "ハードウェア"

#: ../gui/data/l10n.py:53
msgid "High Performance Computing"
msgstr "HPC"

#: ../gui/data/l10n.py:54
msgid "Integrated Development Environments"
msgstr "統合開発環境"

#: ../gui/data/l10n.py:55
msgid "Internationalization"
msgstr "国際化"

#: ../gui/data/l10n.py:57
msgid "Java"
msgstr "Java"

#: ../gui/data/l10n.py:58
msgid "Libraries"
msgstr "ライブラリ"

#: ../gui/data/l10n.py:59
msgid "Libraries (System)"
msgstr "ライブラリ (システム)"

#: ../gui/data/l10n.py:60
msgid "Localizations (Desktop)"
msgstr "言語単位 (デスクトップ)"

#: ../gui/data/l10n.py:61
msgid "Localizations (System)"
msgstr "言語単位 (システム)"

#: ../gui/data/l10n.py:63
msgid "Networking"
msgstr "ネットワーク処理"

#: ../gui/data/l10n.py:65
msgid "Other Languages"
msgstr "その他のプログラミング言語"

#: ../gui/data/l10n.py:66
msgid "Other Peripherals"
msgstr "その他の周辺装置"

#: ../gui/data/l10n.py:67
msgid "PHP"
msgstr "PHP"

#: ../gui/data/l10n.py:68
msgid "Packaging"
msgstr "パッケージ処理"

#: ../gui/data/l10n.py:69
msgid "Perl"
msgstr "Perl"

#: ../gui/data/l10n.py:70
msgid "Plug-ins and Run-times"
msgstr "プラグインとランタイム"

#: ../gui/data/l10n.py:71
msgid "Ports"
msgstr "ポート"

#: ../gui/data/l10n.py:72
msgid "Printing"
msgstr "印刷処理"

#: ../gui/data/l10n.py:73
msgid "Python"
msgstr "Python"

#: ../gui/data/l10n.py:74
msgid "Ruby"
msgstr "Ruby"

#: ../gui/data/l10n.py:75
msgid "Scripts"
msgstr "スクリプト"

#: ../gui/data/l10n.py:76
msgid "Security"
msgstr "セキュリティー"

#: ../gui/data/l10n.py:77
msgid "Services"
msgstr "サービス"

#: ../gui/data/l10n.py:78
msgid "Sessions"
msgstr "セッション"

#: ../gui/data/l10n.py:79
msgid "Shells"
msgstr "シェル"

#: ../gui/data/l10n.py:80
msgid "Software Management"
msgstr "ソフトウェア管理"

#: ../gui/data/l10n.py:81
msgid "Sound and Video"
msgstr "サウンドとビデオ"

#: ../gui/data/l10n.py:82
msgid "Source Code Management"
msgstr "ソースコード管理"

#: ../gui/data/l10n.py:83
msgid "Storage"
msgstr "ストレージ"

#: ../gui/data/l10n.py:84 ../packagemanager.py:507
msgid "System"
msgstr "システム"

#: ../gui/data/l10n.py:85
msgid "System U"
msgstr "システム U"

#: ../gui/data/l10n.py:86
msgid "System Utilities"
msgstr "システムユーティリティー"

#: ../gui/data/l10n.py:87
msgid "Text Tools"
msgstr "テキストツール"

#: ../gui/data/l10n.py:88
msgid "Trusted"
msgstr "トラステッド"

#: ../gui/data/l10n.py:89
msgid "Trusted Extensions"
msgstr "Trusted Extensions"

#: ../gui/data/l10n.py:90
msgid "Virtualization"
msgstr "仮想化"

#: ../gui/data/l10n.py:91
msgid "Window Managers"
msgstr "ウィンドウマネージャー"

#: ../gui/data/l10n.py:92
msgid "X11"
msgstr "X11"

#: ../gui/data/l10n.py:94
msgid "X11 (System)"
msgstr "X11 (システム)"

#: ../gui/data/addmoresoftware.desktop.in.h:1
msgid "Add More Software"
msgstr "ソフトウェアの追加"

#: ../gui/data/packagemanager.glade.h:3
msgid "1. Delete old and unused BEs to free up disk space."
msgstr "1. 未使用の古い BE を削除してディスク容量を解放します。"

#: ../gui/data/packagemanager.glade.h:4
msgid "2. Change the default BE on your system."
msgstr "2. システム上のデフォルトの BE を変更します。"

#: ../gui/data/packagemanager.glade.h:20
msgid "<b>Manage your BEs to:</b>"
msgstr "<b>BE の管理:</b>"

#: ../gui/data/packagemanager.glade.h:33
msgid "Click to get list of newest packages."
msgstr "最新のパッケージの一覧を取得する場合にクリックします。"

#: ../gui/data/packagemanager.glade.h:34
msgid "Click to update all installed packages."
msgstr "すべてのインストール済みパッケージを更新する場合にクリックします。"

#: ../gui/data/packagemanager.glade.h:57
msgid "Legal"
msgstr "使用条件"

#: ../gui/data/packagemanager.glade.h:58
msgid "Manage Repositories"
msgstr "リポジトリの管理"

#: ../gui/data/packagemanager.glade.h:59
msgid "Manage Repositories..."
msgstr "リポジトリの管理..."

#: ../gui/data/packagemanager.glade.h:63
msgid ""
"Note: The current active BE cannot be deleted. \n"
"To delete this BE, boot into another BE, then return here."
msgstr ""
"注: 現在のアクティブ BE は削除できません。\n"
"この BE を削除するには、別の BE にブートしてからここに戻ります。"

#: ../gui/data/packagemanager.glade.h:70
msgid "Plan creation error."
msgstr "計画作成のエラー。"

#: ../gui/data/packagemanager.glade.h:79
msgid ""
"Review the information below.\n"
"Click OK to proceed.\n"
"Click Cancel to return to the Boot Environment\n"
"Management panel.\n"
"\n"
"Note: Changes will occur upon reboot."
msgstr ""
"下の情報を確認してください。\n"
"処理を続行するには「了解」をクリックしてください。\n"
"「ブート環境の管理」パネルに戻るには「取消し」を\n"
"クリックしてください。\n"
"\n"
"注: 変更はリブート時に適用されます。"

#: ../gui/data/packagemanager.glade.h:89
msgid "Select from the list to modify or remove existing repositories."
msgstr "既存のリポジトリを変更または削除する場合は、リストから選択してください。"

#: ../gui/data/packagemanager.glade.h:90
msgid "Select packages by marking the checkbox and click to Install/Update."
msgstr "チェックボックスにチェックマークを付けてパッケージを選択し、「インストール/更新」をクリックします。"

#: ../gui/data/packagemanager.glade.h:91
msgid "Select packages by marking the checkbox and click to Remove selected."
msgstr "チェックボックスにチェックマークを付けてパッケージを選択し、「選択したパッケージを削除します」をクリックします。"

#: ../gui/data/packagemanager.glade.h:95
msgid "The following BEs are available on your system:"
msgstr "システム上で次の BE を使用できます:"

#: ../gui/data/packagemanager.glade.h:99
msgid "Type text to search name and description of the package."
msgstr "パッケージの名前と説明を検索するためのテキストを入力します。"

#: ../gui/data/packagemanager.glade.h:100
msgid ""
"Type the repository name and URL you want to add as a new package source."
msgstr ""
"新しいパッケージソースとして追加するリポジトリの名前と URL を入力してください。"

#: ../gui/data/packagemanager.glade.h:102 ../gui/modules/installupdate.py:424
msgid "Update All failure in plan creation."
msgstr "「すべて更新」が計画作成時に失敗しました。"

#: ../gui/data/packagemanager.glade.h:118
msgid "gtk-close"
msgstr "gtk-close"

#: ../gui/modules/beadmin.py:69
msgid ""
"The <b>libbe</b> library was not found on your system.\n"
"All functions for managing Boot Environments are disabled"
msgstr ""
"<b>libbe</b> ライブラリがシステム上に見つかりませんでした。\n"
"ブート環境を管理するためのすべての機能が無効になっています"

#: ../gui/modules/beadmin.py:339
msgid "<b>Couldn't change Active Boot Environment to:</b>\n"
msgstr "<b>アクティブブート環境を次のものに変更できませんでした:</b>\n"

#: ../gui/modules/beadmin.py:344
msgid "<b>Couldn't delete Boot Environments:</b>\n"
msgstr "<b>ブート環境を削除できませんでした:</b>\n"

#: ../gui/modules/beadmin.py:410
msgid ""
"The <b>libbe</b> library couldn't  prepare list of Boot Environments.\n"
"All functions for managing Boot Environments are disabled"
msgstr ""
"<b>libbe</b> ライブラリはブート環境の一覧を準備できませんでした。\n"
"ブート環境を管理するためのすべての機能が無効になっています"

#: ../gui/modules/beadmin.py:445 ../gui/modules/beadmin.py:464
#, python-format
msgid "Error conversion from UTF-8 to %s."
msgstr "UTF-8 から %s への変換でエラーが発生しました。"

#: ../gui/modules/beadmin.py:481
#, python-format
msgid "Error conversion from %s to UTF-8."
msgstr "%s から UTF-8 への変換でエラーが発生しました。"

#: ../gui/modules/installupdate.py:150
msgid "Proceed"
msgstr "続行"

#: ../gui/modules/installupdate.py:302
msgid ""
"An unknown error occured while preparing the\n"
"list of packages\n"
"\n"
"Please let the developers know about this problem by filing\n"
"a bug at http://defect.opensolaris.org"
msgstr ""
"パッケージの一覧を準備中に不明なエラーが発生\n"
"しました。\n"
"\n"
"この問題を開発者に知らせるために、http://defect.opensolaris.org \n"
"でバグ情報を入力してください"

#: ../gui/modules/installupdate.py:306 ../gui/modules/installupdate.py:473
#: ../gui/modules/installupdate.py:521
msgid ""
"\n"
"\n"
"Exception value: "
msgstr ""
"\n"
"\n"
"例外値:"

#: ../gui/modules/installupdate.py:314
msgid ""
"Evaluation started.\n"
"Gathering packages information, please wait...\n"
msgstr ""
"評価が開始されました。\n"
"パッケージ情報を収集しています。しばらくお待ちください...\n"

#: ../gui/modules/installupdate.py:324
msgid ""
"Unexpected failure with\n"
"catalog refresh during install while \n"
"determining what to update."
msgstr ""
"インストール中に更新の対象を\n"
"判断しているとき、カタログ再表示で予期して\n"
"いないエラーが発生しました。"

#: ../gui/modules/installupdate.py:332
msgid ""
"Invalid repository certificate.\n"
"You can not install packages from the\n"
"repopsitory, which doesn't have\n"
"appropriate certificate."
msgstr ""
"無効なリポジトリ証明書。\n"
"適切な証明書が存在しないリポジトリ\n"
"からパッケージをインストールする\n"
"ことはできません。"

#: ../gui/modules/installupdate.py:341
msgid "Install/Update failure in plan creation."
msgstr "「インストール/更新」が計画作成時に失敗しました。"

#: ../gui/modules/installupdate.py:350
msgid ""
"Install failed.\n"
"The inventory is not correct."
msgstr ""
"インストールが失敗しました。\n"
"目録が正しくありません。"

#: ../gui/modules/installupdate.py:362 ../gui/modules/installupdate.py:437
msgid ""
"Please check the network connection.\n"
"Is the repository accessible?"
msgstr ""
"ネットワーク接続を確認してください。\n"
"リポジトリにアクセスできますか?"

#: ../gui/modules/installupdate.py:375
msgid "Remove failure in plan creation."
msgstr "「削除」が計画作成時に失敗しました。"

#: ../gui/modules/installupdate.py:401
msgid ""
"Unexpected failure with\n"
"catalog refresh during image-update while \n"
"determining what to update."
msgstr ""
"image-update の実行中に更新の\n"
"対象を判断しているとき、カタログ再表示で予期して\n"
"いないエラーが発生しました。"

#: ../gui/modules/installupdate.py:416
msgid ""
"pkg(5) appears to be out of date and should be\n"
" updated before running Update All.\n"
"Please update SUNWipkg package"
msgstr ""
"pkg(5) は古いようなので、「すべて更新」を\n"
"実行する前に更新すべきです。\n"
"SUNWipkg パッケージを更新してください"

#: ../gui/modules/installupdate.py:446
msgid ""
"Selected packages for update can\n"
"only be updated using Update All."
msgstr ""
"更新対象として選択されたパッケージは、\n"
"「すべて更新」を使用してのみ更新できます。"

#: ../gui/modules/installupdate.py:448
msgid "Unable to update"
msgstr "更新できません"

#: ../gui/modules/installupdate.py:453
msgid "The action for selected packages could not be completed."
msgstr "選択されたパッケージに対するアクションを完了できませんでした。"

#: ../gui/modules/installupdate.py:455
msgid "Unable to perform action"
msgstr "アクションを実行できません"

#: ../gui/modules/installupdate.py:468
msgid ""
"An unknown error occured while downloading the files\n"
"\n"
"Please let the developers know about this problem by filing\n"
"a bug at http://defect.opensolaris.org"
msgstr ""
"ファイルのダウンロード中に不明なエラーが発生しました\n"
"\n"
"この問題を開発者に知らせるために、http://defect.opensolaris.org \n"
"でバグ情報を入力してください"

#: ../gui/modules/installupdate.py:488
msgid ""
"An error occured while downloading the files\n"
"Please check your permissions and\n"
"network connection."
msgstr ""
"ファイルのダウンロード中にエラーが発生しました\n"
"アクセス権およびネットワーク接続を\n"
"確認してください。"

#: ../gui/modules/installupdate.py:515
msgid ""
"An unknown error occured while installing\n"
"updating or removing packages\n"
"\n"
"Please let the developers know about this problem by filing\n"
"a bug at http://defect.opensolaris.org"
msgstr ""
"パッケージのインストール、更新、または削除中\n"
"に不明なエラーが発生しました\n"
"\n"
"この問題を開発者に知らせるために、http://defect.opensolaris.org \n"
"でバグ情報を入力してください"

#: ../gui/modules/installupdate.py:536
msgid ""
"There was an error during installation.\n"
"The index is corrupted. You might wan't try to fix\n"
"this problem by running command:\n"
"pfexec pkg rebuild-index"
msgstr ""
"インストール中にエラーが発生しました。\n"
"インデックスが壊れています。次のコマンドを実行することによって、\n"
"この問題の解決を試みることをお勧めします:\n"
"pfexec pkg rebuild-index"

#: ../gui/modules/installupdate.py:544
msgid ""
"An error occured while installing the files\n"
"Please check your permissions"
msgstr ""
"ファイルのインストール中にエラーが発生しました\n"
"アクセス権を確認してください"

#: ../gui/modules/installupdate.py:550
msgid ""
"There was an error during installation.\n"
"The State of the image is incorrect and the operation\n"
"can't be finished."
msgstr ""
"インストール中にエラーが発生しました。\n"
"イメージの状態が正しくないため、操作を完了\n"
"できません。"

#: ../gui/modules/installupdate.py:557
msgid ""
"This is an Live Image. The install\n"
"operation can't be performed."
msgstr ""
"これはライブイメージです。インストール\n"
"操作を実行できません。"

#: ../gui/modules/installupdate.py:563
msgid ""
"There was an error during installation.\n"
"The Plan of the operation is missing and the operation\n"
"can't be finished."
msgstr ""
"インストール中にエラーが発生しました。\n"
"操作の計画がないため、操作を完了\n"
"できません。"

#: ../gui/modules/installupdate.py:607
msgid "Not enough disc space: selected action cannot "
msgstr "ディスク容量が不足しています: 選択されたアクションはできません"

#: ../gui/modules/installupdate.py:611 ../updatemanager.py:1269
msgid "Not Enough Disc Space"
msgstr "ディスク容量が不足しています"

#: ../gui/modules/installupdate.py:644
msgid "Evaluating package "
msgstr "パッケージを評価しています"

#: ../gui/modules/installupdate.py:687
msgid ""
"This action couldn't be finished.\n"
"Some of the selected packages depends on other.\n"
"Please review the dependencies."
msgstr ""
"このアクションを完了できませんでした。\n"
"選択されたパッケージの一部がほかのパッケージに依存しています。\n"
"依存関係を確認してください。"

#: ../gui/modules/repository.py:223
msgid ""
"Couldn't change the preffered authority.\n"
"Please check your permissions."
msgstr ""
"優先された権限を変更できませんでした。\n"
"アクセス権を確認してください。"

#: ../gui/modules/repository.py:223
msgid ""
"Couldn't change the preferred authority.\n"
"Please check your permissions."
msgstr ""
"優先された権限を変更できませんでした。\n"
"アクセス権を確認してください。"

#: ../gui/modules/repository.py:381 ../gui/modules/repository.py:439
#: ../gui/modules/repository.py:473
msgid ""
"\n"
"Please check your permissions."
msgstr ""
"\n"
"アクセス権を確認してください。"

#: ../gui/modules/repository.py:395 ../gui/modules/repository.py:452
msgid ""
"\n"
"Please check the network connection or URL.\n"
"Is the repository accessible?"
msgstr ""
"\n"
"ネットワーク接続または URL を確認してください。\n"
"リポジトリにアクセスできますか?"

#: ../modules/client/api_errors.py:108
msgid ""
"pkg: The following pattern(s) did not match any packages in the current\n"
"catalog. Try relaxing the pattern, refreshing and/or examining the catalogs"
msgstr ""
"pkg: 次のパターンは、現在のカタログ内のどのパッケージにも一致しませんでした。\n"
"パターンの条件緩和、再表示、カタログの検査のいずれか、あるいはそのすべてを試してください"

#: ../modules/client/api_errors.py:121
#, python-format
msgid "pkg: '%s' matches no installed packages"
msgstr "pkg: '%s' はどのインストール済みパッケージにも一致しません"

#: ../modules/client/api_errors.py:124
#, python-format
msgid "pkg: '%s' is an illegal fmri"
msgstr "pkg: '%s' は不正な FMRI です"

#: ../modules/client/api_errors.py:128
msgid "pkg: the following package(s) violated constraints:"
msgstr "pkg: 次のパッケージが制約に違反しました:"

#: ../modules/client/api_errors.py:162
msgid ""
"No matching package could be found for the following FMRIs in any of the "
"catalogs for the current authorities:\n"
msgstr ""
"次の FMRI に一致するパッケージが、現在の権限のどのカタログにも見つかり"
"ませんでした:\n"

#: ../modules/client/bootenv.py:215
#, python-format
msgid ""
"\n"
"A clone of %s exists and has been updated and activated.\n"
"On the next boot the Boot Environment %s will be mounted on '/'.\n"
"Reboot when ready to switch to this updated BE.\n"
msgstr ""
"\n"
"%s のクローンが存在しており、それが更新およびアクティブ化されました。\n"
"次回リブート時にはブート環境 %s が「/」にマウントされます。\n"
"準備が整ったらリブートしてこの更新済みの BE に切り替えてください。\n"

#: ../packagemanager.py:502
msgid "Applications"
msgstr "アプリケーション"

#: ../packagemanager.py:503
msgid "Desktop (GNOME)"
msgstr "デスクトップ (GNOME)"

#: ../packagemanager.py:504
msgid "Development"
msgstr "開発"

#: ../packagemanager.py:505
msgid "Distributions"
msgstr "ディストリビューション"

#: ../packagemanager.py:506
msgid "Drivers"
msgstr "ドライバ"

#: ../packagemanager.py:508
msgid "Web Services"
msgstr "Web サービス"

#: ../packagemanager.py:584
msgid "Fetching legal information..."
msgstr "使用条件情報を取得しています..."

#. Prompt user
#: ../packagemanager.py:791
msgid "Newer versions of SUNWipkg and SUNWipkg-gui\n"
msgstr "SUNWipkg と SUNWipkg-gui の新しいバージョン\n"

#: ../packagemanager.py:809
msgid ""
"Update All was not run.\n"
"\n"
"It can not be run until SUNWipkg and SUNWipkg-gui have been updated."
msgstr ""
"「すべて更新」は実行されませんでした。\n"
"\n"
"「すべて更新」は、SUNWipkg と SUNWipkg-gui が更新されるまで実行できません。"

#: ../packagemanager.py:1096
msgid "Not available"
msgstr "使用不可"

#: ../packagemanager.py:1430
msgid ""
"Network problem.\n"
"\n"
msgstr ""
"ネットワークの問題。\n"
"\n"

#: ../packagemanager.py:1431
msgid "Details:\n"
msgstr "詳細:\n"

#. 2790: As IPS and IPS-GUI have been updated the IPS GUI must be shutdown
#. and restarted
#: ../packagemanager.py:2080
msgid ""
"SUNWipkg and SUNWipkg-gui have been updated and Package Manager will now be "
"restarted.\n"
"\n"
"After restart select Update All to continue."
msgstr ""
"SUNWipkg と SUNWipkg-gui が更新されたため、パッケージマネージャーが再起動"
"されます。\n"
"\n"
"再起動後、「すべて更新」を選択して続行してください。"

#: ../packagemanager.py:2093
msgid ""
"Update All has completed and Package Manager will now exit.\n"
"\n"
"Please reboot after reviewing the release notes posted at:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"「すべて更新」が完了したため、パッケージマネージャーが終了します。\n"
"\n"
"次の場所で公開されているリリースノートを確認したあと、リブートしてください:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../updatemanager.py:815
#, python-format
msgid ""
"\n"
"Description:\t\t%s\n"
"FMRI:       \t\t%s"
msgstr ""
"\n"
"説明:\t\t%s\n"
"FMRI:       \t\t%s"

#: ../updatemanager.py:1029 ../updatemanager.py:1048
msgid ""
"Update All failed during catalog refresh\n"
"while determining what to update:"
msgstr ""
"カタログ再表示中に更新の対象を判断しているとき、\n"
"「すべて更新」が失敗しました:"

#: ../updatemanager.py:1097
msgid ""
"Please reboot after reviewing the release notes posted at:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"
msgstr ""
"次の場所で公開されているリリースノートを確認したあと、リブートしてください:\n"
"\n"
"http://opensolaris.org/os/project/indiana/resources/relnotes/200811/x86/"

#: ../updatemanager.py:1106
msgid "Update All Completed"
msgstr "「すべて更新」が完了しました"

#: ../updatemanager.py:1142
msgid "Update error in plan install:"
msgstr "計画インストール時の更新エラー:"

#: ../updatemanager.py:1213 ../updatemanager.py:1243
#, python-format
msgid "%s exceded available disc space"
msgstr "%s が、使用可能なディスク容量を超えました"

#: ../updatemanager.py:1265
msgid ""
"Not enough disc space: the Update All action cannot be performed.\n"
"\n"
"Click OK to launch BE Management to manage your existing BE's and free up "
"disc space."
msgstr ""
"ディスク容量が不足しています: 「すべて更新」アクションを実行できません。\n"
"\n"
"既存の BE を管理してディスク容量を解放するために BE 管理を起動するには、「了解」"
"をクリックしてください。"

#, python-format
msgid ""
"Accessing this restricted repository failed."
"\nYou either need to register to access this repository,"
"\nthe certificate expired, or you need to accept the repository"
"\ncertificate."
msgstr ""
"制限されたこのリポジトリへのアクセスに失敗しました。"
"\n登録してこのリポジトリへアクセスするか、"
"\n証明書の期限が切れている場合はリポジトリの証明書に"
"\n同意する必要があります。"

#, python-format
msgid ""
"An error occured while "
"downloading the files\nPlease check your permissions."
msgstr ""
"ファイルのダウンロード中に"
"エラーが発生しました\nアクセス権を確認してください。"

#, python-format
msgid "Download failure."
msgstr "ダウンロードの失敗。"

